### ISSUE TITLE
Fecha entrega idea/tema y etiquetas

### ISSUE THREAD

**Issue by jmndoza** [IIC2513-2020-1/syllabus#1]
Hola, en caso o no de presentar propuestas, cuándo se entregarían las ideas/temas a trabajar? como para empezar para la Entrega 1.
No he encontrado la forma de etiquetar la issue, según el link entregado ([Applying labels to issues and pull requests](https://help.github.com/en/github/managing-your-work-on-github/applying-labels-to-issues-and-pull-requests)), hay que marcar un checkbox.. que no esta.  

Gracias.

**Comment by gpvidal** [comment]
Hola @jerrymendoza ,

Lo antes posible, comenzaremos a trabajar en eso desde el lunes a medio día.
Con respecto a las labels, aún no los agregamos a la organización, por eso no pueden agregarlas.

Saludos,
