### ISSUE TITLE
Diagrama ER y comentarios self-containing

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2513-2020-1/syllabus#10]
Hola! Mi grupo tiene asignado el enunciado de DCConstituyo, y dentro de la red social estabamos pensando en poner posts con comentarios. El problema es que los comentarios pueden tener comentarios ellos mismos, y eso crea que una weak entity (los comentarios solo existen si existe el post) se autoreferencia. No sé como abordar esto, alguna idea?

Para referencia, esta es la parte del diagrama que me complica
![image](https://user-images.githubusercontent.com/48324565/78060554-1b494f80-7362-11ea-89c8-a5b0d3cc6347.png)
El problema de esto es que la pk del comentario contiene la pk del comentario padre, pero me encantaría dejar en evidencia que si el post muere o si el comentario padre muere, entonces el comentario hijo muere también.

Gracias!!

**Comment by gpvidal** [comment]
Hola @JJJGGGG ,

Creo que estás yendo un poco más allá con lo que un diagrama ER puede mostrar. Por decirlo de una forma coloquial, al diagrama ER no lo interesa lo que son llaves primarias y cualquier otro detalle con respecto a la implementación (por ejemplo borrado en cascada). Este diagrama, como su nombre lo dice, muestra solo las relaciones que hay entre distintas entidades.

Entonces sí puedes dibujar que un comentario tiene uno (o varios) comentarios (según sea tu solución). Luego, cuando tengas que implementarlo, te preocupas de cómo los vas a referenciar y como los vas a borrar :wink: 

Ánimo! :tada: 

Saludos,
