### ISSUE TITLE
Pregunta 1

### ISSUE THREAD

**Issue by aacamhi** [IIC2513-2020-1/syllabus#100]
Hola, tengo dos preguntas:

1) Podemos implementar otras clases aparte de las que nos piden? 

2) Para la funcion heal de magician a diferencia de las otras que nos piden no nos ponen los argumentos que recibe. Esto implica que la función no puede recibir ningún argumento o eso queda a criterio nuestro?

**Comment by gpvidal** [comment]
Haga supuestos.

Saludos,
