### ISSUE TITLE
Heroku Problema

### ISSUE THREAD

**Issue by vicentesh** [IIC2513-2020-1/syllabus#102]
Hola, tenemos un problema con el deploy de heroku, 
![image](https://user-images.githubusercontent.com/48304636/82003431-5a8be100-962e-11ea-96b1-8aac5ee2f58e.png)

Hemos intentado de todo pero no se soluciona :(

**Comment by mistico0121** [comment]
Es lo mismo de acá https://github.com/IIC2513-2020-1/syllabus/issues/49, a mi también me pasó. Instalando el plugin se soluciona.

**Comment by vicentesh** [comment]
siii, probamos con eso pero nos sale lo mismo, incluso revisamos si se creaban las vars y si están 😞 
![image](https://user-images.githubusercontent.com/48304636/82008082-c162c780-9639-11ea-80e0-c8e1df8b6919.png)

**Comment by gpvidal** [comment]
Hola @vicentesh ,

No tendrán algún archivo en su repositorio que esté sobreescribiendo las variables de entorno?

Saludos
