### ISSUE TITLE
Middleware sin return y buenas prácticas

### ISSUE THREAD

**Issue by Oisangui** [IIC2513-2020-1/syllabus#104]
Hola, tenemos el siguiente middleware en posts que redirecciona si es que no está autenticado, pero el eslinter nos dice que la función debería retornar consistentemente. Ignoramos el error del linter o colocamos la autenticación dentro del router respectivo?
```async function ensureAuthenticated(ctx, next) {
  if (ctx.state.currentUser) {
    return next();
  }
  ctx.redirect(ctx.router.url('posts.list'));
}

**Comment by gpvidal** [comment]
Hola @Oisangui ,

En general el linter no se equivoca :P

Partamos por eso:

El linter te está reclamando porque no tienes return en todos los caminos posibles, esto es:

```js
function myFunction(bool) {
  if (bool) return 'OK'; // <--- Si bool es true, entonces retornas
  bool = true; // <-- Si bool es false, entonces cambias su valor pero no retornas nada 
}
```

Para ser completamente consistente tu función, si retorna en algún punto, debería retornar en todos ellos. Entonces, si en la función de arriba agregas un `return bool;`, entonces dejarías de ver el error.

Ahora con respecto a tu *middleware* puedes ver que pasa algo similar, estás retornando solo dentro del bloque del `if` pero nada fuera de él. Es por esto que el linter te arroja el error.

Saludos,

**Comment by JJJGGGG** [comment]
Hola, soy el compañero de grupo de @Oisangui. Es correcto hacer la siguiente solucion? Nos traería algun error inesperado?
```js
  if (ctx.state.currentUser) {
    return next();
  }
  return ctx.redirect(ctx.router.url('posts.list'));
}
```

**Comment by gpvidal** [comment]
Hola @JJJGGGG ,

No veo, según lo que han puesto, que eso podría tener un problema.

Saludos,
