### ISSUE TITLE
Librería de sockets de javascript

### ISSUE THREAD

**Issue by dasolari** [IIC2513-2020-1/syllabus#105]
Hola! ¿Se puede usar en el proyecto el paquete de npm llamado _socket.io_ para establecer conexiones entre usuarios que se encuentran en una misma página?

**Comment by gpvidal** [comment]
Qué quieren hacer? :eyes:

**Comment by dasolari** [comment]
Es para implementar un chat que se actualice sin tener que refrescar la página manualmente.

**Comment by gpvidal** [comment]
Wow! Like it! Good luck! :+1: 

Sí lo pueden ocupar :wink:

**Comment by dasolari** [comment]
Gracias!
