### ISSUE TITLE
Subir archivos con digital ocean

### ISSUE THREAD

**Issue by ibaeza1** [IIC2513-2020-1/syllabus#106]
Hola!
Estaba viendo el video del profe para subir archivos y tengo un par de dudas:
1) En las variables de entorno tengo que poner el STORAGE_KEY y el STORAGE_SECRET pero no entendi cuales credenciales tengo que asignarle a esas variables en mi .env. de donde las saco?
 
2) El profe sube archivos csv pero yo quiero subir imagenes. estuve leyendo y queria saber si para subir imagenes era necesaria estas lineas:
` const coursesRow = parse(fileContent, { columns: true, delimiter: ';' });`
  `const coursesPromises = coursesRow.map((row) => {`
   ` const course = ctx.orm.course.build(row);`
 `   return course.save({ fields: ['code', 'name', 'description'] });
  });`
ya que segun yo eso es para designar las columnas del csv.

3) El boton para subir que se llama upload puede tener otro name? o tiene que si o si ser upload?
este:
` <input type="submit" name="upload" value="Upload" />`

Gracias! :)

**Comment by gpvidal** [comment]
Hola @ibaeza1 ,

Te respondo:

1. En Digital Ocean tienes que pedir una API keys para tu cuenta. Barra lateral (izquierda), abajo, aparece una sección de API.

2. Efectivamente ese código es para resolver el problema particular que les mencioné, que era cargar un archivo CSV. Si tu vas a cargar una imagen debes hacer otro procedimiento.

3. El botón puede tener otro nombre, incluso podría no tenerlo.

Saludos!

**Comment by ibaeza1** [comment]
Gracias!
