### ISSUE TITLE
load de scripts

### ISSUE THREAD

**Issue by topkaj** [IIC2513-2020-1/syllabus#108]
Hola, estoy teniendo dudas respecto a la forma correcta de cargar scripts externos en una vista, ya que de la forma habitual usando la ruta relativa no me funciona. Leí que esto se podía solucionar usando `koa-static` para crear archivos o carpetas estáticas, sin embargo, por una issue anterior creo que algo tiene que ver la carpeta `assets`, pero desconozco la forma en que funciona `assetPath` ni como debiese usarse en este caso. Si pudiesen orientarme al respecto, gracias de antemano :)

**Comment by gpvidal** [comment]
Hola @topkaj ,

A qué te refieres con scripts externos? A scripts escritos por ti?

Saludos,

**Comment by topkaj** [comment]
así es, escritos por mi

**Comment by gpvidal** [comment]
Aquí dejé un PR en `my-university` relacionado a eso :wink: 

https://github.com/IIC2513-2020-1/my-university/pull/6

Saludos,

**Comment by topkaj** [comment]
La he revisado, pero sigo sin entender si el `example.js` está siendo cargado para todos los archivos o sólo para el `index.html.ejs`, de ser lo último, ¿en qué parte del código se especifica eso?

**Comment by gpvidal** [comment]
Hola @topkaj ,

Está siendo cargado para todos las páginas.

Saludos,

**Comment by topkaj** [comment]
gracias, me queda más claro :)

**Comment by topkaj** [comment]
hola,

y en caso de querer que se cargue en sólo una vista particular, ¿cómo debiera hacerlo?

**Comment by gpvidal** [comment]
Lamentablemente, por como está armado el template, no puedes hacerlo. Esto no es solo como se comporta nuestro *template*, sino también como lo hace Rails y otros.

Saludos,
