### ISSUE TITLE
Carpeta Services para subir archivos

### ISSUE THREAD

**Issue by ibaeza1** [IIC2513-2020-1/syllabus#109]
Hola!
Queria preguntar cual era la funcion de la carpeta services que hizo el profe en el video para subir archivos, ya que revise el codigo y no veo que este usada en ninguna parte.
Es necesaria? como se esta usando exactamente?
Gracias! :)

**Comment by gpvidal** [comment]
Hola @ibaeza1 !

Yo la hice porque agregué un archivo a esa carpeta. Particularmente este:

https://github.com/IIC2513-2020-1/my-university/pull/5/files#diff-1e0bee6de321329047a12e4babc4bcf8

Tu podrías no utilizar eso, entonces no tienes que crearla.

Uds son libres de crear carpetas para ordenar su código como quieran :smile: 

Saludos,
