### ISSUE TITLE
Input de Callback

### ISSUE THREAD

**Issue by fabarros** [IIC2513-2020-1/syllabus#11]
Hola! tengo una duda respecto de cual es el input que reciben los callbacks. 
Los ejemplos que he visto son del tipo:
`asyncFunc(function callback(return_de_asyncFunc){
do_something; 
return whatever;})`
Mi duda es, tengo que saber a priori qué y cuántos elementos retorna la `asyncFunc` para saber qué usar de callback, cierto? La función `callback` sabe inmediatamente que lo que está recibiendo como input es el output de `asyncFunc`? Cómo lo sabe? Y si `asyncFunc` retorna más de un elemento?
Gracias!

**Comment by gpvidal** [comment]
Hola @fabarros !

En general si una función recibe un *callback*, te van a decir qué características tiene que cumplir (debería ser parte de alguna documentación). No deberías estar adivinando cuales son los parámetros que debe recibir.

Saludos!
