### ISSUE TITLE
Disponibilidad semana de ajuste

### ISSUE THREAD

**Issue by Kitaps** [IIC2513-2020-1/syllabus#110]
Hola, 

van a estar respondiendo issues durante la semana de ajuste?

Gracias :)

**Comment by gpvidal** [comment]
Hola @Kitaps ,

Yo al menos sí. Los ayudantes también tienen pausa de ajuste, pero si quieren pueden participar también.

Saludos,

**Comment by Kitaps** [comment]
Gracias por la pronta respuesta :D
