### ISSUE TITLE
Librerías obsoletas en el proyecto

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2513-2020-1/syllabus#111]
Hola! Tengo una duda sobre el template del proyecto. Al hacer ```npm install```, me salen estos mensajes:
![image](https://user-images.githubusercontent.com/48324565/82739707-cb5a8980-9d0f-11ea-9681-cdb8fc1ff878.png)
Todas estas librerías están obsoletas en el template. Esto trae algún tipo de problema? Podemos actualizarlas sin problema en nuestros repositorios?

Gracias

**Comment by iaacosta** [comment]
Hola!

Primero hay que entender que así como tú puedes instalar paquetes para facilitar ciertas cosas de tu desarrollo, los que publican los paquetes que usas hacen lo mismo e instalan otros.

Para ver que paquetes tienes instalados, puedes entrar al `package.json` de tu proyecto y tendras todas las dependencias que usas y sus versiones. De hecho, si entras a `node_modules/<cualquierPaquete>` encontraras un `package.json` con los respectivos paquetes que utilizan, distintos a los que tu usas en tu proyecto.

Puedes actualizar las versiones hasta cierto punto. Generalmente los versionamientos de paquetes de Node siguen [Semantic Versioning](https://semver.org/), donde cada dígito de la versión significan:

```
      1.     12.      2
<major>.<minor>.<patch>
```

- major: cambio significativo, no se te asegura retrocompatibilidad
- minor: feature / cambio menor y hay retrocompatibilidad
- patch: arreglo de algún bug particular y hay retrocompatibilidad.

Generalmente, si puedes hacer upgrades de tus paquetes si son minor o patch con `npm update` o `yarn upgrade`, pero no podrás hacer cambios que involucren un cambio en el dígito _major_

La gravedad del warning depende de cada uno. Por ejemplo, `chokidar` te dice que cuando uses Node v14+ no funcionará, y eso es potencialmente grave dependiendo de lo que uses en tu app. Probablemente saldrá alguna actualización del paquete para esa versión de Node y eventualmente tendrías que hacer un update al template para poder usarlo.

Espero que te quede más claro más o menos porque salen los warnings y porque eventualmente podrían siguen saliendo aunque actualices :smile:

**Comment by gpvidal** [comment]
Muy buena explicación de @cho19 :wink: . De hecho, mi pregunta era si no estabas ocupando node 14.x ya que me parece raro que te avise por adelantado.
