### ISSUE TITLE
Error al subir archivos

### ISSUE THREAD

**Issue by ibaeza1** [IIC2513-2020-1/syllabus#112]
Hola!
Estoy tratando de subir los archivos a digitalocean ( aun :o ) pero me sale este error
![image](https://user-images.githubusercontent.com/37149485/82742293-4335ad80-9d2a-11ea-8e24-21076b962cd3.png)
No se que significa la verdad, busqué en google y no sale nada util.
Hice todo lo que dijo el profe en el video, lo unico que tengo diferente es que el archivo que quiero subir no esta dentro de mi app si no que es algo que tengo en mi escritorio pero no se si eso afecta.
Gracias!

**Comment by gpvidal** [comment]
Hola @ibaeza1 ,

La IP que aparece ahí es una IP privada. Tienes todavía este problema? Si es así, Cómo te estás conectando? estás usando docker o algo similar?

Saludos,

**Comment by ibaeza1** [comment]
Sii aun lo tengo :( Y estoy haciendo literalmente lo que usted hizo en el video. No se la verdad como se esta conectando pero si se que no estoy usando nada parecido a docker.

**Comment by gpvidal** [comment]
Lo estás desarrollando en windows o en linux?

**Comment by ibaeza1** [comment]
En windows

**Comment by gpvidal** [comment]
Solo para corroborar,

Creaste tu "space" de Digital Ocean en la región SF2? porque de no ser así, la configuración cambia un poco. En particular cambia el endpoint.

Saludos,

**Comment by ibaeza1** [comment]
Sii esta en ese

**Comment by gpvidal** [comment]
Ya, me doy! Puedes subir tu código actual a un branch en tu repo y decirme qué branch es para revisar?

Saludos!

**Comment by ibaeza1** [comment]
Esta en mi repo! la branch nacha_e4 es el ultimo commit 😃

**Comment by vtespinosa** [comment]
Hola, cuando internto subir fotos me aparece el mismo error, con la misma IP.

**Comment by gpvidal** [comment]
Hola @vtespinosa , voy a revisar el código de @ibaeza1 para ver si hay algo extraño. Por mientras, tu tb desarrollas en windows?

**Comment by vtespinosa** [comment]
@gpvidal desarrollo en linux (ubuntu 18.04)

**Comment by vtespinosa** [comment]
@gpvidal @ibaeza1 Logré solucionar el error.
Antes de hacer el upload a digital ocean, puse un `console.log(fileStorage)` para ver si había un problema con las access keys y me di cuenta que no se estaban guardando (como se puede ver en la foto), por lo que la página no podía acceder al space.

![Screenshot from 2020-05-25 21-45-08](https://user-images.githubusercontent.com/42243507/82852982-600ce500-9ed2-11ea-897c-f1f0da276e9f.png)

Para solucionarlo agregué la línea `require('dotenv').config();` al principio de config/storage.js. @ibaeza1 no se si estás ocupando dotenv o direnv para manejar las variables de entorno, pero para dotenv, esto lo soluciona.

**Comment by gpvidal** [comment]
Ya, creo que deberían probar con un par de cosas:

1.- Borrar la carpeta `node_modules` y correr `yarn install` de nuevo
2.- Verificar si efectivamente tienen asignadas las variables de entorno

**Comment by gpvidal** [comment]
Jajajaja @vtespinosa creo que publicamos casi al mismo tiempo. Lo que mencionas justamente cae en el punto 2 que mencionaba :wink: 

Que bueno que lo solucionaste!

**Comment by vtespinosa** [comment]
@gpvidal jajajja si me di cuenta. Gracias por la ayuda!

**Comment by Gorgola22** [comment]
Una pregunta, en el archivo .env habría que agregar algún valor para 'STORAGE_KEY' y 'STORAGE_SECRET' ?
También me gustaría saber cómo puedo revisar los archivos que subo en la página de cloud.digitalocean.com
Graciass!!!

**Comment by gpvidal** [comment]
Hola @Gorgola22 ,

El servicio de Digital Ocean que se utiliza para subor archivos se llama "Spaces", yo partiría leyendo la información sobre ese servicio. También utilizamos el paquete `pkgcloud` para subir los archivos, por lo que en la documentación de ese paquete también puedes encontrar información útil.

Por último, en el video de upload de archivos se trata lo que preguntas.

Saludos!

**Comment by Gorgola22** [comment]
Hola @gpvidal ,

Pregunté eso porque en el video de **upload** no sale explícita esa información. De hecho me dijeron después que debía crearme una cuenta en digitalocean para obtener las keys, pero cuando lo hago, esta me pide poner tarjeta de crédito (supongo que para pagar cada cierto tiempo), lo que no se ha especificado en ningún lado, siendo algo muy importante que el curso debería informar a los alumnos.

Aparte de eso, leeré para aprender de "Spaces" de Digital Ocean y la librería pkgcloud, esperando a que el ramo de una solución respecto al tema del método de pago solicitado, con el fin de acceder compatiblemente a las facilidades del proveedor de Amazon con Amazons3 o DigitalOcean.

Gracias de antemano,
Eduardo O.

**Comment by gpvidal** [comment]
Hola @Gorgola22 ,

**No es requisito usar Digital Ocean para tu proyecto**, de hecho yo respondí la pregunta que tu realizaste sobre este proveedor. Incluso, en clases les mencioné esto y les dí alternativas como por ejemplo Cloudinary, que no pide tarjeta de crédito.

Atte.
