### ISSUE TITLE
Awaits en vista

### ISSUE THREAD

**Issue by Kitaps** [IIC2513-2020-1/syllabus#113]
Hola 

estoy tratando de hacer que haciendo un 
`algosList.forEach((algo) => {`
`let user_elegido = await ctx.orm.user.findOne({ where: user.id == algo.userID })}`

Pero esto sería en una view. En las views se hacen awaits? Según tengo entendido eso es solo en las routes. 
Además de eso, que estoy haciendo mal? Que me tira errores de que no encuentra user. Que podria ser?

**Comment by iaacosta** [comment]
Hola!

No, no deberías poder usar `await` en las vistas, principalmente porque no tienes una función `async` que lo acompañe. Tampoco puedes usar promesas en general, por ejemplo, si tratas esto:

```html
<% let variable = 20; %>

<p>
  <% promesaDesdeTuRuta.then(() => variable = 10) %>
  <%= variable %>
</p>
```

Tu vista hara render de `20` y no `10`, porque en ninguna parte señalas  que hay que esperar a la `promesaDesdeTuRuta` (ni tampoco puedes).

Respecto a tu ejemplo, recuerda que todo `await` debe estar en una función `async`, y algo muy común que pasa es que se intenta esto:

```js
const asyncFunction = async () => {
  const array = await getArray();
  const processedArray = array.forEach((element) => await element.doSomethingAsync());
};
```

Pero no es válido, porque el `async` de `asyncFunction` solo sirve para el scope directo de la función (e.g. `getArray()`) y no para los callbacks que creas y pasas a otras funciones (e.g. `(element) => await element.doSomethingAsync()`). En este caso lo _"correcto"_ sería agregar un `async` al callback.

Digo "correcto" porque en realidad eso no haría que esperes a todas las promesas que estás generando a medida que iteras, y tampoco puedes hacer `await algo.forEach(...)` porque `forEach` no es asíncrono. Ante esto, hay dos soluciones que se usan bastante:

1. Hacer un `for` que sea parte del scope directo de la función con `async`, y aplicar `await` dentro de este
2. Hacer un arreglo con todas tus promesas, que tu callback contenga `async` y esperar al arreglo con `Promise.all`.

Para tu ejemplo:

**for**
```js
for (const algo of algoList) {
  let user_elegido = await ctx.orm.user.findOne({ where: user.id === algo.userID });
}
```

**Promise.all**
```js
const promises = algosList.map(async (algo) => {
  let user_elegido = await ctx.orm.user.findOne({ where: user.id === algo.userID });
});
const resolvedPromises = await Promise.all(promises);
/* resolvedPromises[i] será la resolución de la i-esima promesa (en este caso, al no haber return, será siempre nulo) */
```

Cabe mencionar que la alternativa del `for` da un warning en el linter del template, porque se prefiere lo segundo (más info [aquí](https://eslint.org/docs/rules/no-await-in-loop))

Espero haber aclarado tus dudas :smile: 

P.D.: recuerda que `==` no es lo mismo que `===`, por si tienes comportamientos medios raros :cold_sweat:

**Comment by Kitaps** [comment]
Muchas gracias por la respuesta tan completa. Me quedó muy claro.
