### ISSUE TITLE
Dar un token a id de usuario

### ISSUE THREAD

**Issue by ibaeza1** [IIC2513-2020-1/syllabus#114]
Hola!
Estoy tratando de darle un token a mi id de usuario para que no se guarde en la cookie pero no entiendo muy bien como hacerlo.
Estoy usando jsonwebtoken para encriptar el id, y lo que creo que hay que hacer es que en el modelo de user hago un
`user.beforeCreate(buildIdToken);`
que seria una funcion que me encripta el id y lo guarda en la base de datos.
Luego cuando hago un new session en el router de sessions, donde dice 
`ctx.session.userId = user.id;`
en lugar de darle user.id darle la funcion que desencripta el id.
La cosa es que no se si es asi exactamente porque ahi igual le estaria dando el id directamente.
Vi varios tutoriales de como usar jwt pero no entiendo bien como aplicarlo a la app.
Si me pudieran guiar mas o menos a como hacerlo seria bacan :)
Gracias!

**Comment by ibaeza1** [comment]
**UPDATE**: Al final no logre usar jsonwebtokens asi que hice yo una funcion que encripte el id que es algo como pasarla a base64 y luego cambiarle los caracteres de lugar y para desencriptarlo volver los caracteres a su lugar y pasarlo a utf8.
Mi problema es que cuando voy a hacer login de un usuario si la password es correcta en lugar de hacer
`ctx.session.userId = user.id`
hago
`ctx.session.userId = encriptar(user.id)`
que al final le da el id del usuario encriptado.
Luego en las rutas tengo la funcion desencriptar, que cada vez que hago un get, por ejemplo el users.list, tengo:
`router.get('users.show', '/:id/show', loadUser ,desencriptar, async (ctx) => {.`
que se supone que deberia desencriptar el user.id
La cosa es que cuando le doy el id encriptado a la session se me guarda como por siempre encriptado y no se desencripta, y despues cuando trato de entrar al localhost me pone por default el id encriptado que es un string por lo que me dice que el id es de tipo integer y no acepta string, y arreglar esto es muy complicado, tengo que borrar la base de datos y reiniciar mi app y cambiar el atributo id de tipo integer a string a integer denuevo :O.
Si solo hago drop de la base de datos aun me deja por default el id encriptado y no puedo hacer nada.
No se si estoy haciendo algo mal cuando le paso el id encriptado al ctx.session.userId pero yo creeria que haciendo eso solo le estoy encriptando el id al usuario logeado pero no cambio nada en la base de datos.
No se si se entendio mi problema pero en verdad no entiendo como hacerlo.
Ayudaa! :(
Gracias!

**Comment by gpvidal** [comment]
Hola @ibaeza1 ,

Lo que tienes que hacer es exactamente lo que aparece en el esquema de la página 9 del pdf de la clase de sesión.

Para este caso *jsonwebtokens* o (JWTs para los amigos) no es necesario.

Creo que estás atascada en el proceso de generar un session id, y para eso puedes usar el paquete `bcrypt` que usamos para generar claves u otro que te permita generar una cadena aleatoria de caracteres.

Ojo que esta cadena debería ser generada cuando el usuario ingresa correctamente una clave.

Uno de los requisitos es que no hagas justamente `ctx.session.userId = user.id`, pero podrías hacer algo del estilo `ctx.session.sessionId = 'esteEsMiTokenRandomAsignadoAEsteUsuario'`. Y de alguna forma relacionar `'esteEsMiTokenRandomAsignadoAEsteUsuario'` con el usuario en cuestión.

Saludos!

**Comment by ibaeza1** [comment]
Entonces al final lo que podria hacer es no encriptar el id en si si no darle a la sesion una cadena random de caracteres y despues asociarlos al id del usuario, asi no estaria cambiando el id.

**Comment by gpvidal** [comment]
Claro, puedes generar una cadena random cada vez que el usuario ingrese correctamente sus credenciales :slightly_smiling_face: y esa cadena se la mandas por la cookie :+1:

**Comment by ibaeza1** [comment]
ya! lo voy a probar asi.
Gracias! :)

**Comment by ibaeza1** [comment]
UPDATE: Al final lo que hice fue que el ctx.session.userId fuera el mail del usuario encriptado con bcrypt y cuando lo necesito usar hago un compare con el mail y retorno el id del usuario con ese mail.
Supongo que hacer eso esta bien jajaja porque fue lo unico que me funciono.

**Comment by gpvidal** [comment]
Pero eso no es random o si? si no es random yo podría suplantarlo (sabiendo el email o no)?

**Comment by ibaeza1** [comment]
Pero se esta guardando un hash en la cookie no el email en si entonces si se trata de suplantar la cookie con el email la funcion desencriptar no podria desencriptarlo siendo el mail. Al final no haria match con el email al momento de desencriptar un correo no encriptado. 🤔

**Comment by gpvidal** [comment]
Pero yo podría generar ese hash sabiendo el mail del usuario? Si es random está bien.

Te lo pregunto porque creo que tienes una confusión. Si te fijas en el diagrama que te mencioné (de las diapos de la clase), en ningún punto habla de desencriptar. Tu generas una cadena de caracteres que se la mandas al usuario mediante la cookie y luego, por contrato, el usuario te la manda de vuelta en cada request. Tu debes saber, de alguna forma, a que usuario corresponde la cadena de texto que recibiste.

De hecho, hice referencia a ese diagrama porque ahí aparecen todos los pasos :wink: 

Saludos,

**Comment by ibaeza1** [comment]
Sii nos fijamos en eso y lo solucionamo y ya funciona todo bien :)
Gracias!

**Comment by gpvidal** [comment]
Excelente! :+1:
