### ISSUE TITLE
<script> defer en HTML

### ISSUE THREAD

**Issue by Kitaps** [IIC2513-2020-1/syllabus#115]
Hola, 
espero que hayan tenido un buen fin de semana.

En un tutorial que vi dicen que cuando hacen script en html meter defer, como en el ejemplo:
`<script src="my-js-file.js" defer></script>`
Esto para asegurarse que esté cargado el html antes de que se ejecute el js. 
Pero en los ejemplos vistos en clase ni en las views del template hacen eso. 

En el templare supongo que es xq usamos ejs. Pero en los ejemplos? Hay alguna razón para no hacerlo?
Creo recordar que en una clase el profesor Gabriel hablaba algo de tiempo de carga y ejecución de js pero no me acuerdo de los detalles. 

De antemano gracias.

**Comment by gpvidal** [comment]
Es una buena pregunta!

En el caso del template es porque no es necesario hacer algo de ese estilo por como está cargado.

En los ejemplos, nosotros escuchamos al evento `DOMContentLoaded`, que espera que todo el contenido esté cargado y luego ejecuta nuestro código JS.

En el caso de `defer` en los scripts, este es una propiedad booleana que permite que los scripts se ejecuten apenas el DOM esté listo. Esto es antes que el evento `DOMContentLoaded`, ya que este último espera que también los scripts esten cargados.

Saludos!

**Comment by Kitaps** [comment]
Gracias, 

entonces si hacemos `DOMContentLoaded` no es necesario hacer defer. Ahh perfecto, me había costado entender que era eso del `DOMContentLoaded`.
