### ISSUE TITLE
Script no encontrado

### ISSUE THREAD

**Issue by dasolari** [IIC2513-2020-1/syllabus#116]
Hola! Estoy intentando cargar un script antes del `</body>` tag en el archivo layout.html.ejs. 
Este script se encuentra en la carpeta _src_, por lo que el path que le estoy dando es: `src="../nombre_script.js"` (de hecho, _VS Code_ lo marca como correcto), pero al cargar la página me dice que el archivo no existe. He intentado con muchos paths distintos y ninguno funciona. ¿Qué puedo hacer para solucionar esto?

**Comment by gpvidal** [comment]
Hola @dasolari ,

ese `nombre_script.js` lo hiciste tu?

Saludos,

**Comment by dasolari** [comment]
Si.

**Comment by gpvidal** [comment]
Puede revisar esta issue donde abordamos lo mismo :wink: 

https://github.com/IIC2513-2020-1/syllabus/issues/108

Saludos,

**Comment by dasolari** [comment]
Gracias!
