### ISSUE TITLE
css para los emails

### ISSUE THREAD

**Issue by bgsamilla** [IIC2513-2020-1/syllabus#117]
Tengo una duda con los css en los emails.
He estado dando un vistazo a la documentación de sendgrid respecto a eso y dice "Always use inline CSS", lo que va en contra de la regla del curso sobre no usar el tag style.
Entonces para esta parte en especifico podemos usar los estilos de esa forma o tenemos que hacerlo de otra manera. (¿Cual? Probé con el método "normal" y no funciona).

Saludos!

**Comment by gpvidal** [comment]
Hola @BSamilla !

> He estado dando un vistazo a la documentación de sendgrid respecto a eso y dice "Always use inline CSS", lo que va en contra de la regla del curso sobre no usar el tag style.

Muy bien! Efectivamente nosotros tenemos como regla en nuestros sitios web no usar el tag `style` o la propiedad en los elementos HTML.

Sin embargo, en los correos la cosa cambia. Creo haberlo mencionado en una ocasión, pero de no ser así aquí está: en los correos, y tal como dice la documentación de Sendgrid, sí hay que escribir los correos con estilo *inline* (usando la propiedad `style` de los elementos HTML) o con el tag `style`. La verdad es que no se los dije así, pero les mencioné que existían algunos casos en los que hay que escribir los estilos mezclado con la estructura HTML. Este es uno de ellos.

La razón es porque los visores de correo son limitados (no son navegadores completos), y por temas de compatibilidad es mejor escribirlos con los estilos incluidos en el correo. Ojo que esto es **solo para el caso del correo electrónico**, nuestras páginas se deben seguir escribiendo con los estilos separados.

Saludos!
