### ISSUE TITLE
modelsList

### ISSUE THREAD

**Issue by Kitaps** [IIC2513-2020-1/syllabus#118]
Hola, 

tengo una duda respecto a las listas de instancias. 
Lo que pasa es que digamos que tengo un modelo `a` y un modelo `b` donde `a` tiene un atributo `bId`.

Lo que quiero hacer es que en el view de `a` muestre algunos atributos del `b` correspondiente. 

Para esto en el scope de `asList.foreach( (a) => {`
tengo `const a_b = bsList.find(b => b.id === a.bId)`

Pero me dice que `bsList` no está definido, pese que en el router de `b` se define de la misma manera que la lista de `a` en su router.

Por que no puedo acceder a esta? O estoy haciendo algo mal?

**Comment by gpvidal** [comment]
Hola @Kitaps ,

Por lo que entiendo, tu en el router de `a` estás generando la vista y estás llamando a una variable que está definida en el router de `b`?

Si es eso, no lo puedes hacer. Cuando llamas a la función `render` tienes que pasarle todos los parámetros necesarios para poder generar la vista. Recuerda que al llegar un *request* ejecuta solo la función que hayas definido en tu router dependiendo de la ruta, por lo que no puedes llamar a una variable definida en otro router que no corresponde a la ruta especificada.

Ahora, por lo que veo (y me imagino) esos dos modelos están relacionados. Puedes, al consultar por `a`, incluir los datos de `b` relacionados utilizando la opción `include` al realizar la consulta.

Puedes consultar eso acá:

https://sequelize.org/master/manual/eager-loading.html

Saludos!

**Comment by Kitaps** [comment]
Ohh muchas gracias, 
eso se ve como lo que quería hacer y se ve harto más facil que la solución que estaba maquinando. 

Voy a probar como me funciona.

**Comment by Kitaps** [comment]
Hola, al hacer el include de distitnas maneras me dice que no está definido. 

`ReferenceError: user is not defined`
`at /mnt/c/Users/Asus/U/Web/grupo-localhost/src/routes/buyers.js:12:61`

Siguiendo la lógica del ejemplo 
Hago: 
`const asList = await ctx.orm.a.findAll({ include: b });`

Y se cae ahí. 
Revisé el modelo de `a` y ya está que: 
`models.a.belongsTo(models.b);`
y en `b`
`models.b.hasOne(models.a);`

**Comment by gpvidal** [comment]
Probaste como texto?

```js
User.findAll({ include: 'Instruments' }); // Also works
```

**Comment by Kitaps** [comment]
Ohhh eso era!! Muchas gracias

Como supiste que tenía que ser eso?

**Comment by gpvidal** [comment]
Estaba más abajo en la documentación como otra forma de pasar datos :stuck_out_tongue:

**Comment by Kitaps** [comment]
No lo encuentro. En que parte de la documentación?

**Comment by gpvidal** [comment]
En la misma página que te envié bajo este título: "Fetching an Aliased association"

Puedes buscar la línea que te envié en esa página.

Saludos,

**Comment by Kitaps** [comment]
Ahh perfecto, estaba buscando en la documentación del template. 

Otra dudita. Pero ahí sale que eso es para Aliased associations, pero yo no hice un alias para user. 

Que por que podría ser esto?

O me estoy enredando por nada y debería omitir esta info?

**Comment by gpvidal** [comment]
Pero si está bien preguntar :wink: 

No hiciste un alias para user, pero si no lo hiciste entonces su nombre en string debería ser un alias o no? :stuck_out_tongue: 

Saludos,

**Comment by Kitaps** [comment]
Ok, pero entonces me confunde la otra parte de la documentación. 

Cuando se puede hacer sin string?

**Comment by gpvidal** [comment]
Siempre igual, pero creo que deberías obtener los modelos de `ctx.orm.model` para el include.

**Comment by Kitaps** [comment]
`ctx.orm.model.a.findAll({ include: b})` así?
porque antes lo tenía con 
`ctx.orm.a.findAll({ include: b })` y no funcionó, pero ahora con 
`ctx.orm.a.findAll({ include: 'b' })`  si funciona y me parece raro

**Comment by gpvidal** [comment]
`ctx.orm.a.findAll({ include: ctx.orm.b });`

**Comment by Kitaps** [comment]
ahhhh perfect perfect porque `user` por si solo no esá en ningun lado, pero si la key 'user' del orm.
Gracias, ahi si me quedó claro. 

Disculpa el thread largo :9
