### ISSUE TITLE
cargar variable ejs en un script

### ISSUE THREAD

**Issue by topkaj** [IIC2513-2020-1/syllabus#119]
Sobre la issue #75 ,

En mi caso necesito solamente cargar una variable de ejs en un script,
¿hay alguna alternativa a usar
`<div id="myId" data-myVar="<%= ejsVar%>" /> `
y posteriormente en el script capturar el atributo `data-myVar`?, pues no me gustaría que `ejsVar` estuviese visible para el usuario en el html.

**Comment by gpvidal** [comment]
Hola @topkaj 

Qué es lo que quieres hacer en particular? Por qué quisieras cargar una variable ejs?

Saludos,

PD: Gracias por abrir otra issue! :slightly_smiling_face:

**Comment by topkaj** [comment]
Hola, necesito pasar la id del `<%= currentUser %>` (u otro identificador) para así entregarla a un socket cuya lógica está en un script. He estado usando ya sockets para otros casos donde la variable necesaria estaba en la url, por lo cual no significaba problema, pero en este caso necesito cargar la variable ejs al script. El problema con la solución que propuse, es que el atributo queda a la vista del usuario, no sé si eso implique que pueda resultar inseguro.

**Comment by gpvidal** [comment]
> El problema con la solución que propuse, es que el atributo queda a la vista del usuario, no sé si eso implique que pueda resultar inseguro.

Sí, de todas maneras es inseguro.

Pero tu socket no es autenticado? Es decir, me imagino que tienes la cookie desde el inicio de sesión de usuario. Podrías utilizar eso o no?

Saludos

**Comment by topkaj** [comment]
Estoy intentando implementar notificaciones push, por lo que necesito que el `.emit` se envíe a un usuario particular. Estoy usando `socket.io`, por lo que cada socket tiene su propio `socket.id`, y de alguna forma necesito asociar al currentUser (que en efecto tiene su propia cookie), con el socket.id (o una room única) . El problema sigue siendo, como entrego la cookie o cualquier otro identificador del usuario a la función `socket.emit` que está en un script.

**Comment by gpvidal** [comment]
Lo que yo te estoy mencionando, es que no deberías poder hacer un request y operaciones en tu backend sin autenticarte. Pasar un id de usuario no es autenticar el request, a eso me refiero.

Tienes que revisar cómo hacer que `socket.io` sepa cual es tu current user, si no hay usuario debería rechazar la operación. Luego de esto, relacionar la room, spark, socket id, o lo que estes ocupando con ese usuario.

Saludos!

**Comment by topkaj** [comment]
> Tienes que revisar cómo hacer que `socket.io` sepa cual es tu current user, si no hay usuario debería rechazar la operación. 
>
No he podido hacer esto :(
Sólo encontré que para poder autenticar el socket, necesito enviarle alguna credencial, y como no puedo enviar variables del ejs, pensé en la cookie de sesión que generé yo, pero capturarla u<en el socket usando `socket.request.headers.cookie` no sirve debido a que el template hashea las cookies, por lo que queda diferente a la que almaceno en mi db. ¿Alguna orientación al respecto?

**Comment by topkaj** [comment]
> Tienes que revisar cómo hacer que `socket.io` sepa cual es tu current user, si no hay usuario debería rechazar la operación. 
>
No he podido hacer esto :(
Sólo encontré que para poder autenticar el socket, necesito enviarle alguna credencial, y como no puedo enviar variables del ejs, pensé en la cookie de sesión que generé yo, pero capturarla en el socket usando `socket.request.headers.cookie` no sirve debido a que el template hashea las cookies, por lo que queda diferente a la que almaceno en mi db. ¿Alguna orientación al respecto?

**Comment by gpvidal** [comment]
Esto puede ser util, no lo he probado así que esa parte te toca a ti:

https://medium.com/@albertogasparin/sharing-koa-session-with-socket-io-8d36ac877bc2

Saludos,

**Comment by topkaj** [comment]
¡Muchas gracias! Era lo que necesitaba, funciona perfecto. Es curioso que me topé con ese link mucho antes de esta duda, queriendo implementar el socket por primera vez. Terminé dando vueltas en círculos :satisfied:

**Comment by gpvidal** [comment]
Jajaja qué bueno! :wink:
