### ISSUE TITLE
Contenedores

### ISSUE THREAD

**Issue by Kitaps** [IIC2513-2020-1/syllabus#12]
Hola, 

en el curso de Software nos enseñaron la importancia de usar contenedores como Docker cuando se hacen proyectos de software. Pero usar contenedores, por lo menos en software, trae consigo a veces problemas. 

Para el proyecto del curso recomiendan que usemos contenedores o un virtual environment? O que recomendaciones similares hacen?

**Comment by gpvidal** [comment]
Hola @Kitaps ,

Desde la entrega 2 deben subir su código a heroku, por lo que van a utilizar contenedores :stuck_out_tongue: 

Ahora, en tu desarrollo local, la verdad es que he visto de todo: estudiantes que instalan los paquetes en su computador (que es la opción que yo también utilizo), algunos que lo hacen con docker y otros que instalan una máquina virtual. No hay una respuesta correcta, sino que se trata de qué es mas cómodo para cada uno (creo yo).

Saludos,
