### ISSUE TITLE
SendGrid no funciona en Heroku

### ISSUE THREAD

**Issue by rjcavada** [IIC2513-2020-1/syllabus#120]
Estuve trabajando con el proceso de envío de mails de manera local, usando nodemailer y sendgrid y este funcionaba de manera correcta, pero al momento de subirlo a Heroku este no funciona, a que se puede deber?

**Comment by gpvidal** [comment]
Hola @rjcavada ,

Configuraste las variables de entorno para Sendgrid en heroku?

Saludos,

**Comment by rjcavada** [comment]
Creo que no, eso se debe hacer desde Heroku mismo?

Saludos,

**Comment by gpvidal** [comment]
Sí, igual como se hizo con la base de datos.

Saludos,
