### ISSUE TITLE
Where en relaciones

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2513-2020-1/syllabus#121]
Hola! Estaba buscando en la documentación sobre cómo hacer where en relaciones.
Nuestro esquema ER está modelado como ```constituyente``` IsA ```votante``` IsA ```user```. El problema es que necesitamos buscar en sequelize todos los constituyentes de los cuales el usuario tiene un nombre de usuario definido.

Una solución que encontré es esta:
```js
const constituyentes = await ctx.orm.constituyente.findAll({
  include: [{ 
    model: ctx.orm.votante,
    include: [{ 
      model: ctx.orm.user,
    }],
  }],
  where: {
    '$votante->user.username$': {
      [Op.like]: "%" + term + "%",
    },
  },
});
```
Tristemente, esto es hacer trampa aprovechandose del nombre que sequelize le pone en la query a la entidad relacionada, por lo que aunque funciona, no es conveniente. Por otro lado, intenté esto:
```js
const constituyentes = await ctx.orm.constituyente.findAll({
  include: [{ 
    model: ctx.orm.votante,
    include: [{ 
      model: ctx.orm.user,
      where: {
        username: {
          [Op.like]: "%" + term + "%",
        },
      },
    }],
  }],
});
```
Pero ahí se limita a dejar nulo a ```constituyente.votante```.

De momento funciona bien como lo primero, pero hay alguna forma de hacerlo formalmente?

**Comment by gpvidal** [comment]
Hola @JJJGGGG ,

Me imagino que viste esto o no?

https://sequelize.org/master/manual/eager-loading.html#complex-where-clauses-at-the-top-level

Saludos,

**Comment by JJJGGGG** [comment]
No había encontrado eso en el mar de documentación que hay. Muchas gracias!
