### ISSUE TITLE
Desconfiguración de hora con Digital Ocean

### ISSUE THREAD

**Issue by domingo-valdes** [IIC2513-2020-1/syllabus#123]
Hola! Después de seguir el tutorial, logré subir archivos a Digital Ocean, pero cada cierto tiempo se desconfigura la sincronización entre la hora del servidor y mi PC, con lo que me aparece el error "Request Time too skewed: null" en la consola. ¿Hay alguna manera de arreglar este problema permanentemente? Gracias de antemano!

**Comment by domingo-valdes** [comment]
Ayer me funcionó haciendo ` sudo service ntp restart`, pero hoy ya no consigo que funcione de ninguna manera :(

**Comment by domingo-valdes** [comment]
Ya he intentado usar las soluciones ""clásicas" como [https://stackoverflow.com/questions/4770635/s3-error-the-difference-between-the-request-time-and-the-current-time-is-too-la](url) ¿Puede tener que ver con que esté trabajando en una máquina virtual?

**Comment by gpvidal** [comment]
Hola @domingo-valdes ,

Justo te iba a preguntar si estabas trabajando en una VM. Quién pierde la sincronización? Tu VM o tu sistema operativo (el que corre la VM)? Qué sistema operativo tienes en tu computador y en la VM?

Saludos,

**Comment by domingo-valdes** [comment]
Tengo Windows y una VM con Linux Mint. Por lo que entiendo, la pierde la VM.

**Comment by gpvidal** [comment]
Con virtualbox?

**Comment by domingo-valdes** [comment]
Sí!

**Comment by gpvidal** [comment]
Tienes instalado el "Guest Additions" en tu Linux?

**Comment by domingo-valdes** [comment]
Sí. Al hacer `lsmod | grep -i vbox` en la consola me arroja el output correspondiente

**Comment by gpvidal** [comment]
Lo que he podido leer es que dicen que hay que desactivar el servicio de NTP de tu Guest (Linux) y que solo sincronice con el Host (Windows). Probaste con eso?

Lo otro es que cambies los servidores NTP de Linux, pero yo probaría con lo primero. O ya lo probaste?

Saludos,

**Comment by domingo-valdes** [comment]
Ahí funcionó! Finalmente lo dejé sincronizado con el host (sin ntp) y actualicé la hora de Windows de todas formas. Muchas gracias profesor!
