### ISSUE TITLE
Variables de entorno para SendGrid

### ISSUE THREAD

**Issue by vtespinosa** [IIC2513-2020-1/syllabus#124]
Hola, no me queda claro del video de emails para el proyecto que son las dos variables de entorno que tenemos que definir. Según el profesor tenemos que "crear un usuario dentro de SendGrid que esté autorizado a enviar correos", pero cuando intento crear un subuser en SendGrid me sale que esa funcionalidad es pagada. Con esto me surgen las siguientes dudas:

1. ¿Realmente tengo que pagar para hacer lo que hace el profesor en el video o tengo que crear otra cosa que no sea un subuser, como por ejemplo, una API KEY?
2. En el caso de que haya que crear subusers, ¿Que otros servicios recomiendan para poder reemplazar a SendGrid?

P.D: Intenté definir mis variables de entorno como SENDGRID_USER = api_key_name, SENDGRID_PASS = api_key pero no funcionó.

**Comment by gpvidal** [comment]
Hola @vtespinosa ,

Yo no expliqué qué es lo que deben colocar, ustedes deben buscar qué es lo que deben poner ahí. Sino yo les haría casi toda la entrega o no? :stuck_out_tongue: 

Aquí hablamos sobre algunas cosas de Sendgrid:
https://github.com/IIC2513-2020-1/syllabus/issues/84

Saludos,
