### ISSUE TITLE
Modificar ACL en pkgcloud

### ISSUE THREAD

**Issue by domingo-valdes** [IIC2513-2020-1/syllabus#126]
Hola! Estoy tratando de modificar el parámetro ACL en la configuración de file storage que hicimos en clases. Se que esto se puede porque está en el repositorio de pkgcloud https://github.com/peter-moffatt-hpe/pkgcloud/commit/72d2e88fdd8403209515510a34c9b7cbafc8bce7 pero no sé bien cómo integrarlo a nuestro código

**Comment by domingo-valdes** [comment]
En el fondo, no sé cómo modificar upload(options)

**Comment by gpvidal** [comment]
Hola @domingo-valdes ,

Pero si ahí está clarito lo que hay que hacer :stuck_out_tongue: Cuál es la parte que no entiendes?

También te conviene revisar si el proveedor que estás ocupando tiene configuración de ACL por su lado.

Saludos,

**Comment by gpvidal** [comment]
Ojo que el enlace que enviaste está en un fork del proyecto. Aquí está en el proyecto `pkgcloud`

https://github.com/pkgcloud/pkgcloud/blob/master/lib/pkgcloud/amazon/storage/client/files.js#L73

Saludos,

**Comment by domingo-valdes** [comment]
Revisé y el proveedor tiene configuración ACL. Hasta ahora había tratado de poner la configuración en `storage.js` como `  options: { ACL: mi configuración }` o como `  ACL: mi configuración `. Ninguna funcionó. En `file-storage.js` también intenté agregando parámetros en la línea que dice `const writeStream = this.client.upload({ container: CONTAINER_NAME, remote });` Tampoco tuve buenos resultados. En definitiva, no entiendo bien cómo ni donde debería modificar el parámetro en un código como el que hizo en clases para my-university.

**Comment by gpvidal** [comment]
Creo que debes fijarte en la firma del método, eso te puede dar luces.

Saludos,

**Comment by domingo-valdes** [comment]
Por la firma lo único que puedo deducir es que es un parámetro que le debo entregar a upload, pero así no me funciona :(
