### ISSUE TITLE
bcrypt_lib.node is not a valid Win32 application

### ISSUE THREAD

**Issue by aljara97** [IIC2513-2020-1/syllabus#127]
Intentando hacer yarn dev en mi terminal, me arroja el error `node_modules\bcrypt\lib\binding\napi-v3\bcrypt_lib.node is not a valid Win32 application.` 
Busqué este error en internet, pero no me quedó claro como solucionarlo y si es que se debe a un error de node o de la configuración de mi computador. 

De antemano, gracias

**Comment by gpvidal** [comment]
Hola @aljara97 ,

Te recomiendo que borres la carpeta `node_modules` y hagas un `yarn install` :+1: 

Saludos,

**Comment by aljara97** [comment]
Gracias, ahora funciona
