### ISSUE TITLE
Cargos en AWS S3

### ISSUE THREAD

**Issue by cacoos** [IIC2513-2020-1/syllabus#128]
Hola!

Tengo mis imágenes en AWS S3 y viendo el Billing me encontré con esto. 
![image](https://user-images.githubusercontent.com/30879716/83580712-bc8f8600-a50a-11ea-9385-0eaf98121d01.png)

Por qué aparece costos por bases de datos relacionales si solo uso S3?

Muchas gracias!

**Comment by gpvidal** [comment]
Hola @cacosandon ,

Eso es el detalle del "Free Tier" de Amazon. Estás seguro que no iniciaste nunca una instacia para bases de datos en RDS? Puedes ir a ese servicio y revisar.

De ser un error te puedes contactar con el Soporte de Amazon.

Saludos,

**Comment by cacoos** [comment]
Si estoy seguro, tendré que avisar a soporte!

Gracias!
