### ISSUE TITLE
Versión PostgresQL

### ISSUE THREAD

**Issue by Kitaps** [IIC2513-2020-1/syllabus#13]
Hola, 

estaba intentando de instalar postgres y me preguntaba si usamos una versión especifica? 
O si recomiendan alguna. 

Gracias de antemano, 
Patrick

**Comment by gpvidal** [comment]
Hola @Kitaps ,

Puedes ocupar todas las versiones que actualmente tienen soporte por parte de PostgreSQL, es decir, desde la 9.5 en adelante (incluida la 12).

Yo en particular tengo instalada la 10.

Saludos,

**Comment by Kitaps** [comment]
Muchas gracias
