### ISSUE TITLE
Heroku no lee archivos subidos a cloudinary

### ISSUE THREAD

**Issue by ibaeza1** [IIC2513-2020-1/syllabus#131]
Hola!
Cuando subo mi app a heroku no me lee los archivos que subo. Hicimos el upload a cloudinary y en el localhost funciona perfecto, pero en heroku no funciona. No me tira ningun error pero no las esta leyendo. 
Por que podria ser?
Gracias! :)

**Comment by gpvidal** [comment]
Hola @ibaeza1 ,

Quizás puede ser por como están procesando el archivo (si lo están moviendo de lugar) o no están esperando una promesa, revisaron eso?

Saludos,

**Comment by ibaeza1** [comment]
Hola!
Si estamos haciendo await antes del upload.

```js
await user.save({ fields: ['name', 'password', 'email', 'photo', 'curriculum', 'description', 'complaints', 'tag_admin','tag_company'] });
await fileStorage.uploadImage(photo.path, user.id, "profile");
user.photo = await fileStorage.getImage(user.id, "profile");
await fileStorage.uploadCv(curriculum.path, user.id);
user.curriculum = await fileStorage.getCv(user.id);
await user.save();
```

Eso estamos haciendo para subir archivos.

**Comment by gpvidal** [comment]
Y no ves el archivo en cloudinary? O si entras en cloudinary ves el archivo pero no está en tu base de datos?

**Comment by ibaeza1** [comment]
Cuando creo un usuario en el localhost se sube bien la imagen a cloudinary, pero en heroku no funciona

**Comment by gpvidal** [comment]
Tienen configuradas las mismas variables de entorno en Heroku y en local? Es decir, revisaron que toda la configuración que necesitan esté en Heroku?

**Comment by ibaeza1** [comment]
Osea las variables de entorno las tengo en mi .env.
Hay que ponerlas directamente en heroku? Si es asi como lo hago?

**Comment by gpvidal** [comment]
https://devcenter.heroku.com/articles/config-vars

**Comment by ibaeza1** [comment]
Era eso! Graciaas
