### ISSUE TITLE
Markdown y archivos .md

### ISSUE THREAD

**Issue by Kitaps** [IIC2513-2020-1/syllabus#132]
Hola, 

escribo para preguntar que reccomiendan para ver archivos Markdown?

Yo antes usaba mi editor de texto, pero el de ahora viene sin. Entonces quería preguntar, antes de instalar una extensión, como lo hacen uds para ver este tipo de documentos?

He visto que extensiones para chorme como para varios editores de texto. 

De antemano gracias

**Comment by gpvidal** [comment]
Hola @Kitaps ,

Yo los veo con VSCode. Creo que GitHub también te los muestra.

Saludos,

**Comment by Kitaps** [comment]
Gracias. 

Si Github tambien muestra, pero estaba buscando que es lo recomendable. Voy a descargar un plugin para mi VSCode entonces.
