### ISSUE TITLE
Cambiar ctx.session.id

### ISSUE THREAD

**Issue by cacoos** [IIC2513-2020-1/syllabus#133]
Hola!

Mi pregunta va más relacionado por si se puede cambiar el `ctx.session.id` o el diccionario `ctx.session` mediante consola web o algo. Cómo funciona el `ctx.session` es lo que me deja en duda. ¿Puedo hacerme pasar por otra persona cambiando este id? Si no, ¿por qué? Estoy super confundido.

Por esta misma línea, queremos hacer moderadores que tienen funcionalidades especializadas. ¿Es mala práctica dejar ids predefinidos que determinen los usuarios que pueden hacer estas cosas? O es mejor ponerles un atributo type? Qué es más seguro?

Muchas gracias!

**Comment by cacoos** [comment]
Profe, acabo de leer una issue que publicaron hace un tiempo y me quedó clarísimo, gracias!

**Comment by gpvidal** [comment]
Hola @cacosandon ,

> Mi pregunta va más relacionado por si se puede cambiar el `ctx.session.id` o el diccionario `ctx.session` mediante consola web o algo. Cómo funciona el `ctx.session` es lo que me deja en duda. ¿Puedo hacerme pasar por otra persona cambiando este id? Si no, ¿por qué? Estoy super confundido.

`ctx.session` se define mediante la cookie. Te recomiendo mirar esa clase, quizás también el paquete `koa-session` que es el que disponibiliza el `ctx.session`.

> Por esta misma línea, queremos hacer moderadores que tienen funcionalidades especializadas. ¿Es mala práctica dejar ids predefinidos que determinen los usuarios que pueden hacer estas cosas? O es mejor ponerles un atributo type? Qué es más seguro?

Hay que preguntarse si es un rol o no, si es así entonces quizás un atributo o referencia a  los roles de tu aplicacion :wink: 

Saludos!

**Comment by gpvidal** [comment]
> Profe, acabo de leer una issue que publicaron hace un tiempo y me quedó clarísimo, gracias!

Buena! :tada:
