### ISSUE TITLE
Cambiar app.keys

### ISSUE THREAD

**Issue by cacoos** [IIC2513-2020-1/syllabus#134]
Hola!

Me quedó claro lo de firmar cookies. Pero si alguien conoce el actual valor del `app.keys` del template, igual sabría como hacer la conversión, no?

Si yo quiero llevar la app a producción debería cambiar `app.keys` a cualquier string que yo quiera?

Gracias!

**Comment by gpvidal** [comment]
Hola @cacosandon ,

Claro, tienes que cambiarlas ;)

Saludos,

**Comment by cacoos** [comment]
Perfect, gracias!
