### ISSUE TITLE
Obtener resultado de upload

### ISSUE THREAD

**Issue by ibaeza1** [IIC2513-2020-1/syllabus#137]
Hola!
Para subir archivos estamos usando cloudinary. 
Estamos usando este metodo para subirlos:

```js
  uploadImage(imageData, userId, tipo) {
    cloudinary.uploader.upload(
      imageData,
      { public_id: userId + "_" + tipo,invalidate: true },
      function f(error, result) {return result["url"]; } ) };
```

Lo que quiero es poder sacar la informacion de result, ya que ahi esta el url de la imagen y necesito ese url para poder mostrarla en el html.
Como puedo obtener result?

**Comment by gpvidal** [comment]
Hola @ibaeza1 ,

Por lo que pude ver a simple vista, la API de Cloudinary está basada en *callbacks* y no en promesas. Si están ocupando ese método, no están esperando que la imagen se suba antes de responder el *request*.

Lo que te recomiendo es que retornes una promesa que "envuelva" a ese método. Hice algo muy similar en la clase de API.

Saludos,
