### ISSUE TITLE
Duda permisos

### ISSUE THREAD

**Issue by Cadagan** [IIC2513-2020-1/syllabus#139]
Una duda corta, ¿podemos utilizar:

- Angular
- multer
- multer -s3
- aws-sdk
- express
?  hay algunos que no y otros si?

Estas cosas pensaba utilizarlas para el manejo de subida de imagenes con un bucket en S3 de Amazon Web Services de manera individual en lugar de manual en la página de AWS misma, para que cada usuario pueda subir sus propias imagenes

**Comment by gpvidal** [comment]
Hola @Cadagan ,

Acabas de poner una lista de *packages* para distintos usos, por lo que no entiendo la pregunta. Por qué no usar `pkgcloud` que fue el que vimos? Este sirve para subir a AWS (por ejemplo).

Saludos,
