### ISSUE TITLE
Problemas postgres

### ISSUE THREAD

**Issue by aaguilarg** [IIC2513-2020-1/syllabus#14]
Hola,
Al tratar de usar postgres, ingresando psql en la consola, me indica este error. 

``psql: error: could not connect to server: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?``

He buscado, y la verdad no entiendo mucho las soluciones que salen en internet.
¿Cómo lo soluciono?
Gracias!

**Comment by gpvidal** [comment]
Hola @aaguilarg ,

Instalaste postgres en tu máquina y quieres ingresar con `psql`? Que sistema operativo usas?

Saludos,

**Comment by aaguilarg** [comment]
Utilizo ubuntu 19.10

**Comment by aaguilarg** [comment]
Logré hacerlo, seguí las instrucciones de acá:
https://tecadmin.net/install-postgresql-server-on-ubuntu/

Disculpa las molestias

**Comment by gpvidal** [comment]
Prueba con:

```bash
$ sudo service postgresql start
```
o

```bash
$ sudo systemctl start postgresql
```
Este comando iniciará el servidor postgres y deberías poder conectarte con `psql` después :+1: 

Saludos,

**Comment by gpvidal** [comment]
Súper :tada:

**Comment by nhbravo** [comment]
Hola! Tengo el mismo problema desde Mac, pero no he podido ni siquiera crear la base de datos. Podrían darme algunos pasos a seguir para hacerlo bien?

**Comment by gpvidal** [comment]
Viste esto @nhbravo ?

https://github.com/IIC2513-2020-1/syllabus/wiki/Getting-Started#macos

Saludos,

**Comment by nhbravo** [comment]
Si, tengo todo instalado y en teoria mi servidor de postgres esta funcionando, aun asi me tira error (adjunto foto del terminal). Quizás estoy haciéndolo mal.
<img width="682" alt="Captura de Pantalla 2020-04-02 a la(s) 19 43 55" src="https://user-images.githubusercontent.com/37144022/78306664-52626100-751a-11ea-9402-18170fcc498c.png">

**Comment by gpvidal** [comment]
@nhbravo mi conocimiento de Mac es extremadamente limitado, no creo que pueda ayudarte con esto. Ojalá alguien más pueda :smile:

**Comment by arpincheira** [comment]
Hola, 
se que lo ideal del foro es recomendar documentación o stackoverflow, pero esta guía te podría servir para ver el como crear bases de datos, como crear usuarios, asignar contraseñas y eso en Mac. https://www.codementor.io/@engineerapart/getting-started-with-postgresql-on-mac-osx-are8jcopb

Espero que te sirva.

**Comment by nhbravo** [comment]
Después de mucho rato, encontré un error que decía:
`The data directory was initialized by PostgreSQL version 11, which is not compatible with this version 12.2.`
Lo cual es corregible con el comando:
`brew postgresql-upgrade-database`
