### ISSUE TITLE
ctx.redirect crea un request PATCH

### ISSUE THREAD

**Issue by vtespinosa** [IIC2513-2020-1/syllabus#140]
Hola, tengo un form en react que al hacer un submit, crea un request patch con fetch a una route en espcífico. Esta route recibe perfectamente la información y actualiza sin ningún problema la base de datos, pero al momento de hacer ctx.redirect, por alguna razón éste crea un request patch (el cual retorna un status 404) y no se redirecciona. Como consecuencia, si bien se actualiza la base de datos, desde el punto de vista del cliente no pasa nada. He buscado mucho en internet y no he encontrado nada parecido. Adjunto una foto del error.

![Screenshot from 2020-06-16 18-14-33](https://user-images.githubusercontent.com/42243507/84833430-49533d00-affd-11ea-8cdf-6f0d1ccdf273.png)

**Comment by gpvidal** [comment]
Hola @vtespinosa ,

No tendrás dos rutas con el mismo nombre?

Saludos,

**Comment by vtespinosa** [comment]
Hola, @gpvidal,

Me fijé y no tengo dos rutas con el mismo nombre. Lo raro del problema es que hago el mismo redirect para el update y el create de las companies y si funciona, pero por alguna razón cuando accedo a la route mediante un fetch desde react, no funciona.

Saludos

**Comment by gpvidal** [comment]
Creo que esto puede ser de utilidad:

https://stackoverflow.com/questions/39735496/redirect-after-a-fetch-post-call

Saludos,

**Comment by vtespinosa** [comment]
Lo acabo de probar y no solucionó el problema, pero si hubieron cambios. Cambié de patch a post y agregué `redirect: 'follow'` a las opciones de fetch y ahora el ctx.redirect funciona como se espera y hace un request de get en vez de patch. Además, en la terminal se imprimen las queries a la base de datos que son necesarias para renderiar la vista a la que estoy redireccionando y el request de get retorna status 200, pero en el navegador no pasa nada.
La verdad es que no se me ocurre si el error viene de react, node o de algún otro lado. Voy a seguir investigando.
Saludos y gracias por la ayuda.

**Comment by gpvidal** [comment]
Wait, que esperas que pase?

**Comment by vtespinosa** [comment]
Quiero que cuando se haga submit del form se redireccione al perfil (show) de la empresa que está haciendo el cambio.

**Comment by gpvidal** [comment]
Ahhh pero ese es un comportamiento que tú tienes que programar en el componente React.

Sí la respuesta es 3XX entonces redireccionar. En una clase o issue (no recuerdo bien) mencioné sobre window.location

Saludos,

**Comment by vtespinosa** [comment]
Ahhhh entiendo, voy a buscar la issue o clase entonces.
Muchas Gracias!

**Comment by gpvidal** [comment]
Ahora, la gracia de un componente React es no redirigir, porque sería lo mismo que tener la página "normal". Podrías mostrar un mensaje que se actualizo correctamente los datos y ocultar el formulario (o no).

Saludos,

**Comment by vtespinosa** [comment]
Si me dijo eso mi ayudante, pero esta vista de react es como un segundo paso del sign up, que también se puede editar en el perfil, por lo que creo que lo mejor es redirigir al perfil. Quizas no era lo mejor hacerlo con react, pero necesitaba que se cambiara la vista a medida que el cliente cambiara los inputs.

**Comment by vtespinosa** [comment]
@gpvidal  con window.location funcionó al tiro.
Muchas Gracias.
