### ISSUE TITLE
Uso de librería 'react-chat-window'

### ISSUE THREAD

**Issue by matiaseche** [IIC2513-2020-1/syllabus#141]
Hola, quería saber si puedo usar esta librería para el chat de nuestro proyecto! Nuestro chat ya está implementado, pero esta ayudaría a que se vea mejor.

**Comment by gpvidal** [comment]
Hola @matiaseche ,

No, no pueden ocupar este paquete.

Saludos,

**Comment by matiaseche** [comment]
Ok!
