### ISSUE TITLE
Lag CSS

### ISSUE THREAD

**Issue by fdduarte** [IIC2513-2020-1/syllabus#142]
Hola,

Desde que partio el proyecto, tengo un pequeño delay en la carga del css, por lo que al cargar una vista se ve feo por una fracción de segundo y después renderea bien.

No sé si a alguien mas le pasa o si alguien lo soluciono, pero es un poco molesto.

Me fije que en el layout lo primero que se importa es el css entonces no sé a que se debe.

Gracias

**Comment by gpvidal** [comment]
Hola @fdduarte ,

Es el comportamiento esperado, dado como se cargan los estilos en el entorno de desarrollo. Es una muy buena pregunta para responder en mi clase de mañana :wink: 

Saludos,
