### ISSUE TITLE
API 204 not response

### ISSUE THREAD

**Issue by cacoos** [IIC2513-2020-1/syllabus#143]
Hola!

Estamos desarrollando la API, y cuando la llamo (consulta get) se ejecuta la consulta, se setea el ctx.body y retorna 204. Sin embargo, no se muestra nada en la página y en el Talend API Tester se muestra "204 No Content". No tengo idea qué puede ser.

En la foto se ve que seteo ctx.body con cualquier cosa y aún así se muestra el error.
![image](https://user-images.githubusercontent.com/30879716/85044867-3905a400-b15c-11ea-8255-6a88d7efa55f.png)

![image](https://user-images.githubusercontent.com/30879716/85044930-4de23780-b15c-11ea-9d0e-1f08050af641.png)

Muchas gracias! Estoy atento.

**Comment by gpvidal** [comment]
Hola @cacosandon ,

Intentaste pasarle un objeto o array? Ahora le estás pasando un texto que no debe entender como el contenido que quieres enviar para una API.

```js
ctx.body = { foo: 'bar' };
```

Saludos,

**Comment by cacoos** [comment]
Profe, ahora funcionó.

Lo que hicimos fue cambiar el nombre de las rutas. Antes estaba:
```
router.get("/myfiles", ...) {
 --
}
router.get("/:id", ...){
 --
}
```

y entraba a la segunda ruta tomando id = myfiles, no sé por qué si debería ir en orden de middlewares.. por qué será?

Gracias!

**Comment by gpvidal** [comment]
Claro, puede ser temas de orden.
