### ISSUE TITLE
Page-specific javascript

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2513-2020-1/syllabus#144]
Hola! Estoy super perdido sobre este tema.

He escuchado que es mejor práctica poner los scripts al final del body. Principalmente porque así se cargan todos los elementos del DOM y luego no hay problemas con jquery o con react. Hay alguna forma de llevar los scripts al final del body? Algo así como los que hace
```ejs
<%- body %>
```
en el layout, pero más abajo y con contenido dinámico (y ojalá no tener que estar escapando todas las comillas ```\"```)

Si esto no es necesario, entonces es buena práctica poner los scripts en una vista, siendo que se carga a la mitad body?

Para referencia, agregamos estilos al layout y por lo mismo no basta con poner los scripts al final de la vista.
```html
    <div class="page-main">
        <div class="page-container">
          <%- body %>
		      <div id="root"></div>
        </div>
    </div>
```

Por otro lado, intenté crear un archivo .js en ```/assets/js``` y llamarlo desde el html, pero no lo encuentra. Sólo lo encuentra si lo agrego a ```index.js```, pero no me agrada la idea de que todas mis vistas compartan todos los scripts (y de hecho ya comparten todos los css).

Alguna idea sobre estas dudas?

**Comment by gpvidal** [comment]
Hola @JJJGGGG ,

Aquí está la respuesta: https://github.com/IIC2513-2020-1/syllabus/issues/108

Saludos,
