### ISSUE TITLE
Error en upload de imagen a space DigitalOcean con pkgcloud: falta 'Key' en params

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2513-2020-1/syllabus#145]
Hola, estoy intentando subir una imagen a un space que cree en DigitalOcean. Llevo todo el día intentado, pero este último error es uno que ya no tengo idea de cómo solucionar. Hice yarn add pkgcloud y yarn add fs, configuré las variables de entorno con una key que generé en API / Space acess keys. Fuera de eso solo cambie el remote path a uno customizado, y en vez de usar la const list paso directamente como parámetro  ctx.request.files.image1, que es el elemento File{} que recibo del form de update de una entidad al que agregué un enctype="multipart/form-data". Esto ya que al definir las const imprimían valor undefined, y al pasarle ctx.request.files tenía un error de que no tenía .path . 

En base a otra issue probé borrar node_modules y hacer yarn start de nuevo, pero el error sigue siendo el mismo. Aclaro que File Storage si guarda las credenciales, y mi space sí lo creé en San Francisco 2.

![image](https://user-images.githubusercontent.com/26129405/85072608-5e5bd780-b187-11ea-948a-ba6adfa928dc.png)

Este es el error:
![image](https://user-images.githubusercontent.com/26129405/85072950-e80ba500-b187-11ea-9f61-c0f2ff51e4ab.png)

Y un poco más que esto es ctx.request.files.image1:
![image](https://user-images.githubusercontent.com/26129405/85072773-9ebb5580-b187-11ea-99da-9cb7d9d5b8a6.png)

Acá se levanta el error en el archivo de node_modules
![image](https://user-images.githubusercontent.com/26129405/85074180-2013e780-b18a-11ea-98d7-888822e1194b.png)

Desde ya muchas gracias!!!

**Comment by gpvidal** [comment]
Hola @B-Dominguez ,

Por qué `yarn add fs`? `fs` "viene" en node.

Saludos,

**Comment by gpvidal** [comment]
Y probablemente te falte enviar, en alguna parte, el nombre del archivo que estás subiendo. Ojo ahí con la documentación de `pkgcloud`.

Saludos,

**Comment by B-Dominguez** [comment]
Gracias por la respuesta profe. Con lo del yarn add fs me confundí al escribir la isssue lo siento. Efectivamente el problema era la diferencia entre el parámetro 'name' del objeto File y el nombre que yo brindaba en lo que en la documentación se ve como:

>   remote: 'remote-file-name.txt'

El tema era que, precisamente como decía 'remote-file-name.txt', pensé que se podía editar solo ahí el nombre del archivo en el destino, además de que no había asociado 'Key' al nombre de archivo, y en issues de internet la asociaban con la key de aws. Ahora lo pude solucionar y puedo seguir, así que muchísimas gracias!!!
