### ISSUE TITLE
Settear Archivos Publicos en DigitalOcean

### ISSUE THREAD

**Issue by BenjaPrograma** [IIC2513-2020-1/syllabus#147]
Hola! Estoy teniendo problemas para poder settear por default los archivos que suba a digitalOcean como publicos, por ej: quiero subir una imagen y despues almacenar el url permanente en mi bdd, pero la imagen es subida de forma privada por lo que me tira acceso denegado.
Puedo hacerlo manualmente de pasarlo a publico, pero claramente no es la idea.
Supongo que hay algun comando que se puede pasar al upload para que sea publico el archivo al subirse, pero no lo he podido encontrar, por si alguien me puede ayudar.

Saludos!

**Comment by nrrosenberg** [comment]
hola, estoy teniendo el mismo problema, cómo pudiste arreglarlo??
