### ISSUE TITLE
Setear archivos como públicos por default en digitalOcean

### ISSUE THREAD

**Issue by nrrosenberg** [IIC2513-2020-1/syllabus#148]
Hola, estoy teniendo problemas para setear como públicos los archivos que subo a digitalocean. Para que se puedan ver (en este caso fotos), debo ajustar manualmente el permiso en la pagina de digitalocean, hay alguna forma de dejarlo como público por default?

**Comment by gpvidal** [comment]
Hola @nrrosenberg ,

Aquí se hizo una pregunta similar https://github.com/IIC2513-2020-1/syllabus/issues/126

Saludos,
