### ISSUE TITLE
Error al importar modulos en archivos .JS en carpeta ASSETS

### ISSUE THREAD

**Issue by BenjaPrograma** [IIC2513-2020-1/syllabus#149]
Hola! Estoy intentando consumir una API que requiere AUTH, por lo que necesito almacenar client keys, y para eso utilizar .env para las variables de entorno, por esto necesito importar la libreria dotenv en un archivo JS, que ubico en assets/js/services/ pero por algun motivo el programa se cae. Sin embargo, no solo pasa con la libreria dotenv, me pasa tambien al tratar de importar otras librerias.

Me tira el siguiente error:
![Screenshot_364](https://user-images.githubusercontent.com/26238496/85498102-1389f780-b5ad-11ea-8acc-b35e9f961a0a.png)

Mi ayudante de proyecto me dijo:

> Ya, estuve revisando el template y el problema está en como este carga los paquetes, porque el código que esta en assets se despliega en el navegador, el cual no tiene acceso a node modules, les recomiendo que busquen otra Api en la cual no deban usar keys

Pero que de todas formas hiciera una issue al respecto.

Saludos!

**Comment by gpvidal** [comment]
Hola @BenjaPrograma ,

Efectivamente no puedes hacer eso, dado que viven en mundos distintos (cliente y servidor). 

Ahora, revisa cuales son las características de esas keys. Si son públicas (o tienen que serlo) entonces tienen que estar en tu aplicación.

Si tienen que ser privadas, lo que sí podrías hacer es un endpoint que le entregue esas keys a tu aplicación cliente para que las utilice. De esa forma no estan escritas explícitamente.

Saludos,
