### ISSUE TITLE
Configuracion de variables de entorno

### ISSUE THREAD

**Issue by tpcantergiani** [IIC2513-2020-1/syllabus#15]
Hola:
Estoy un poco complicado Para configurando las variables de entorno:
Deberíamos cambiarlas directamente en la terminal, o es preferible crear un archivo y correr un programa de ta forma que una herramienta lo lea y las configure?
En el segundo caso, deberíamos colocar en el gitignore est archivo?
Gracias de antemano.

**Comment by gpvidal** [comment]
Hola @tpcantergiani !

En la clase de hoy (puedes ver el video V09) expliqué un poco más sobre el tema de las variables de entorno. También puedes consultar acá:

https://github.com/IIC2513-2020-1/syllabus/wiki/Tips

Es preferible lo segundo que mencionas, para no estar haciéndolo cada vez que quieras trabajar en el proyecto! Y sí, debería estar ese archivo en el `.gitignore` :wink: 

Saludos!
