### ISSUE TITLE
Importar imágenes s3

### ISSUE THREAD

**Issue by aljara97** [IIC2513-2020-1/syllabus#150]
Hola, estoy utilizando el método `getSignedUrl` de `aws-sdk` para obtener la presigned url de una imagen alojada en un bucket de Amazon S3. El problema es que esta función me retorna una ruta, la cual solo permite visualizar una imagen que fue subida de forma manual, y  para aquellas que fueron subidas con el método upload, el link generado descarga la imagen de forma automática, por tanto, no puedo verla en el navegador. Hay alguna forma de corregir este error? o es algún permiso que puede estar fallando?

De antemano, muchas gracias

**Comment by gpvidal** [comment]
Hola @aljara97 ,

Puedes revisar si las fotos que subiste de forma manual tienen, en la interfaz de Amazon S3, dentro de metadata un campo de Content-Type? Probablemente al subirlo de forma manual se agrega de forma automática.

Saludos,

**Comment by aljara97** [comment]
Si, los archivos que subí de forma manual tienen como atributo en content type `image/jpeg` y los que subí por la aplicación son de tipo `application/octet-stream`. Agregué este parámetro al hacer upload y ahora funciona.

Muchas gracias
