### ISSUE TITLE
Error de CORS haciendo FETCH desde un componente REACT hacia una ruta definida en KOA

### ISSUE THREAD

**Issue by BenjaPrograma** [IIC2513-2020-1/syllabus#152]
Hola! Estamos trabajando en hacer forms en REACT, para lo que necesitamos enviar con fetch los datos desde REACT hacia KOA, pero me tira un error de cors

> Solicitud de origen cruzado bloqueada: La misma política de origen no permite la lectura de recursos remotos en https://localhost:3000/comentarios/. (Razón: Solicitud CORS no exitosa)

Busque en internet e instale @koa/cors, para solucionar el problema, 
https://github.com/koajs/cors
y seguí los pasos, agregando la linea app.use(cors()) en el app.js, para habilitar CORS, pero aun asi me sigue arrojando el mismo error.
Lo probe desde POSTMAN y me funciona perfecto, haciendolo desde el navegador no me funciona.

**Comment by gpvidal** [comment]
Hola @BenjaPrograma ,

Ojo, no tenemos configurado `https` en el proyecto. Revisa la URL a la que estás haciendo fetch :wink: 

Saludos,

**Comment by BenjaPrograma** [comment]
Hola @gpvidal,

Hago fetch a `localhost:3000/XXXX/` y no me deja entrar, pero por postman lo hace sin problemas, junto con lo del mensaje de CORS, me hace pensar que era un problema por CORS, todavia no me deja entrar.

Saludos y gracias por tu respuesta.

EDIT: Por otro lado me surge la duda, `https` sigue sin configurar aun cuando se hace el deploy a heroku?

**Comment by gpvidal** [comment]
No omitas el `http`, deberías hacer fetch a `http://localhost:3000/XXXX/`. En algunos casos por defecto lo hace por `https`.

Y yep, en Heroku no está habilitado el https.

Saludos,

**Comment by tpcantergiani** [comment]
Yo tuve el mismo problema y agregue `mode: 'no-cors',` en el fetch, después de headers.
No se si es una buena solución.

**Comment by tpcantergiani** [comment]
Hola!
@BenjaPrograma  De casualidad la librería @koa/cors no hace que la app se te caiga en Heroku?
Que tengo el mismo problema, y tampoco lo he podido solucionar, intento instalando la libreria, pero me bota la app en heroku.

**Comment by domingo-valdes** [comment]
@BenjaPrograma pudiste solucionar el problema? Estoy en las mismas desde hace rato

**Comment by gpvidal** [comment]
@domingo-valdes , puedes explicar qué es lo que quieres hacer y de donde a donde estás haciendo los requests?

Saludos,

**Comment by domingo-valdes** [comment]
Hola Profesor! Hice una segunda app completamente distinta e independiente de la hecha a comienzo del curso, que estoy corriendo en localhost, y estoy haciendo un fetch a mi app original en Heroku. Estoy haciendo la auteticación para recibir el jwt como vimos en clases

**Comment by gpvidal** [comment]
Instalaste `@koa/cors`?

**Comment by domingo-valdes** [comment]
Sí, y al igual que Benjamín más arriba estoy usando app.use(cors()) en el app.js

**Comment by gpvidal** [comment]
Y qué error te tira?

**Comment by domingo-valdes** [comment]
![imagen](https://user-images.githubusercontent.com/17691819/86387042-5ca70f00-bc71-11ea-84fc-c623b96fb666.png)
Hasta donde entiendo poner no-cors no es buena idea porque no podría leer el body de la respuesta

**Comment by gpvidal** [comment]
E hiciste push a heroku después de haber instalado `@koa/cors`?

**Comment by domingo-valdes** [comment]
En la app original no. Voy a intentar eso!

**Comment by domingo-valdes** [comment]
Funcionó! Muchísimas gracias profe!
