### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by fabarros** [IIC2513-2020-1/syllabus#153]
Hola! Espero que estén bien.
Estoy testeando nuestra API, y la autenticación funciona bien, me devuelve el token, pero cuando envío el token de vuelta con el request de tipo GET me dice que no estoy autorizado D: 
Estoy mandando este header: Authorization: Bearer 'token'
Request de tipo GET a http://localhost:3000/api/myentidad
Estoy usando Talend API Tester.
Porfis si me pueden dar algun indicio de qué puede ser, se los agradecería mucho. Llevo rato tratando de debuggear y nada.
Saludos!

**Comment by gpvidal** [comment]
Hola @fabarros ,

Dos cosas:

- Me imagino que no estás encerrando tu token entre comillas, si es así hay que sacarlas.
- Tienes seteado el secreto para crear el token?

Saludos,

**Comment by fabarros** [comment]
Hola! Gracias por responder profe.
Noo no está entre comillas en el request GET y si tengo la variable de entorno. Tiene que tener alguna caracteristica especial el secreto?
Saludos.

**Comment by gpvidal** [comment]
Creo, entonces, que debes revisar la parte en la que encuentra a qué usuario le corresponde ese token. Si estás mandando bien el *header*, que como dices así debería ser, y también tienes seteado el secreto para generar los JWT (revisar si efectivamente está la variable en ese punto con un `console.log`, no vaya a ser que tengas ahí problemas con `dotenv`) entonces creo que por ahí puede ir problema: en detectar al usuario al que le corresponde ese token.

Saludos,

**Comment by fabarros** [comment]
Gracias profesor, lo pude solucionar. Tenía problemas con dotenv.

Saludos!
