### ISSUE TITLE
Uso de Apis

### ISSUE THREAD

**Issue by andresplass** [IIC2513-2020-1/syllabus#155]
Hola leyendo el enunciado de la entrega 6, no me quedó claro qué sería consumir o no una API.
La idea es no simplemente poner un botón y que muestre algo pero, si por ejemplo vamos a algo simple como una api que te muestre una foto de perro cada día y no tenga nada más, no sería correcto usarla? 
De ser así, el problema sería la "simplicidad" de la api o la manera en que la estoy usando (porque al hacer request ya la estoy consumiendo) y eso me confunde
Gracias 😄

**Comment by gpvidal** [comment]
Hola @andresplass ,

Te recomiendo que cuando tengas una API le consultes a tu ayudante, para que no hayan sorpresas a la hora de la corrección. Finalmente, él/ella es quien da los requisitos.

La idea es que sea un servicio REST, tal como lo menciona el enunciado.

Saludos,

**Comment by andresplass** [comment]
Ya profe muchas gracias!
