### ISSUE TITLE
Uso de XMLHttpRequest

### ISSUE THREAD

**Issue by ibaeza1** [IIC2513-2020-1/syllabus#159]
Hola!
Queremos usar una api y su libreria dice que hay que usar XMLHttpRequest() para hacer las requests. Se puede usar esta libreria?
Si no se puede, cual es una alternativa?
Gracias!

**Comment by gpvidal** [comment]
Sí, podrían, aunque recomiendo que lo hagan con `fetch` que es lo mismo pero más moderno :wink: 

Saludos,
