### ISSUE TITLE
Error al iniciar la aplicación.

### ISSUE THREAD

**Issue by bgsamilla** [IIC2513-2020-1/syllabus#16]
Hola! 
Al ejecutar yarn start me lanza el siguiente error:

```
Unable to connect to the database: ConnectionError [SequelizeConnectionError]: password authentication failed for user "mi_usuario"
```

Ya intente todo lo que he encontrado en internet y no logro solucionarlo....

Help!

**Comment by gpvidal** [comment]
Hola @BSamilla !

Eso es porque los datos que estás usando para conectarse a la base de datos no son correctos. ¿Qué intentaste?

Saludos,

**Comment by bgsamilla** [comment]
Lo primero que hice asegurarme de que tenia bien puestos los datos. Como no era eso decidí crear desde cero un nuevo usuario en postgres, dar los permisos, y ponerle contraseña (pensé que el problema podría ser que no tenia una). Volver a crear la base de datos, y asegurarme de que estaba escribiendo bien los datos nuevamente.

También pensé que podría ser el .env pero está reconociendo el usuario que cree y no está intentando usar el usuario que tenia por defecto. Pero tampoco lo descarto porque es la primera que intento usar variables de ambiente.

**Comment by gpvidal** [comment]
Muy en resumen, lo que deberías hacer es (Si tienes linux):
```
$ sudo -u postgres psql
postgres=# create database mydb;
postgres=# create user myuser with encrypted password 'mypass';
postgres=# grant all privileges on database mydb to myuser;
```
El primer paso es para entrar al servidor, podría variar si tienes otro sistema operativo. En lo anterior sería ideal que cambies los valores que se expresan para la base de datos, usuario y contraseña.

Al final, los datos te quedarían:

Nombre base de datos: mydb
Nombre usuario: myuser
Contraseña usuario: mypass

Hiciste algo como esto?

Saludos,

**Comment by bgsamilla** [comment]
Sip, lo intente.

**Comment by gpvidal** [comment]
Pero entonces es muy extraño, porque esos fueron exactamente los pasos que yo seguí :confused:
Qué más intentaste para ver cuál puede ser otra fuente de error?

**Comment by bgsamilla** [comment]
Intente meter harcoded los valores a database.js, por si eran las variables de entorno.
También intenté varios comandos que encontré por ahí, pero básicamente eran lo mismo que sugirió mas arriba escritos de otra forma.
Ahora supongo que voy a borrar todo, reiniciar el laptop (que tiene fama de funcionar como le da gana) he intentar todo otra vez, estuve trabajando en una app rails que usa postgres en la mañana y quizás esté interfiriendo (aunque lo dudo muchisimo) , reinstalar los programas podría ser la otra opción.
Cuento como me va mas tarde ....

**Comment by gpvidal** [comment]
Te puedes conectar por `psql`?

PD: GitHub está com problemas ahora! https://www.githubstatus.com/

**Comment by bgsamilla** [comment]
Si, si puedo.

**Comment by gpvidal** [comment]
Intenta el siguiente comando:

```
$ psql -h localhost -U <usuario bd> -d <nombre bd>
```
Te debería pedir la clave de ese usuario para la base de datos. Si te puedes conectar, entonces el problema no está en la base de datos.

Saludos,

**Comment by bgsamilla** [comment]
Sip, conecta bien.

**Comment by gpvidal** [comment]
Y las variables de entorno están bien? Si te conectó con `psql` puede haber sido un typo o algo de ese estilo.

**Comment by gpvidal** [comment]
Y las variables de entorno están bien? Si te conectó con `psql` puede haber sido un typo o algo de ese estilo.

**Comment by bgsamilla** [comment]
Copie la contraseña desde la consola al .env para asegurarme de que coincidiera.

**Comment by gpvidal** [comment]
¿Qué método de carga de variable de entorno estás usando?
