### ISSUE TITLE
CRUD Api manejar errores

### ISSUE THREAD

**Issue by andresplass** [IIC2513-2020-1/syllabus#160]
Hola estoy implementando los metodos Delete y post en mi App en modo Api.
Al momento de usar el metodo DELETE, logro que efectivamente lo elimine (esto con Talend API Tester), pero como se elimina, en el API Tester obtengo el mensaje de error "404 Not found". Quería saber si existe una forma de que al usar el metodo DELETE, solo me elimine pero no me tire algun error.

Esto lo pregunto porque al momento de consumir nuestra API, supondré que la idea es que no salgan errores de ese tipo, o que haya un correcto manejo de ellos.
Muchas gracias

**Comment by gpvidal** [comment]
Podrías retornar un `statusCode` de 204 :wink:

**Comment by andresplass** [comment]
En este caso dentro del router delete de la api tendria que retornar ctx.state(204), algo así?

**Comment by gpvidal** [comment]
Sí, puedes buscar en la documentación de Koa.

Saludos,
