### ISSUE TITLE
Hora de la entrega 6

### ISSUE THREAD

**Issue by fjlopez7** [IIC2513-2020-1/syllabus#163]
Es posible cambiar la hora de la entrega?, dado que es en la mañana implica en que varios grupos se tengan que amanecer trabajando si la entrega es a las 10 de la mañana. Si fuera al menos a las 10 o 12 de la noche nos permitiría dormir y realizar una entrega de mejor calidad.

**Comment by gpvidal** [comment]
No, la fecha de la entrega está publicada hace bastante tiempo.

Saludos,
