### ISSUE TITLE
Error al subir a heroku - package-lock.json

### ISSUE THREAD

**Issue by ibaeza1** [IIC2513-2020-1/syllabus#165]
Hola!
Al tratar de subir la app a heroku no sale que hay dos archivos lock, el yarn.lock y el package-lock. 
Borramos el package-lock pero nos sigue saliendo el error. Si le hago git rm package.-lock.json me dice que no hay ningun archivo que se llame asi, pero al intentar subir la aplicacion me dice que si entonces no entiendo nada jaja.
Que puede ser?
Gracias :)

**Comment by gpvidal** [comment]
Hola @ibaeza1 ,

Eso les pasa por mezclar `npm` con `yarn`! :stuck_out_tongue: 

Recuerda que hay una versión de tu código en heroku, se hace push a un repositorio. Podrías intentar hacer un push force.

Saludos,

**Comment by ibaeza1** [comment]
Sii ahi lo logramos jaja
