### ISSUE TITLE
Error al hacer fetch

### ISSUE THREAD

**Issue by ibaeza1** [IIC2513-2020-1/syllabus#166]
Hola!
Estamos tratando de hacer fetch a nuestra api desde una app externa y tenemos esto:
`async function getUser(){`
`  var job = await fetch('https://mighty-gorge-19097.herokuapp.com/api/auth',{`
         ` method: 'POST',`
          `headers: {`
            `  'Content-Type': 'application/json',`
         `     'API-Key': 'secret'`},
          `mode: 'no-cors',`
       `   body: JSON.stringify({'email': "aplass@uc.cl", 'password': "12345678"})}`
      `.then(function(response) {`
       `   return response.json();`
      `    console.log("respuesta",response.json())`

  `    })`
   `  .then(function(data) {`
     `   console.log('data = ', data);`
      `})`
    `  .catch(function(err) {`
      `    console.error(err);});`
`}`
Hacemos heroku logs y nos dice que el atributo al email se esta enviando algo undefined pero no entendemos por que ya que se lo estamos enviando bien.
Se supone que le enviamos un mail y una contraseña y nos devuelve un token para poder hacer mas requests.
Por que sera que nos sale ese error?
Gracias :)

**Comment by gpvidal** [comment]
Por que tienen el `no-cors`? Pueden revisar acá si tienen este problema:

https://github.com/IIC2513-2020-1/syllabus/issues/152

Saludos,

**Comment by ibaeza1** [comment]
Porque nos salia
"has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."
Asi que le tuvimos que poner eso. La verdad no entendimos muy bien por que nos salio eso

**Comment by gpvidal** [comment]
Revisa la issue que coloqué antes.
