### ISSUE TITLE
Error en el servidor

### ISSUE THREAD

**Issue by Kitaps** [IIC2513-2020-1/syllabus#168]
Hola, al hacer un request al servidor para obtener el token de autentificación me retorna un error 500. 

Esto es parte del plan o no?

![500](https://user-images.githubusercontent.com/10112117/87384496-e99f7180-c569-11ea-8d63-22e659beea84.PNG)

**Comment by johntrombon** [comment]
creo que debes incluir el header content type = application/json

**Comment by gpvidal** [comment]
:point_up: ojo además que el numero de alumno va como string.
