### ISSUE TITLE
Nota Máxima

### ISSUE THREAD

**Issue by nfbalbontin** [IIC2513-2020-1/syllabus#169]
Hola!
Revisando la pauta del examen me di cuenta que junto con los extras uno obtiene una nota máxima de 7,8. Sin embargo, no se considera el punto base. Por lo que mi duda es que si uno no contesta nada obtiene un 0? o la nota máxima es un 8,8?
Saludos!

**Comment by gpvidal** [comment]
Buen intento! La nota máxima es un 7,8 (con todos los bonus) y la mínima es un 1. Sí, pueden tener más de un 7 en esta evaluación.
Los puntajes no están mapeados 1 a 1 con la nota, salvo lo de los extras.
La nota se calcula como (Pje obtenido / Pje total) * 6 + 1 + extras

Saludos,
