### ISSUE TITLE
problema yarn y yo

### ISSUE THREAD

**Issue by mimunoz11** [IIC2513-2020-1/syllabus#17]
Duda cuando agrego yo me arroja lo siguiente en consola:
`yarn global add yo
yarn global v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "yo@3.1.1" with binaries:
      - yo
      - yo-complete
Done in 1.91s.`

Es correcto que diga lo siguiente?:

success Installed "yo@3.1.1" with binaries:
      - yo
      - yo-complete
Done in 1.91s.`

Porque después no me reconoce el comando yo

**Comment by gpvidal** [comment]
Hola @mimunoz11 ,

Puede depender de como hayas instalado yarn. Este paso puedes reemplazarlo por:

```
$ npm install -g yo
```

y luego instalar el paquete del curso de la misma manera, con npm.

NOTA: Solo hacerlo para este paso, cuando hayas generado la base del proyecto ocupa yarn!

Saludos,

**Comment by mimunoz11** [comment]
Muchas gracias, eso era :D

**Comment by absoto4** [comment]
Hola tengo el mismo problema, pero tampoco me funciona instalar yo con npm. Me sale este error.
![Screenshot_1](https://user-images.githubusercontent.com/39503197/79504192-7a64c080-8000-11ea-9e42-9df1995f4930.jpg)

**Comment by gpvidal** [comment]
Hola @absoto4 ,

Cómo instalaste NPM?

Saludos,

**Comment by absoto4** [comment]
Hmm, la verdad no lo sé. Mi computador tuvo problemas y me prestaron este. Ya estaba instalado npm. La versión es 6.14.4

**Comment by gpvidal** [comment]
Probaste anteponiendo `sudo`? `sudo npm install -g yo`?
Revisa que la versión de node sea compatible! (12.16)

Saludos,

**Comment by absoto4** [comment]
Ahí sí me funcionó! Muchas gracias! 😄

**Comment by vicentesh** [comment]
Hola, trate de instalar yo a través de yarn y después no me reconocía el comando yo, entonces seguí las recomendaciones de este issue pero sigue sin servir, tengo la versión 12.16 de node, me arroja este error
![Captura de Pantalla 2020-04-16 a la(s) 20 11 41](https://user-images.githubusercontent.com/48304636/79518276-adb64800-801e-11ea-9ef0-2b0969e557ad.png)
