### ISSUE TITLE
Duda enunciado, posts con la misma descripción

### ISSUE THREAD

**Issue by mathiasvaldebenito** [IIC2513-2020-1/syllabus#170]
Hola, no entendí la diferencia entre estos dos posts en el enunciado:

![Captura de pantalla de 2020-07-14 03-55-19](https://user-images.githubusercontent.com/37158672/87399889-0e094700-c586-11ea-875f-e580ac043759.png)

**Comment by gpvidal** [comment]
Corregido. Gracias!
