### ISSUE TITLE
Aclaración sobre Instrucciones

### ISSUE THREAD

**Issue by ncasassas** [IIC2513-2020-1/syllabus#171]
Hola, quería aclarar un punto de las instrucciones donde se menciona:

"Esperamos que en esta evaluación la estructura, diseño y comportamiento estén separados.
Si hay una mezcla en alguno de los puntos la nota será la mínima."

Esto implica que por ejemplo si en mi código estoy escribiendo formato html no puedo hacer las funciones entre medio de este formato o hacer esto mismo con los estilos? o se refiere a que debo programar la estructura el diseño y comportamiento en distintos módulos e importarlos dentro de un main archivo ?? 
Pregunto esto por que estoy siguiendo una estructura tal como en el ejemplo del proyecto ( función render que contiene el html y llama a mis funciones cuando es requerido y sobre esta función render escribo las funciones que serán llamadas) y no estoy seguro si esto implica calificación mínima.

Saludos!

**Comment by gpvidal** [comment]
HTML, CSS y JS separados. En el proyecto, puedes ver como https://github.com/IIC2513-2020-1/my-university/ los tiene separados.

Saludos,

**Comment by niguzman** [comment]
El proyecto no usa html sólo. Podemos usar html.ejs como el proyecto?

**Comment by gpvidal** [comment]
Pueden ocupar el template del proyecto si quieren (tal como dice en las instrucciones). Los archivos html.ejs se transforman finalmente a HTML.

Saludos,
