### ISSUE TITLE
Duda API ruta action

### ISSUE THREAD

**Issue by cacoos** [IIC2513-2020-1/syllabus#172]
Hola,

Estoy comunicandome con la API para ejecutar una acción, y al poner el body

{
    "action": {
      "type": "MOVE",
      "ship": "H6,
      "direction": "EAST",
      "quantity": 1
    }
}

Me tira como error {"error":"An action must be defined"}

Qué puede ser?

Gracias!

**Comment by gpvidal** [comment]
Le indicaste a la API que estás enviando un JSON?

Saludos

**Comment by cacoos** [comment]
Si!

Le paso el Content-Type y la Authorization :/

**Comment by cacoos** [comment]
Ahora me funcionó! Estaba pasando mal un string
