### ISSUE TITLE
Duración y Medidas del examen

### ISSUE THREAD

**Issue by fncabrera** [IIC2513-2020-1/syllabus#176]
Hola, 

Dado que nunca fueron capaces de responder mi correo (y varios otros al parecer) junto con (a mi juicio) el descriterio de asegurar que este examen se podía realizar en 2-2.5 horas siendo que solo entender bien el enunciado + estructurar mentalmente era más de una hora (+ todo el tiempo que puede significar ir debugeando el código), quiero expresar mi descontento por acá . 

Vengo recién saliendo de examen de finanzas, ante el cual casi no dormí programando para este examen, y ahora veo esta medida parche (porque no reconoce el problema de fondo) que se vino a avisar 15 horas después de subido el examen. Lamentablemente para mi ya no existe solución frente al inconveniente que tenía, pero quiero dejar de todas formas este mensaje para que lo tengan en consideración para futuras evaluaciones y semestres online. Espero que todos quienes hayan tenido otros exámenes durante hoy o incluso que tienen durante mañana, puedan descansar y rendir :)! Puedo estar equivocado o ser un tema de percepciones, pero yo creo que lo mínimo que uno esperaría después de 14 horas, con la ansiedad de rendir al 100% en dos exámenes con poco dormir, es al menos una respuesta con un simple "no" a un correo. 

Saludos,

**Comment by parodiagabrielvidal** [comment]
Hola soy Gabriel Vial Parodia y no me importa la salud mental de mis estudiantes. Saludos

Closed
