### ISSUE TITLE
Error tipo de evento en enunciado

### ISSUE THREAD

**Issue by matiaseche** [IIC2513-2020-1/syllabus#178]
Hola,

Me di cuenta que en el enunciado dice que hay un evento de tipo `DESTROYED_SHIP` y `DESTROYED_ALL_SHIPS`, pero en la API los eventos son de la forma `SHIP_DESTROYED` y `ALL_SHIPS_DESTROYED`.

**Comment by gpvidal** [comment]
Sí, Gracias! Lo cambiaré!
