### ISSUE TITLE
Event with invalid type

### ISSUE THREAD

**Issue by behrmann97** [IIC2513-2020-1/syllabus#179]
Hola, cuando el computador le pega a uno de mis barcos envío mi acción y eventos de esta manera:
![image](https://user-images.githubusercontent.com/26407766/87489044-f5de0a00-c60f-11ea-9b36-ef92fbbd0b52.png)

Sin embargo, retorna "event with invalid type". Probe distintas cosas y pareciera que el problema es con el "destroyed_ship", pero no logro encontrar mi error.

Gracias!

**Comment by gpvidal** [comment]
Hola @behrmann97 ,

Prueba con `HIT_SHIP`, `SHIP_DESTROYED` y `ALL_SHIPS_DESTROYED` :wink: 

Saludos,
