### ISSUE TITLE
Convención para nombres de modelos

### ISSUE THREAD

**Issue by daleal** [IIC2513-2020-1/syllabus#18]
Hola!
No he podido encontrar en internet si existe alguna convención para llamar a los modelos. Por ejemplo, no sé si un modelo para autos rápidos debería llamarse `fastCar` o `FastCar` (para luego llamar `ctx.orm.fastCar` o `ctx.orm.FastCar`).
Gracias!

**Comment by gpvidal** [comment]
Hola @daleal ,

Yo te recomendaría que siguieras la convención de javascript, *lowerCamelCase* para tus modelos (lo que va dentro del `define`).

Saludos,

**Comment by daleal** [comment]
Gracias!
