### ISSUE TITLE
Problema con informar destrucción de todos los barcos

### ISSUE THREAD

**Issue by behrmann97** [IIC2513-2020-1/syllabus#180]
Hola, tengo un problema con informar cuando el jugador pierde. Como el jugador perdió, debo mandar un evento con el tipo "ALL_SHIPS_DESTROYED", sin embargo, este evento no tiene acción con la cual ir acompañado dado que el jugador no puede tomar una acción después de perder, lo que retorna bad request desde la API.

**Comment by gpvidal** [comment]
Hola @behrmann97 ,

No es necesario que lo informes, solo puedes mostrar el mensaje que ganaste.

Saludos,

**Comment by behrmann97** [comment]
Hola, me refiero cuando uno pierde, cuando el computador te destruye todos tus barcos. ¿No informo que el computador ganó?

**Comment by gpvidal** [comment]
Puedes no informarle, o puedes enviar la última jugada en conjunto con el
evento.

Saludos,
