### ISSUE TITLE
Tests Endpoint

### ISSUE THREAD

**Issue by vramos1** [IIC2513-2020-1/syllabus#181]
Hola, intento usar el test para que el servidor me devuelva una accion despues, me acepta en el endpoint el request, pero luego cuando hago una accion, el servidor arroja error 500. Cual es la manera correcta de usarlo?

**Comment by gpvidal** [comment]
Hola @vramos1 ,

Acabo de probar el endpoint y funciona. No estarás olvidando algo al enviar la acción?

Saludos,

**Comment by vramos1** [comment]
me acepta la request perfecto, pero despues al hacer una request al action normal, se me cae. 
Resumen: hago request put a https://battleship.iic2513.phobos.cl/games/:id/test/action y todo bien
Hago despues request POST a https://battleship.iic2513.phobos.cl/games/:id/action y me arroja internal Server Error. Si corro ese ultimo sin haber hecho al test antes, si funciona

**Comment by cacoos** [comment]
Ahh la issue #184 que creé recién es por lo mismo!

**Comment by cacoos** [comment]
Ya me funcionó! Hay que asegurarse de pasar todo lo que pide el `body`!

**Comment by gpvidal** [comment]
Eso dice el enunciado :stuck_out_tongue: "Ejemplo body: Ver más abajo"
