### ISSUE TITLE
Paquetes examen

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2513-2020-1/syllabus#182]
Hola! Me vi con la necesidad de usar una lista en el state de react. Estoy teniendo problemas para agregar elementos, ya que
```js
setList([...list, newElement])
```
provoca pérdida de información. Puedo usar el paquete npm 'immutability-helper' para solucionarlo?

**Comment by gpvidal** [comment]
Hola @JJJGGGG ,

No, no puedes agregar ese paquete.

Saludos,
