### ISSUE TITLE
Barcos duros

### ISSUE THREAD

**Issue by johntrombon** [IIC2513-2020-1/syllabus#183]
Me di cuenta que la api responde con barcos que aguantan mas de un impacto, es decir que hay veces en que le damos a un barco pero este no muere. ¿Debemos manejar ese caso o consideramos que hit = destroy ?

**Comment by johntrombon** [comment]
No se si es idea mia, pero le tuve que dar dos veces a un barco que presuntamente tenia 2 maxImpacts, y a otro basto con darle una sola vez

**Comment by gpvidal** [comment]
Sí, es para que puedas probar de forma fácil varios casos (como los eventos). En todo caso tu nunca deberías manejar el estado de los barcos del oponente en tu aplicación, los endpoint de tests son básicamente para probar.

Saludos,
