### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by cacoos** [IIC2513-2020-1/syllabus#184]
Hola,

Tengo dos acotaciones/preguntas:

- La ruta `POST games/:id/test/action` para setear la próxima jugada del computador no existe, funciona solo con `PUT`. Está mal el enunciado?
- Usando `PUT` en la ruta antes mencionada, al hacer un `POST games/:id/action` real la API arroja `500 (Internal Server Error)`, por lo que no puedo probar, por ejemplo, que el computador gane.

Estoy atento gracias!

**Comment by gpvidal** [comment]
Creo que por https://github.com/IIC2513-2020-1/syllabus/issues/181#issuecomment-658535111 ya lo solucionaste :wink:
