### ISSUE TITLE
Error de servidor. Al parecer está aído

### ISSUE THREAD

**Issue by Oisangui** [IIC2513-2020-1/syllabus#187]
Hola, el servidor está funcionando?
```html
<html>

<body>
	<h1>503 Service Unavailable</h1>
	No server is available to handle this request.
</body>

</html>
```

**Comment by Michelmagna** [comment]
Media hora pegado ya :(

**Comment by raespinoza4** [comment]
Más de media hora :( se cayó a las 4

**Comment by Michelmagna** [comment]
@raespinoza4  Igual era re imaginable que pasara algo así :/

**Comment by Oisangui** [comment]
2 horas caído

**Comment by gpvidal** [comment]
Ya está up and running

**Comment by BenjaPrograma** [comment]
Hola @gpvidal, considerando que estuvo caído por más de 3 horas, están evaluando extender los plazos de entrega?

**Comment by Michelmagna** [comment]
@gpvidal  Aun me aparece caído profesor

**Comment by viantirreau** [comment]
@gpvidal Profe, al principio, antes de dar el 503 teníamos problemas con CORS, por si pudiese revisar si siguen los headers de `Access-Control-Allow-Origin: *` en los _endpoints_ de la API. Gracias desde ya!

**Comment by gpvidal** [comment]
@Michelmagna Yep! My bad! Ya estaría OK

@viantirreau no es posible o indica que tienes un problema en tu configuración. Tengo un cliente con la solución corriendo y no arroja esos problemas

**Comment by viantirreau** [comment]
Genial, ya no me da problemas tampoco, gracias @gpvidal .
Como incident report, este comenzó a las 3:57 AM según las primeros reportes de mis compañeros, por lo que estuvo 3 horas con 50 minutos caída.
Puede considerar una extensión en el plazo de entrega sin descuentos que sirva para compensar el tiempo que no pudimos seguir consumiendo la API?
Gracias nuevamente!

**Comment by Michelmagna** [comment]
@gpvidal Concuerdo con la petición de mi compañero. El examen de por si es muy largo y al igual que varios compañeros, durante esta noche pensaba terminar la parte final de la tarea (que depende absolutamente de la API funcionando). Debido a esta situación, ya me resigné a no entregarla a las 13pm y seguir en la tarde por sueño
Ojala considere esto profesor! Saludos y gracias!

**Comment by BenjaPrograma** [comment]
Hola! Me sigue sin funcionar, me tira error de CORS.

**Comment by Oisangui** [comment]
De repente se cae. Recomiendo volver a hacer el request hasta que funcione.

**Comment by gpvidal** [comment]
> De repente se cae. Recomiendo volver a hacer el request hasta que funcione.

Esto era yo, revisando unas cosas

> Hola! Me sigue sin funcionar, me tira error de CORS.

Cómo te digo, tengo la solución corriendo y a tus compañeros les funciona. No es un problema de la API.
