### ISSUE TITLE
Cambio 

### ISSUE THREAD

**Issue by matiasop** [IIC2513-2020-1/syllabus#188]
Hola,

Ayer la API funcionaba con eventos SHIP_DESTROYED y ALL_SHIPS_DESTROYED. Hoy amaneció funcionando con eventos del tipo DESTROYED_SHIP y DESTROYED_ALL_SHIPS.Yo envié mi tarea ayer a las 22.30 aproximadamente usando los eventods de la forma SHIP_DESTROYED y ALL_SHIPS_DESTROYED, pero ahora con el cambio mi tarea no funciona. La tarea solo se puede enviar una vez, por lo que no puedo hacer cambios a mi aplicacion. Además tengo un examen de otro ramón hasta las 13 horas, así que aun que se me diera la oportunidad de hacer los cambios, no podría hacerlos hasta antes de las 13 hrs, lo que haría que me descuenten 5 décimas de mi nota. ¿Qué puedo hacer?

**Comment by gpvidal** [comment]
Hola @movalle4 ,

Es solo el cambio de los strings de los eventos?
btw, la API no ha cambiado.

Saludos

**Comment by matiasop** [comment]
Tiene razón. No se cambió la API. Pensé que se habia cambiado porque lo vi en otra issue.

Gracias por su respuesta
