### ISSUE TITLE
direnv - envrc - variables de entorno

### ISSUE THREAD

**Issue by mimunoz11** [IIC2513-2020-1/syllabus#19]
Hola, no he podido encontrar un buen tutorial de todo el proceso de como configurar las variables de entorno con direnv y envrc. En mi caso, aún con la clase, video y tips,  no me queda claro . 

Si alguien tiene algun tutorial o guia de esto me sería de mucha utilidad, gracias

**Comment by iaacosta** [comment]
¡Hola @mimunoz11! Deberían ser solo dos pasos:

1. **Instalar `direnv`** - dependiendo si usas OS X o alguna distribución de Linux, debes usar el _package manager_ correspondiente (e.g., `sudo apt install direnv` para Ubuntu, `brew install direnv` para OS X).

2. **Hacer el _hook_ con tu terminal** - depende de la _shell_ que estás usando. A menos que hayas instalado `zsh`, `fish` o algun otro, deberías tener `bash` por defecto. En ese caso, basta con ejecutar lo siguiente:

    `echo 'eval "$(direnv hook bash)"'  >> ~/.bashrc`

Luego cierras y abres tu terminal y deberias poder utilizar `direnv allow` en el directorio donde tengas `.envrc` para cargar tus variables de entorno. Puedes probar si se cargaron si es que el siguiente comando la imprime en consola:

`echo $TU_VARIABLE`

Avísame si te surge algún problema o no te funciona después de esto :smiley:
