### ISSUE TITLE
document.getelementById(id).style.background = 'green'

### ISSUE THREAD

**Issue by andresplass** [IIC2513-2020-1/syllabus#190]
Hola puedo utilizar este recurso para cambiar el color de algo en mi js?
Hay una issue y no queda claro.
Hay descuento?

**Comment by andresplass** [comment]
Dado el tiempo asumiré que sí se puede usar

**Comment by gpvidal** [comment]
Es parte de las instrucciones del examen, en este punto deben saber lo que corresponde a comportamiento y lo que corresponde a estilo y donde va cada cosa.

Saludos,

**Comment by andresplass** [comment]
Pero la función document.getelementById(id) es una funcion de comportamiento, entonces se puede utilizar o no

**Comment by gpvidal** [comment]
Claro que puedes ocupar esa función `document.getElementById()`

**Comment by andresplass** [comment]
Entonces está bien haber utilizado la función en mi .js para cambiar el comportamiento de mis elementos?

**Comment by gpvidal** [comment]
`document.getElementById()` es una función que te retorna un elemento del DOM que tiene el `id` especificado, no cambia nada.

El código JS es para cambiar comportamiento, eso lo vimos en clases. CSS para estilos y HTML para estructura.

Saludos,

**Comment by andresplass** [comment]
Pero sigue siendo una funcion de javascript entonces estaria bien usar esa funcion en el .js

**Comment by gpvidal** [comment]
Andrés, es parte de lo que estamos evaluando.
