### ISSUE TITLE
Cambios de mensaje en la API

### ISSUE THREAD

**Issue by jnhasard** [IIC2513-2020-1/syllabus#191]
Hola!

Entregué mi examen anoche y me enteré que cambiaron algunos mensajes entregados por la API lo cual provoca que algunos logs no se estén haciendo correctamente. Espero que esto sea tomado en consideración a la hora de corregir y para un próximo cambio creo que podrían avisar al hacerlo.

**Comment by gpvidal** [comment]
@jnhasard ,

No se cambió nada en la API, alguien nos informó que estaban mal escritos en el enunciado. Si antes te funcionaban, debe seguir haciéndolo porque la API no ha sido modificada.

Atte
