### ISSUE TITLE
Agregar js a jupyter

### ISSUE THREAD

**Issue by Arodriguez14** [IIC2513-2020-1/syllabus#2]
Hola! Traté de hacer los ejercicios de la clase dos en un jupyter notebook pero solo me deja trabajar con python 3. ¿Como puedo agregar javascript?

Gracias!

**Comment by gpvidal** [comment]
Hola @Arodriguez14 ,

En el servidor que les mostré o tu instalaste uno?

Saludos,

**Comment by Arodriguez14** [comment]
Ahora use el servidor del link en las diapositivas de clases, pero no me aparecen archivos en el jupyter. Esto es porque no se han subido o deberian aparecerme?

**Comment by gpvidal** [comment]
Porque te registraste después, te los voy a agregar en un momento. Dame unos minutos

**Comment by gpvidal** [comment]
@Arodriguez14 ya deberías tenerlos en tu directorio!

Saludos!

**Comment by Arodriguez14** [comment]
Ahí si. Muchas gracias!!!!!

**Comment by fthurtado** [comment]
Hola! Me podrías agregar a mí también porfavor! Que tampoco me funciona

**Comment by Arodriguez14** [comment]
A mi tampoco me funciona ahora. Nose que paso. Será porque soy de la seccion 2 y esa clase es de la seccion 1?

**Comment by gpvidal** [comment]
Acabo de agregar el material :+1: 

Saludos,
