### ISSUE TITLE
NVM problema

### ISSUE THREAD

**Issue by stmorales** [IIC2513-2020-1/syllabus#20]
Hola!
Tengo una pregunta que se relaciona con un problema que tengo. ¿Para qué sirve NVM?

He leído que sirve para correr localmente distintas versiones de NodeJS. Sin embargo, al instalar la versión 16.12 de NodeJS y correr el yarn dev, me dice que "yarn" necesita NodeJS >= 4.0 para funcionar.

Si me pueden explicar para qué es necesario NVM se los agradecería, porque no entiendo la utilidad si me tengo que descargar también NodeJS permanentemente.

Gracias!

**Comment by gpvidal** [comment]
Hola @stmorales ,

Sirve para justamente lo que dices, tener varias versiones de Node corriendo localmente. Pero además permite instalar de forma fácil Node. Simplemente `nvm install <version>`.

En tu caso, probablemnte te ocurra eso porque no configuraste tu `.bashrc` (o equivalente) con el comando que sale en las instrucciones de NVM, o no hiciste logout de tu sesión y luego login para que se cargaran estas configuraciones.

NVM instala Node de forma fácil. Lo puedes instalar también directamente, pero cuando quieras (o tengas) que ocupar otra versión de tendrás que desintalarlo e instalar la nueva versión.

Saludos,

**Comment by stmorales** [comment]
Lo extraño es que me aparece que si estoy usando la versión de NodeJS 16.12.1. 

![Screenshot from 2020-04-03 10-24-02](https://user-images.githubusercontent.com/42178490/78365301-4b2c6900-7595-11ea-868c-45d346a2163d.png)

Me reconoce los comandos de nvm, pero a la hora de correr yarn no lo hace.

Gracias

**Comment by gpvidal** [comment]
Instalaste `yarn`?

```
$ npm install -g yarn
```

**Comment by iaacosta** [comment]
Para complementar lo que dice @gpvidal, cuando corres `yarn` con `sudo` se pierde la configuración de tu usuario (`sebastian`) que contiene las versiones que instalaste con `nvm`, por esto no te lo reconoce. 

Trata de correr `yarn dev` a solas.

**Comment by gpvidal** [comment]
Ahh good catch @cho19 :wink:

**Comment by gpvidal** [comment]
Ah! No quiero dejar de perder la oportunidad de indicar que estos comando **no** deberían correrlos con sudo, ya que no es necesario.

Saludos!

**Comment by stmorales** [comment]
Muchas gracias!
