### ISSUE TITLE
Permiso denegado al iniciar un Template

### ISSUE THREAD

**Issue by fabarros** [IIC2513-2020-1/syllabus#21]
Hola! Al tratar de crear un template como en el video que subió el profesor me tira el siguiente error:
```
fabarros@fabarros-G3-3579:~$ yo @iic2513/template my-university
/usr/local/share/.config/yarn/global/node_modules/write-file-atomic/index.js:236
    throw err
    ^

Error: EACCES: permission denied, open '/home/fabarros/.config/insight-nodejs/insight-yo.json.3206112855'
```
No logro saber cómo solucionarlo. Gracias por la ayuda!

**Comment by gpvidal** [comment]
Hola @fabarros !

Aquí hay algo extraño... como tu usuario no tiene permisos en su carpeta del sistema? Corriste en algún momento algo con sudo?

Saludos!

**Comment by fabarros** [comment]
Ehh si, todos los comandos porque o si no no me dejaba.

**Comment by gpvidal** [comment]
No instalaste node con NVM cierto? lo instalaste con unos `.deb`?

**Comment by fabarros** [comment]
Usé `curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
` y `sudo apt-get install -y nodejs` para corregir la versión

**Comment by gpvidal** [comment]
me imagino que si haces:
```
$ sudo yo @iic2513/template my-university
```
funciona verdad?

**Comment by fabarros** [comment]
me arroja el mismo error :/

**Comment by gpvidal** [comment]
Yap, tenemos que probar algo. Vamos a forzar que nuevamente todos los archivos que están en tu directorio de usuario sean de tu usuario (valga la redundancia).

Para esto tienes que hacer lo siguiente:
```
$ sudo chown -R fabarros:fabarros /home/fabarros
```

Ve si después de eso, al ejecutar el comando, funciona.

Saludos,

**Comment by fabarros** [comment]
IT WORKS!
Gracias profe!

**Comment by B-Dominguez** [comment]
Hola, solo vengo a agradecer la respuesta porque después de muchos intentos fallidos basados en issues de github, documentación, stackoverflow, etc ahora logré arreglar este mismo error. Muchas gracias!!
