### ISSUE TITLE
Funciones importadas jupyter asíncronas

### ISSUE THREAD

**Issue by crvargasu** [IIC2513-2020-1/syllabus#22]
Hola, no sé donde se encuentran las funciones que debemos importar en el documento de funciones asíncronas.

![Captura de Pantalla 2020-04-03 a la(s) 21 44 55](https://user-images.githubusercontent.com/48322767/78414827-75f9da00-75f4-11ea-8ef9-0ec5f0343ecc.png)

**Comment by gpvidal** [comment]
Hola @crvargasu!

Tu problema es otro, probablemente ya ejecutante esa línea (solo se puede ejecutar una vez).

Esa es la línea que importa las funciones asíncronas.

Saludos,

**Comment by crvargasu** [comment]
Pero al resetear el kernel el problema persiste.

Incluso si intento ejecutar el archivo de soluciones me dice que las funciones que debiesen estar importadas no están definidas.

**Comment by gpvidal** [comment]
La foto era del Notebook que les subí?

**Comment by crvargasu** [comment]
Sí

**Comment by gpvidal** [comment]
Lo estás ejecutando en el servidor de ejercicios? (iic2513.phobos.cl:8000)

**Comment by crvargasu** [comment]
Quizás ese sea el problema, como puedo ejecutarlo en el servidor de ejercicios?

**Comment by gpvidal** [comment]
No es quizás, ese es el problema :stuck_out_tongue:  Ese Notebook referencia a archivos que están en mi directorio de usuario en ese servidor. 

Puedes entrar a la dirección, y subir el Notebook si no lo tienes en tu cuenta de usuario. 

Saludos!

**Comment by crvargasu** [comment]
Disculpe profe, no sé como hacer eso

**Comment by gpvidal** [comment]
Deberías ver un botón como este (que dice upload), cuando ingresas con tu usuario. Al hacer click ahí puedes subir un archivo.

![image-50](https://user-images.githubusercontent.com/5266111/78416096-bbbaa080-75fc-11ea-9f2d-12808811f19f.png)

**Comment by crvargasu** [comment]
Si entiendo eso, lo que no sé es donde están los archivos que debo subir

**Comment by gpvidal** [comment]
Ahhh El archivo que tiene las funciones no está disponible para descarga, entonces lo que puedes hacer es que subes el archivo que tu tienes en tu sistema al servidor de ejercicios y lo corres de ahí. O copias y pegas tus comandos, esa es otra opción.

Saludos,

**Comment by Arodriguez14** [comment]
Hola! Yo soy de la otra seccion y feliz de hacer esos ejercicios. ¿Como los puedo hacer si no estoy en el servidor?

Saludos

**Comment by crvargasu** [comment]
Hola! Me pasó lo mismo, por eso no entendía.
Hay un link en el segundo ppt, donde puedes entrar al servidor y hacer los ejercicios

**Comment by Arodriguez14** [comment]
Gracias!

**Comment by gpvidal** [comment]
Gracias @crvargasu ! :wink:
