### ISSUE TITLE
Prueba

### ISSUE THREAD

**Issue by nhbravo** [IIC2513-2020-1/syllabus#23]
Hola! Cómo va a ser la prueba del martes y cuáles son los contenidos a evaluar?
Gracias!

**Comment by gpvidal** [comment]
Hola @nhbravo ,

En el video de la clase del jueves, de esta semana, respondí esa pregunta. Ahí puedes encontrar más detalles.

Saludos,

**Comment by JJJGGGG** [comment]
Hola, yo soy de la otra sección, donde puedo ver ese video?

**Comment by KnowYourselves** [comment]
Hola @JJJGGGG!

También soy alumno de la otra sección y en [este enlace](https://intrawww.ing.puc.cl/siding/dirdes/ingcursos/cursos/vista.phtml?accion_curso=carpetas&acc_carp=abrir_carpeta&id_curso_ic=12326&id_carpeta=77792) puedes encontrar todo lo que ha subido el profesor de la sección 1.

En caso de que el enlace no funcione puedes ir a IngCursos -> Catalogo -> Computación -> Web Seccion 1 -> Enlaces.

**Comment by JJJGGGG** [comment]
Hola, el video dura 1h30, no hay una versión resumida que contenga los contenidos a evaluar?

**Comment by KnowYourselves** [comment]
Al inicio del video dice que enrra hasta el martes pasado (callbacks  promesas)

**Comment by gpvidal** [comment]
Hola @JJJGGGG , @KnowYourselves !

Ojo que les recuerdo que las clases grabadas corresponden a la S1, no sé lo que su profesor les habrá dicho en sus clases.

Hasta ese momento, nosotros (S1) hemos visto:

- Javascript básico (arreglos, objetos, otros)
- Javascript asíncrono (Promesas y callbacks)
- Elementos básicos de la web

Todo esto lo pueden ver publicado en este repositorio.

Saludos,
