### ISSUE TITLE
No se puede acceder a servidor

### ISSUE THREAD

**Issue by amyaranta** [IIC2513-2020-1/syllabus#24]
He intentado entrar a los links de las diapositivas desde hace unos dias, pero me sale este error. Que se puede hacer para solucionarlo?
![Screenshot from 2020-04-06 15-14-59](https://user-images.githubusercontent.com/38705042/78596417-b8503080-7819-11ea-8502-6bb3486d643a.png)

**Comment by gpvidal** [comment]
Hola @amyaranta !

Ya está disponible nuevamente.

El problema es que muchos de tus compañeros no cierran sus sesiones al terminado y dejan recursos tomados del sistema. 

Saludos,

**Comment by amyaranta** [comment]
Volví a intentarlo, pero aún no me deja

**Comment by amyaranta** [comment]
Después de actualizarlo hartas veces me dejó, muchas gracias.
