### ISSUE TITLE
Problemas Yarn

### ISSUE THREAD

**Issue by MGilB** [IIC2513-2020-1/syllabus#25]
Hola, tengo un problema con yarn, lo instale usando tengo instalada la version 13.12 de node, instale yarn con el comando `sudo apt install --no-install-recommends yarn` y me instalo la version 0.32.

Al tratar de ejecutar el comando `yarn global add yo`, me aparece el error `No such file or directory: 'global'`. por lo que segui lo que respondieron en la issue #17 y pude instalar yo e hice lo mismo para el paquete del curso pero, tengo problemas al instalar las dependencias del paquete.

**Comment by gpvidal** [comment]
Hola @MGilB ,

Cual es el error que te arroja? Como instalaste node?

Saludos,

**Comment by MGilB** [comment]
Al ejecutar `yo @iic2513/template my-university`, me aparece la opción de instalar las dependencias, pongo "y" y al final me aparece este error.

![Captura de pantalla de 2020-04-06 19-28-38](https://user-images.githubusercontent.com/37163381/78614640-19d5c680-783d-11ea-9fac-e30f7607dc9b.png)

**Comment by gpvidal** [comment]
Efectivamente nosotros tenemos la versión de `node` y `yarn` del template del curso para la 12.16 (la que recomendamos instalar) que es la que hemos testeado extensamente.

Puedes ir al `package.json` de tu proyecto y cambiar esos valores en ese JSON bajo la propiedad "engines". Sin embargo, te aclaro que el package no ha sido probado en esa versión (13.12).

Saludos,

**Comment by MGilB** [comment]
Gracias, al final lo que hice fue cambiar las versiones de nodejs a las 12.16 y actualizar yarn que no lo había hecho yfuncionó.
