### ISSUE TITLE
Enunciados I1 y buzones

### ISSUE THREAD

**Issue by FelipeBodelon** [IIC2513-2020-1/syllabus#26]
No se si me ocurrió solo a mi o quizás a la mitad del curso pero, me llegaron 2 mails con 2 enunciados y 2 buzones distintos (asumo que correspondía uno por cada forma de la prueba). Esto sumado con el tiempo adicional entregado me confundió bastante, y  no sé si entregué la versión final de mis respuestas en el buzón adecuado y a tiempo. Espero que se pueda aclarar la situación, ya que claramente hubo una confusión en la entrega de enunciados. Trabajé en el primero que me apareció en el mail y no sé si es el que me corresponde tampoco.

**Comment by gpvidal** [comment]
Hola @FelipeBodelon ,

Mientras hayas entregado todo bien, nosotros revisaremos los buzones y ordenaremos.

Saludos,
