### ISSUE TITLE
Configurar la Base de Datos

### ISSUE THREAD

**Issue by fabarros** [IIC2513-2020-1/syllabus#27]
Hola! Estoy aprendiendo esto de configurar mi ambiente para levantar una página web pero no entiendo bien lo relacionado a la configuración de la base de datos.
En el video se nos dice que debemos setear las variables de entorno con el usuario y la password de nuestra base de datos y mi duda es:
1) Tengo que crear una base de datos con PostgressSQL o voy a usar una base de datos de otro lugar?
2) Si tengo que crear mi propia base de datos, cómo vamos a trabajar en equipo con mi grupo si cada uno tiene su propia base de datos instalada?

Gracias! Saludos.

**Comment by iaacosta** [comment]
Hola @fabarros! Tus dudas son súper buenas.

1. Ambas. Cuándo desarrolles para la entrega, usarás tu propia base de datos en tu computador con tus propias configuraciones. Cuándo la subas a Heroku para que la revisemos, la aplicación apuntará a una base de datos online (que deben configurar previamente). 

    Esto es una de las principales ventajas de usar variables de entorno, te permite cambiar cosas como la base de datos dependiendo de como tu aplicación las lee :smile: 

2. Estás en lo correcto, hay un conflicto porque cada uno tiene su propia base de datos. En primer lugar, el template está restringido a Postgres y los obliga por lo menos a estar alineados con eso. Los dos principales problemas adicionales que se presentan (y sus soluciones) son:
    - **Distintos modelos y atributos entre sus bases de datos** - se necesita que estén sincronizados cada vez que hacen un cambio a la base de datos (e.g., agregar columna, crear tabla). Es inviable que solo conversando la mantengan sincronizada. 

      Para esto existen las **migraciones**, que consisten en pequeños *scripts* que hacen estos cambios y algun otro ajuste necesario. Lo más importante es que estas se comparten mediante su repositorio y con un solo comando pueden sincronizar su base de datos con la del resto.

    - **Distintos datos entre sus bases de datos** - resultaría molesto que uno de ustedes creara varias instancias para que la página se viera bien y que esto no lo pudiesen replicar entre ustedes de manera sencilla. Puede hasta ser conveniente que lo repliquen en la página hosteada en Heroku. 

      Para esto existen las **seeds**, que les permiten definir programaticamente una serie de datos iniciales que poblan su base de datos mediante un solo comando. También se comparten mediante su repositorio y buscan que tengan una base inicial con que rellenar su aplicación. Si bien esto no asegura que siempre tengan los mismo datos en todo momento, eso no implica algo negativo.

¡Espero te haya quedado más claro! :raised_hands:
