### ISSUE TITLE
Problema crear modelo: trata de instalar el paquete de nuevo

### ISSUE THREAD

**Issue by FloValdes** [IIC2513-2020-1/syllabus#28]
Hola! seguí el video para crear un proyecto y dejarlo andando en localhost, funcionó todo bien.
El problema aparece cuando intento hacer un CRUD y quiero crear un modelo:

![image](https://user-images.githubusercontent.com/37163115/78824062-bfa74380-79ab-11ea-93b4-a0b3e1648ff6.png)

Me sale esto, como si tuviera que instalar todo de nuevo. Si pongo Y o n igual me sale lo mismo la siguiente vez que intento crear un modelo.
Lo que sí, me sale esto si pongo "Y":

![image](https://user-images.githubusercontent.com/37163115/78824279-19a80900-79ac-11ea-9c05-0409ad9e4484.png)

Qué podría ser? 
Gracias!

**Comment by gpvidal** [comment]
Hola @FloValdes !

No debe haber espacios en `:model`, el comando es:

`yo @iic2513/template:model` :wink: 

Saludos,

**Comment by FloValdes** [comment]
Ups, gracias profe!
