### ISSUE TITLE
Error Postgres

### ISSUE THREAD

**Issue by MGilB** [IIC2513-2020-1/syllabus#29]
Hola, tengo un error en postgres igual que el la issue #14, seguí las instrucciones que estaban, me metí al link donde encontró la solución y todo pero sigo con el mismo problema.
Puedo ejecutar el comando `sudo su - postgres` que me mete a la "consola" de postgres pero despues tratode poner `psql` y tira el error
`psql: error: could not connect to server: could not connect to server: No such file or directory Is the server running locally and accepting connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?`

Tengo postgres 12.x

**Comment by gpvidal** [comment]
Hola @MGilB ,

Probaste con `sudo service postgresql start` (o `sudo systemctl start postgresql`)?

Saludos,

**Comment by MGilB** [comment]
Si si probe con los dos comandos pero me aparece el mismo error

![Captura de pantalla de 2020-04-09 10-19-51](https://user-images.githubusercontent.com/37163381/78905373-e1f09e00-7a4b-11ea-802f-e42b9b67d654.png)

**Comment by gpvidal** [comment]
Y cuál es la salida con:

`sudo service postgresql status` (o `sudo systemctl status postgresql`)?

Gracias!

**Comment by MGilB** [comment]
Esta es la salida de `sudo srvice postgresql status`:

![Captura de pantalla de 2020-04-09 11-51-27](https://user-images.githubusercontent.com/37163381/78914615-a9a38c80-7a58-11ea-8989-02ff2e7afe8e.png)

**Comment by gpvidal** [comment]
¿Como instalaste Postgres? Lo que muestra esa salida es que parte y luego se detiene.

Saludos,

**Comment by MGilB** [comment]
Lo instalé con `sudo apt-get install postgresql postgresql-contrib`, como decia en este link que https://tecadmin.net/install-postgresql-server-on-ubuntu/ que puso un compañero en la issue #14

**Comment by gpvidal** [comment]
Dos preguntas más:

* Versión de Ubuntu
* Versión que se instaló de postgres

Lo siento, olvidé preguntarte esto antes

**Comment by MGilB** [comment]
Mi versión de ubuntu es 18.04 y de postgres es la 12.2

**Comment by gpvidal** [comment]
Puedes ver qué tiene este archivo? Es muy raro tu problema, pero podría darnos luces:

`$ cat /var/log/postgresql/postgresql-12-main.log`

No sé si existirá en tu sistema un archivo como ese, cualquiera que esté en `/var/log/postgresql/` sirve.

Lo otro que se puede hacer es reinstalar postgres e instalar los paquetes que están en el repositorio de Ubuntu (y no de PostgreSQL). Para esto:

```
$ sudo apt-get purge postgresql postgresql-contrib
$ sudo rm /etc/apt/sources.list.d/pgdg.list
$ sudo apt-get update
$ sudo apt-get install postgresql postgresql-contrib
```

Saludos,

**Comment by MGilB** [comment]
Esto me apareció cuando puse `$ cat /var/log/postgresql/postgresql-12-main.log`:

![Captura de pantalla de 2020-04-09 17-05-00](https://user-images.githubusercontent.com/37163381/78940865-8ee70d00-7a84-11ea-970f-23be2fe798a8.png)

Reinstalo postgres o todavía no?

**Comment by gpvidal** [comment]
Raro, no se te apagó el computador o algo mientras configurabas. Puedes intentar algo como esto (antes de lo que te mencioné más arriba):

```
$ sudo apt-get purge postgresql postgresql-contrib
$ sudo apt-get install postgresql postgresql-contrib
```
Esto va a reinstalar la versión que tienes actualmente. Prueba con esto primero creo yo :wink: 

Saludos,

**Comment by MGilB** [comment]
Acabo de reinstalar la postgres y me pasa exactamente lo mismo, al usar `sudo service postgresql start` no ocurre nada y la otra opción igual, para meterme a la consola de postgres uso `sudo su - postgres`, pero una vez dentro pongo `psql` y el mismo error de antes.

Y no al instalar postgres no se me apagó mi computador.

**Comment by gpvidal** [comment]
Entonces creo que te queda hacer los últimos pasos de esta respuesta https://github.com/IIC2513-2020-1/syllabus/issues/29#issuecomment-611735187

Saludos,

**Comment by MGilB** [comment]
Acabo de instalarlo como me dijo y ya no me aparece el mismo error pero, al poner `sudo -su postgres` para ingresar a postgres me salió el siguiente error, se puede deber a que antes trate de instalar `direnv `para el tema de las variables de entorno.

![Captura de pantalla de 2020-04-10 10-56-44](https://user-images.githubusercontent.com/37163381/79000162-20ed2500-7b1a-11ea-8e07-05c105baff00.png)

Y después de que me saliera este error puse de nuevo `sudo -su postgres` y me pide una contraseña de postgres, que no se si hay una por defecto.

Se instalo la versión 12.2 de postgres.

**Comment by gpvidal** [comment]
El comando es con un espacio luego del - ( `sudo su - postgres`). Prueba con eso :wink: 

Saludos,

**Comment by MGilB** [comment]
Ahí pude entrar al servidor de postgres, muchas gracias.
