### ISSUE TITLE
Duda respecto a create y new

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2513-2020-1/syllabus#31]
Hola!

Hay algo que no me ha quedado claro desde ing de software. Cuando se hace manejo para crear algo en la base de datos se define tanto un`get` en la ruta `new` como un `post` para efectivammmente crear el elemento en la bdd. ¿Cual es la necesidad de esto?

Muchas gracias!

**Comment by JorgeBdelaT** [comment]
Holaa, el get es para obtener la vista donde crearás tu entidad y el post es el método que va en el form. Avisame si tienes otra duda!

**Comment by KnowYourselves** [comment]
Gracias!

En tal caso si fueramos a diseñar una API RESTFUL no sería necesario ese `get`?

**Comment by JorgeBdelaT** [comment]
Claro, porque la vista la manejaría el cliente, la Api solo entrega el endpoint para el create (post).

**Comment by KnowYourselves** [comment]
Me quedo claro, gracias!
