### ISSUE TITLE
Paquetes deprequedos

### ISSUE THREAD

**Issue by Kitaps** [IIC2513-2020-1/syllabus#32]
Hola al instalar yo me arroja las siguientes advertencias: 

![image](https://user-images.githubusercontent.com/10112117/79027259-8ca2b280-7b59-11ea-90f8-8b00247af86a.png)

Eso podría ser un problema o lo ignoramos simplemente?

Gracias :)

**Comment by gpvidal** [comment]
Hola @Kitaps ,

No, no deberías tener problemas.

Saludos,

**Comment by Kitaps** [comment]
gracias :D
