### ISSUE TITLE
Resetear secuencia id en sequelize

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2513-2020-1/syllabus#33]
Hola!

Actualmente tengo un pequeño problema, cada vez que tiro para abajo las _seeds_ y las vuelvo a correr, el _id_ de las tablas no se resetea. Esto es solucionable haciendo un _reset_ de las migraciones, pero hay alguna forma de hacer esto desde el _down_ de las _seeds?_, busque pero no encontré nada.

Gracias!

**Comment by cho19** [comment]
Hola!

Las `seeds` utilizan una API de Sequelize que se llama `QueryInterface`, esta tiene varios métodos como el bulkInsert Puedes intervenir el método `down` de la `seed` para que ejecute una consulta directa en SQL.

**Comment by iaacosta** [comment]
Hola @KnowYourselves!

Para esto tienes que alterar las secuencias a nivel de base de datos y se puede hacer a través de los mismos archivos de `seed`

Estos utilizan una API de Sequelize que se llama `QueryInterface`, que tiene varios atributos como la función `bulkInsert` que viene por defecto para insertar varios elementos a una tabla. 

También tiene como atributo a `sequelize` (objeto) que tiene como atributo a `query`, una función que recibe cualquier consulta SQL y la ejecuta asíncronamente. Puedes usar esta herramienta en el `down` para ejecutar la consulta que resetea tu secuencia a 0 :smile: 

¡Ojalá te sirva!

**Comment by KnowYourselves** [comment]
Ah, te refieres entonces que haga `sequelize.query(***)?` Donde `***`  sea la `query` para reiniciar la secuencia?

**Comment by iaacosta** [comment]
Claro! Pero con `queryInterface.sequelize.query(/* ... */);`

**Comment by KnowYourselves** [comment]
Me funcionó!!! Muchas gracias.

**Comment by gpvidal** [comment]
Hola @KnowYourselves ,

Solo una consideración, ojo cuando hagas referencias y reinicies las series de id. Posiblemente te podrían quedar que nuevas entidades referencien a datos antiguos.

Por ejemplo tienes un compra que referencia a un usuario. Tienes una compra que referencia al usuario uno y tus seed reinician los ids para los usuarios. Si corres esa seed, se va a borrar el el usuario que referencia esa compra y lo vas a reemplazar por otro.

Es por esto que las seed tienen el objetivo de poblar la base de datos y no de hacer este tipo de operaciones. Ya que al borrar los datos que tiene la tabla y crear nuevas entidades (son nuevas aunque tengan los mismos datos) deberían tener un id distinto.

Saludos,

**Comment by KnowYourselves** [comment]
Hola Profesor!

Mi pregunta iba enfocada a que mi única opcion para lograr lo que quería era correr todas las migraciones y las semillas de nuevo (que es mas lento), entonces quería saber si se podía lograr lo mismo solo corriendo las semillas de nuevo.

Pero lo que dice me produce la siguiente, duda, en tal caso no tendría sentido hacer _down_ de una sola semilla?

**Comment by gpvidal** [comment]
Es una muy buena pregunta @KnowYourselves ! Y como siempre la respuesta es depende. Y depende (valga la redundancia) de cómo hayas configurado las relaciones.

Si una tabla no tiene relaciones con otras, entonces ahí sí tiene sentido un `down` (o como se llame el método que revierta una seed - en este caso) que borre todos los datos.

Pero en el curso de bases de datos deben (o deberían) haber visto, por ejemplo, los borrados en cascada. Siguiendo con el ejemplo de los usuarios y las ventas, si yo configuro que cuando se borre un usuario también se borren sus compras asociadas, entonces tiene sentido. Pero si borro todas las compras (por sí solas) también tiene sentido, ya que sería un estado en donde los usuarios están registrados solamente.

Tiene sentido para ti?

Saludos,
