### ISSUE TITLE
Error con la base de datos al iniciar aplicación

### ISSUE THREAD

**Issue by MGilB** [IIC2513-2020-1/syllabus#34]
Hola, tengo el mismo error que aparece en la issue #16, seguí todos los pasos, me puedo conectar a mi base de datos con el comando `psql -h localhost -U <user> -d <mydb>`, pero al momento de ejecutar `yarn dev` o `yarn start` me aparece el error

 `Unable to connect to the database: ConnectionError [SequelizeConnectionError]: password authentication failed for user "manuel"`

Tengo un archivo .env donde tengo los datos para la base de datos y agregue dotenv para usar las variables de entorno.

**Comment by iaacosta** [comment]
Hola @MGilB!

¿Configuraste tu código para que ejecutara `dotenv`? Si no se ejecuta, no asigna las variables de entorno y podría explicar el problema.

Saludos

**Comment by MGilB** [comment]
Si era eso gracias
