### ISSUE TITLE
No puedo acceder a localhost

### ISSUE THREAD

**Issue by ibaeza1** [IIC2513-2020-1/syllabus#35]
Hola,
Estaba viendo el video que subio el profe e hice todo lo que aparece y no me salio ningun error, pero no puedo entrar al localhost. me dice que fue rechazado.
Verifique y tengo todo bien instalado asi que no se que puede ser.
Gracias :)

**Comment by ibaeza1** [comment]
update: creo que es require el que no esta funcionando porque instale todo a mano y funciona lo que instalo pero no lo que hago require

**Comment by ibaeza1** [comment]
update: es algo con la base de datos.
Cuando pongo yarn dev en la carpeta me sale este error
Unable to connect to the database: ConnectionError [SequelizeConnectionError]
Estoy ocupando windows y no se bien como ocupar psql pero tampoco puedo ocupar ubuntu porque no me funciona :(.
La cosa es que igual me sale Compiled successfully pero no se conecta con la database. Que puede ser?

**Comment by lfuenzalida2** [comment]
Lo que pasa es que probablemente no lo tienes conectado a una base de datos, para hacerlo tienes que tener postgresql instalado y despues crear una nueva base de datos (con el comando `createdb:<nombre de la base de datos>`) por defecto dejará al creador de la base de datos como el usuario de la bd y la contraseña probablemente sea la misma que la de usuario (o por lo menos eso me paso a mi), pero siempre se puede cambiar o simplemente crear la bd desde un principio con tu contraseña.

[Aquí te dejo la documentacion](https://www.postgresql.org/docs/9.1/app-createdb.html) de `createdb`, te recomiendo mirarla antes de hacer cualquier cosa.

Para cambiar la contraseña debes entrar a psql y usar el comando `\password <nombre ususario>`, luego te va a pedir cambiar tu nueva contraseña.

Si quieres cambiar el usuario debes creat un neuvo usuario en la bd, esto se hace con la consulta `CREATE USER <nombre usuario> PASSWORD <contraseña>;`, esto va a crear un usuario con la contraseña que tu quieras, luego debes usar ese usuario, contraseña y bd en la conexion con tu app (en database.js), pero se recomienda que no coloques tus datos directamente ahí, sino que uses un controlador de variables de entorno, el profesor recomienda "env rc", pero yo no lo pude encontrar y use "dotenv", que es otro controlador el cual funciona muy bien y es facil de usar, [aquí te dejo el link](https://stackabuse.com/managing-environment-variables-in-node-js-with-dotenv/) de "dotenv".

Ojala te haya podido ayudar!

**Comment by ibaeza1** [comment]
Entonces en resumen:
Tengo que crear una base de datos nueva desde la shell de psql
Luego en mi app poner que esa sea la base de datos que voy a usar en las variables de entorno
Es eso? es que no entiendo bien como hacerlo porque tengo que siempre usar la shell de psql que es aparte de la powershell de windows
Gracias! :)

**Comment by ibaeza1** [comment]
Update: ahora me sale este error
Unable to connect to the database: ConnectionRefusedError [SequelizeConnectionRefusedError]: connect ECONNREFUSED 127.0.0.1:5432

Hice la base de datos y le di todos los permisos al usuario y todo pero no se que significa este error :(

**Comment by lfuenzalida2** [comment]
En el archivo database.js puede hacer 2 cosas, la primera es colocar los valores exactos de tu base de datos (por ejemplo el nombre de la bd es "pepito", colocar en DB_NAME = "pepito" y asi mismo con el DB_USERNAME y DB_PASSWORD. La segunda opción es usar variables de entorno, esto te va a permitir usar otro archivo (.env) para guardar las variables importantes y secretas, tales como DB_USERNAME y DB_PASSWORD, para asi evitar que cualquiera pueda hacer log in a la db y además instanciar las variables en el archivo "database.js", esto esta muy bien explicado en el link que deje antes, lo [vuelvo a dejar](https://stackabuse.com/managing-environment-variables-in-node-js-with-dotenv/).

Ahora, probablemente el problema que estas teniendo es porque el usuario y la contraseña no coinciden (estoy asumiendo por que si que es esto), para arreglar esto debes entrar al SQL Shell, esto se hace de muchas formas, una de ellas es por Putty (app que se usa en el ramo Base de Datos para trabajar con las bd) o con el comando psql, yo personalmente estoy usando Ubuntu porque tuve muchos problemas instalando todo lo necesario para el curso y en este SO se me hizo mucho mas fácil, por eso no puedo darte mas ayuda de como entrar al SQL  Shell en windows, pero ya estando dentro deberias de ser capaz de modificar los usuarios y contraseñas que pueden usar la BD creada, para eso puedes guiarte por la guia de como [hacer un usuario en PostgreSQL](https://www.postgresql.org/docs/9.3/app-createuser.html), como darle [atributos al usuario y cambiar su contraseña](https://www.postgresql.org/docs/9.1/sql-alterrole.html)

Ojala te haya servido!

**Comment by ibaeza1** [comment]
ahi pude!
Muuchas gracias :)

**Comment by gpvidal** [comment]
Hola @ibaeza1 @lfuenzalida2 ,

Sobre esto:

> En el archivo database.js puede hacer 2 cosas, la primera es colocar los valores exactos de tu base de datos (por ejemplo el nombre de la bd es "pepito", colocar en DB_NAME = "pepito" y asi mismo con el DB_USERNAME y DB_PASSWORD. La segunda opción es usar variables de entorno, esto te va a permitir usar otro archivo (.env) para guardar las variables importantes y secretas, tales como DB_USERNAME y DB_PASSWORD, para asi evitar que cualquiera pueda hacer log in a la db y además instanciar las variables en el archivo "database.js", esto esta muy bien explicado en el link que deje antes, lo vuelvo a dejar.

Ustedes pueden colocar los valores como string para probar, pero deberían haberlo con variables de entorno. Lo que **no pueden hacer por ningún motivo es hacer push a su repositorio de sus claves**. Esto es un error grave que compromete la seguridad del sistema donde están.

En este curso no solo hay que hacer las cosas, sino que hay que hacerlas bien :wink: 

Saludos,
