### ISSUE TITLE
Tipos de variables al instanciar un modelo

### ISSUE THREAD

**Issue by lfuenzalida2** [IIC2513-2020-1/syllabus#36]
Estuve buscando un buen rato y no pude encontrar un lugar en donde den mas información sobre los tipos de variables que existen en la instanciacion de un modelo.

Por ejemplo, `$ yo @iic2513/template:model ngo name:string,logo:string,email:string --create` tiene variables string, pero no dice nada de primary keys, int o de serial para las variables, busqué en [`sequelize-cli`](https://github.com/sequelize/cli) y en la página de [Sequelize](https://sequelize.org/master/manual/model-instances.html), pero no encontré nada. 

Hay algún otro lugar en donde haya mas información sobre la sintaxis?

**Comment by iaacosta** [comment]
Hola @lfuenzalida2!

¡Buena pregunta! El template no hace un chequeo de los tipos, asume que el que le estás asignando es válido. Si quieres, puedes probar con `yo @iic2513/template:model modeloEjemplo atributoEjemplo:ejemplo` y en tus archivos creados, deberían salir tipos de la forma `Sequelize.EJEMPLO`.

En este sentido, tienes la libertad de usar los tipos permitidos en la librería, puedes encontrar más información [aquí](https://sequelize.org/master/manual/model-basics.html#data-types). Ojo que hay algunos exclusivos para Postgres y otros que son exclusivos de otros tipos de bases de datos.

Saludos!

**Comment by gpvidal** [comment]
De hecho, "más cerca" y que está mencionado en el primer video del template:

https://github.com/IIC2513/generator-template/wiki/Generator-commands#create-a-model

Saludos,
