### ISSUE TITLE
Base de datos y cambio de branch

### ISSUE THREAD

**Issue by tpcantergiani** [IIC2513-2020-1/syllabus#37]
Hola, realize un CRUD en una branch de git y ahora hice otro en otra.
Al intentar entrar al index del segundo, me dice que la columna con el primer atributo no existe.
Tengo que cambiar algo en mi base de datos?
(Hice una migración).

**Comment by iaacosta** [comment]
Hola @tpcantergiani!

No entendí muy bien tu problema, ¿hubo un conflicto entre ramas o no tuviste problemas con eso?

Respecto a lo segundo, fíjate que la migración del modelo asociado al CRUD exista y que no haya alguna otra que modifica las columnas o elimine ese modelo.

Saludos!

**Comment by gpvidal** [comment]
Hola @tpcantergiani ,

Creo que va a depender de cual fue la *base branch* que ocupaste. Si ocupaste una *branch* como base que no tiene ese esa migración, entonces no te lo va a reconocer. La solución sería que hicieras un `git rebase` de la branch que necesitas que tenga el cambio a la otra donde está implementado.

Saludos,
