### ISSUE TITLE
ERROR: Please install mysql2 package manually

### ISSUE THREAD

**Issue by ibaeza1** [IIC2513-2020-1/syllabus#38]
Hola!
Al tratar de hacer la migracion sequelize db:migrate me sale este error:
ERROR: Please install mysql2 package manually
Lo instale y me sigue saliendo y no se que es.
ayuda :(
Gracias!

**Comment by iaacosta** [comment]
Hola @ibaeza1! 

Qué raro, puede depender de muchas cosas: 

1. ¿Tienes el `.sequelizerc` en la carpeta base de tu proyecto? Si lo tienes, debería ser idéntico a [este](https://github.com/IIC2513/generator-template/blob/dev/generators/app/templates/.sequelizerc)

2. ¿Tienes la variable de entorno `DB_DIALECT` definida? Si la tienes, no deberías, y si lo mantienes debería tener valor `postgres`.

3. ¿Tienes tu archivo `./src/config/database.js`? ¿Qué contiene? Debería ser como [este](https://github.com/IIC2513/generator-template/blob/dev/generators/app/templates/src/config/database.js) a menos que le hayan hecho un cambio en tu grupo.

**Comment by ibaeza1** [comment]
Si a todo jajaja
pero ahora me sale esto: 
ERROR: Access denied for user 'root'@'localhost' (using password: NO)
Eso me salio haciendo lo que el profe hizo en el video con el ejemplo my-university y el error anterior me salio cuando trate de crear mi propia app. 
No se que significa ninguno de los dos :(
La cosa es que cuando hago yo @iic2513/template:model y creo un modelo no se si tengo que hacer migrate porque me aparecen las migraciones y el modelo en la carpeta sin haber hecho migrate. 
No se en verdad estoy un poco perdida en el tema de migrate :(

**Comment by iaacosta** [comment]
Por partes,

> ERROR: Access denied for user 'root'@'localhost' (using password: NO)
Eso me salio haciendo lo que el profe hizo en el video con el ejemplo my-university y el error anterior me salio cuando trate de crear mi propia app. 
No se que significa ninguno de los dos :(

¿Qué comando exacto estás usando y en qué carpeta lo estás corriendo?

> La cosa es que cuando hago yo @iic2513/template:model y creo un modelo no se si tengo que hacer migrate porque me aparecen las migraciones y el modelo en la carpeta sin haber hecho migrate.

¡Esto es normal! Las migraciones se crean primero (que sería uno de los dos archivos que se generan con el comando que mencionas ahí) y luego se ejecutan para que actuen sobre tu base de datos. Es un proceso de dos pasos :blush:

**Comment by ibaeza1** [comment]
Ya para la primera parte
estoy corriendo sequelize db:migrate en my-university/node_modules/.bin

Y para la segunda
Entonces cuando creo el modelo se me crea el archivo en migratons y dsp le tengo que hacer db:migrate?

Sorry por tantas preguntas :( pero al profe le salio altiro entonces no se como arreglar estos errores porque no los mencionó
Gracias :)

**Comment by ibaeza1** [comment]
update: creo que ahi si pude :) 
![image](https://user-images.githubusercontent.com/37149485/79090810-e56c7980-7d18-11ea-8e9a-c0fd6e049fa2.png)
Asumo que eso significa que resulto jajaja

**Comment by iaacosta** [comment]
> Sorry por tantas preguntas :( pero al profe le salio altiro entonces no se como arreglar estos errores porque no los mencionó

No te preocupes, estamos para aclarar tus dudas :blush:

¡Qué bueno que te haya resultado! Avísame si se te da algún otro problema.
