### ISSUE TITLE
Problema con la creación de Tabla

### ISSUE THREAD

**Issue by fabarros** [IIC2513-2020-1/syllabus#39]
Hola! Estoy siguiendo la guía que subió el profesor y cuando intento acceder a localhost:3000/courses (en mi caso es localhost:3000/dietas) la consola me dice que "La relación 'dieta' no existe".
Cree la entidad dieta e hice la migración entonces no sé qué puede ser. 

Muchas gracias! Saludos.

**Comment by gpvidal** [comment]
Hola @fabarros ,

Aquí hay un ejemplo con todos los pasos a seguir:

https://github.com/IIC2513-2020-1/syllabus/wiki/Comenzando-el-desarrollo#creando-un-primer-modelo

Podrías haberte saltado uno.

Saludos,

**Comment by fabarros** [comment]
Seguí exactamente esos pasos :/ ahora cuando ejecuto `./node_modules/.bin/sequelize db:migrate` me dice que no hay migraciones pendientes.
Los archivos de model y migrations fueron creados cuando creé el modelo.

**Comment by fabarros** [comment]
Hice todo de nuevo desde cero y me sigue diciendo que la relación no existe. Quizás tengo un problema en el archivo `routes/dietas`, pero mi código está igual que el de la Wiki.

**Comment by ftrejoc** [comment]
Me pasa lo mismo

**Comment by gpvidal** [comment]
Hola @fabarros , @ftrejoc 

Por favor pueden darnos la siguiente información:

* Sistema Operativo
* Versión de Node
* Comandos y outputs de los comandos que ingresaron, en el orden que los ingresaron.

Saludos,

**Comment by fabarros** [comment]
Hola! Estoy usando Ubuntu 18.04, Node JS 12.16.
Ingresé los siguientes comandos (no recuerdo de memoria los outputs):
`yo @iic2513/template:model dieta name:string,type:string --create`
-Se crearon los dos archivos que aparecen en el tutorial
`./node_modules/.bin/sequelize db:migrate`
output:
```Loaded configuration file "src/config/database.js".
Using environment "development".
File: .gitkeep does not match pattern: /\.js$/
File: .gitkeep does not match pattern: /\.js$/
File: .gitkeep does not match pattern: /\.js$/
== 20200415023720-create-dieta: migrating =======
== 20200415023720-create-dieta: migrated (0.593s)
```

Luego seguí el tutorial para crear la seed con 
`yo @iic2513/template:seed add-dietas --create`

Y llené con algunos datos de prueba.
Finalmente cuando creo el router y completo el template de EJS, intento ingresar a `localhost:3000/dietas` y la consola me dice:

``` GET /dietas
Executing (default): SELECT "id", "name", "type", "createdAt", "updatedAt" FROM "dieta" AS "dieta";
  xxx GET /dietas 500 31ms -

  SequelizeDatabaseError: relation "dieta" does not exist
```

**Comment by gpvidal** [comment]
E hiciste, en el router, `ctx.orm.dieta...`? Probaste con el plural?

Qué string aparece como primer parámetro en el modelo de dieta en el método `sequelize.define`?

Qué string aparece como primer parámetro en la migración de dieta en el método `queryInterface.createTable`?

De todas formas, dado que todo está en inglés, recomiendo que usen ese lenguaje para programar.  En este caso, hay funciones internas (como transformar a plural) que se marean con el español.

Saludos,

**Comment by fabarros** [comment]
Si le pongo plural me dice que no está definido (no se puede encontrar la propiedad findAll de un undefined).
Esto es lo que tengo en mi routes/dietas
```
const KoaRouter = require('koa-router');

const router = new KoaRouter();

router.get('dietas', '/', async (ctx) => {
  const dietasList = await ctx.orm.dieta.findAll();
  await ctx.render('dietas/index', { dietasList });
});

module.exports = router;
```
El primer string es `sequelize.define('dieta',...`
En la migración dice `queryInterface.createTable('dietas',...`
Gracias! Saludos.

**Comment by gpvidal** [comment]
Ya, efectivamente es un problema con la pluralización de la palabra dieta (porque está en español).

Solución:

- (Recomendada) Cambiar el código a inglés

- En la migración cambiar `queryInterface.createTable('dietas',...` por `queryInterface.createTable('dieta',...`. Deshacer esa migración y volverla a correr.

Saludos,

**Comment by fabarros** [comment]
Voy probar, gracias profe!

**Comment by fabarros** [comment]
Funciona! Gracias por la ayuda :smile: Tengo otra pregunta dado que es preferible usar nombres en Ingles.
Cómo me recomienda cambiar de `dieta` a `diet`? Elimino el modelo ya creado? Cambio el nombre en todos los archivos?. Si es mejor eliminar, cómo lo hago con comandos?
Muchas gracias por todo! Saludos.

**Comment by gpvidal** [comment]
Excelente :tada: 

Quizás lo puedes cambiar por *diet plan* o solo plan, dependiendo de tu contexto.

Aquí tienes el comando para borrar un modelo:

https://github.com/IIC2513/generator-template/wiki/Generator-commands#delete-a-model

Saludos!
