### ISSUE TITLE
Repositorios grupales

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2513-2020-1/syllabus#4]
Hola! la próxima semana debemos estar subiendo a github la tarea a nuestros repositorios grupales.

Están creados ya? Dónde los podemos encontrar?

Gracias!

**Comment by gpvidal** [comment]
Hola @JJJGGGG ,

Debería haberte llegado una invitación, si no puedes escribirle a @sormazabal . Tal como lo mencionó en un aviso que envió.

Saludos!
