### ISSUE TITLE
Donde está .env?

### ISSUE THREAD

**Issue by Kitaps** [IIC2513-2020-1/syllabus#40]
Hola, 

o si no está, en que directorio hay que crearlo?

Que ya está agregado al .gitignore pero no lo encuentro.

Extra:
Hay que agregar `require('dotenv').config()` al comienzo de `database.js` ?
Que según tengo entendido el process.env se abre igual (?)

**Comment by iaacosta** [comment]
Hola @Kitaps!

Efectivamente tienes que crear tu propio `.env` (el gitignore lo ignora de hecho, por eso no está subido)

Sobre el extra, si, es la forma de configurarlo. El `process.env` existe antes de la configuración porque aparte de las variables en `.env`, hay otras variables de entorno ya configuradas en tu computador :smile: 

Saludos!

**Comment by Kitaps** [comment]
Ahh perfecto, muchas gracias

Y gracias por responder tan rápido.
