### ISSUE TITLE
Problemas al hacer db:migrate

### ISSUE THREAD

**Issue by mistico0121** [IIC2513-2020-1/syllabus#41]
Hola. 

Estoy intentando seguir el tutorial para correr my-university. Ya instalé Yarn, psql, Node.js 12.16, creé la base de datos, y sin embargo, al llegar a la parte de las instrucciones donde debo ejecutar el comando  `./node_modules/.bin/sequelize db:migrate` , me devuelve el siguiente error.

![image](https://user-images.githubusercontent.com/30903383/79408663-de887580-7f69-11ea-8243-eb5a18f0f516.png)

Que debo hacer? Ya he intentado varias soluciones de internet y no me han resultado. La database existe, y puedo ingresar a psql al ejecutar `psql`.

Saludos, y gracias de antemano

**Comment by gpvidal** [comment]
Hola @mistico0121 ,

Suena a que no están bien configuradas las variables de entorno, las tienes configuradas?

Saludos,

**Comment by mistico0121** [comment]
Probablemente sea eso, ya que no he configurado las variables de entorno. Voy a ver que hacer para configurarlas, y luego postearé como me fué. Saludos

**Comment by JJJGGGG** [comment]
Intenta require('dotenv').config() en config/database.js

**Comment by mistico0121** [comment]
Lo logré. Luego de seguir las instrucciones para crear un virtual environment de acá https://direnv.net/ con el nombre de las variables como sale en database.js, y de seguir las instrucciones de https://github.com/IIC2513-2020-1/syllabus/issues/35 para la creación de la base de datos, logré que `yarn start` funcionara, y abriera mi app en localhost:3000.

Perdón por la demora en responder, y muchas gracias. Saludos
