### ISSUE TITLE
Relaciones entre modelos

### ISSUE THREAD

**Issue by Kitaps** [IIC2513-2020-1/syllabus#42]
Hola, 

en el template, como se hacen las relaciones? Como por ejemplo belongs_to, has_one, has_many ?

De antemano muchas gracias

**Comment by Kitaps** [comment]
https://sequelize.readthedocs.io/en/latest/docs/associations/

Parece que esto responde a mi duda

**Comment by gpvidal** [comment]
Hola @Kitaps ,

Muy bien! Efectivamente ahí está la información.

Si te fijas en los archivos de tus modelos, existe un método `associate`. En el caso de `my-university` para el modelo de cursos es:

`course.associate = function associate() {...}`

Esa función recibe un parámetro que contiene las referencia a los otros modelos (tal como aparece en un comentario en esa parte). Por lo que se puede transformar en algo como:

`course.associate = function associate(models) {...}`

Y dentro de ese método definir las relaciones.

Saludos!

**Comment by Kitaps** [comment]
Muchas gracias

**Comment by Kitaps** [comment]
> Esa función recibe un parámetro que contiene las referencia a los otros modelos (tal como aparece en un comentario en esa parte). Por lo que se puede transformar en algo como:
> 
> `course.associate = function associate(models) {...}`
> 
> Y dentro de ese método definir las relaciones.

Una duda, si es que tengo mi carpeta de models
y dentro de esta tengo los archivos
`team.js` `player.js`

tendría que hacer 
```
player.associate = function associate(team){
player.belongsTo(team);}
```
o
```
player.associate = function associate(modles){
llegar de alguna forma a team?}

```
(me basé en el ejemplo de la pagina mencionada anteriormente, donde inicializaba al player y el team dentro del mismo archivo)

**Comment by gpvidal** [comment]
Hola @Kitaps !

Algo como lo segundo:

``` js
player.associate = function associate(models) {
  // Aquí tienes disponible models.player y models.team
}
```

Saludos,

**Comment by Kitaps** [comment]
Perfecto, muchas gracias
Y gracias por la rapida respuesta
