### ISSUE TITLE
La magia de la computacion (video crud)

### ISSUE THREAD

**Issue by ibaeza1** [IIC2513-2020-1/syllabus#44]
Hola profe,
En el video que subió  sobre como hacer un crud dice varias veces "Ahora usaremos la magia de la computación" y se le escribe codigo de la nada :O.
Eso es un copypaste de algo que ya tenía o es algo especial que hace?.
Perdon si es muy tonta la pregunta pero es mucho codigo que se demora mucho en escribir y si hubiera una manera automática de hacerlo seria bacan :)

**Comment by ibaeza1** [comment]
@gpvidal :)

**Comment by gpvidal** [comment]
Hola @ibaeza1 !

Ese código que se ve en el video es efectivamente un copy/paste. Ese video es muy largo! Porque la verdad es que son 3 clases condensadas en un video equivalente a un módulo de clases.

De todas formas, si necesitas sacar código "mágico" :slightly_smiling_face: puedes obtenerlo de acá: https://github.com/IIC2513-2020-1/my-university/pull/1/files . Ahí está el mismo código que se puede ver en el video :wink: 

Saludos!

**Comment by ibaeza1** [comment]
Gracias profe!
