### ISSUE TITLE
Duda Git Flow

### ISSUE THREAD

**Issue by simontoya** [IIC2513-2020-1/syllabus#45]
Hola!
He estado leyendo sobre git flow y ocupando este sistema con mi grupo. Pero me queda una duda en la guía https://nvie.com/posts/a-successful-git-branching-model/ sale que luego de hacer 
`git merge --no-ff`
Se debe borrar la rama con 
`git branch -d feature-branch`
Y luego realizar push desde la rama develop. Sin embargo al hacer `git branch -a` me sigue apareciendo remote/origin/feature-branch, entonces debo eliminar esa rama remota también ? En la guía no aparecía nada sobre eso.

Gracias!

**Comment by gpvidal** [comment]
Hola @simontoya ,

Según esa guía que mencionas, no veo en ningún caso que una *feature branch* sea pública (o se haga push a `origin`).

Lo que haces es que haces *pull* de `develop`, haces una *feature branch* local, trabajas en ella, haces *merge* a `develop`, borras la *feature branch* y luego hacer *push* de `develop` a `origin`.

No sé si quizás ustedes están haciendo un paso adicional?

Saludos,

**Comment by simontoya** [comment]
Perfecto,
Me equivoqué entonces ya que hice push desde la rama de feature. Ya hice el merge a la rama develop y ya está con todos los cambios bastaría solo con eliminar la rama remota? @gpvidal 

Solo para aclarar,
Habría que crear una rama trabajar sobre ella, hacer commit en esa rama si es necesario y despues hacer el merge y el push desde la rama develop y luego eliminar la rama.

**Comment by gpvidal** [comment]
> Me equivoqué entonces ya que hice push desde la rama de feature. Ya hice el merge a la rama develop y ya está con todos los cambios bastaría solo con eliminar la rama remota?

Sí, solo basta con borrarla :wink: 

> Habría que crear una rama trabajar sobre ella, hacer commit en esa rama si es necesario y despues hacer el merge y el push desde la rama develop y luego eliminar la rama.

En tu *feature branch* puedes hacer todos los commits que tu quieras, lo que no dice esa guía es que hagas *push* a `origin` de ella.

Saludos!

**Comment by simontoya** [comment]
Perfecto!
Gracias
