### ISSUE TITLE
Problemas al instalar paquetes

### ISSUE THREAD

**Issue by gpvidal** [IIC2513-2020-1/syllabus#46]
Hola, trate de instalar yo a través de yarn y después no me reconocía el comando yo, entonces seguí las recomendaciones de este issue pero sigue sin servir, tengo la versión 12.16 de node, me arroja este error
![Captura de Pantalla 2020-04-16 a la(s) 20 11 41](https://user-images.githubusercontent.com/48304636/79518276-adb64800-801e-11ea-9ef0-2b0969e557ad.png)

_Originally posted by @vicentesh in https://github.com/IIC2513-2020-1/syllabus/issues/17#issuecomment-614963140_

**Comment by gpvidal** [comment]
@vicentesh lo moví acá, para que no revivan issues cerradas

**Comment by gpvidal** [comment]
Creo que ya lo tienes instalado, el error es que ya existe :confused:

**Comment by vicentesh** [comment]
Es que al intentar utilizar yo @iic2513/template me dice que no reconoce el comando :(

**Comment by gpvidal** [comment]
y si haces solo `yo`?

**Comment by vicentesh** [comment]
me aparece esto igual command not found: yo

**Comment by gpvidal** [comment]
Creo que quizás , si lo instalaste con `yarn` y no te funcionó, deberías desintalarlo primero:

```sh
$ yarn global remove yo @iic2513/generator-template
```

Y luego instalarlo con npm:

```sh
$ npm -g install yo @iic2513/generator-template
```

Saludos,

**Comment by vicentesh** [comment]
Lo logre, tuve que desinstalar e instalar todo denuevo y resulto, perdón por las molestias y gracias 😄
