### ISSUE TITLE
TypeError: Expected "id" to be defined

### ISSUE THREAD

**Issue by andresplass** [IIC2513-2020-1/syllabus#47]
Holaa, cuando creo un nuevo objeto por alguna razon no se le esta asignando un id nuevo. Y cuando trato de correr en este caso localhost/offers me sale internal server error y en la terminal me sale TypeError: Expected "id" to be defined

El form y todo esta igual al video que subio el profe, funcionaba bien localhost/offers hasta que al codigo le agregué la funcion de editar y update. De hecho localhost/offers/new funciona, pero ya la lista de offers no me la muestra
Gracias! :)

@gpvidal :(

Update: al parecer en el form, al crear una nueva _offer_, no le esta dando un id, se queda con null, y ahí se cae la página.

"offer {
    dataValues: {
      id: null,
      rating: 5,
      description: '5',
      title: '5',
      user_id: 5,
      comments: '5',
      createdAt: 2020-04-17T02:08:25.425Z,
      updatedAt: 2020-04-17T02:08:25.425Z
    },
" esto me entrega al recibir la lista de _offers_ , y bueno otras _offers_ mas

**Comment by iaacosta** [comment]
Hola @andresplass!

En base a tu edit, ¿estás seguro que en la migración se específica que el `id` tiene `primaryKey: true`, `allowNull: false` y `autoIncrement: true`? Sería raro que con esas tres opciones bien puedas asignar IDs nulos.

Si lo anterior falla revisa si tu modelo no tiene definido el atributo `id` (no debería).

Saludos!

**Comment by camichavez** [comment]
Hola! tengo el mismo problema y en la migración sale que si tiene las condiciones de primaryKey y autoIncrement true y allowNull falsos. Además, para revisar que mi modelo tenga el atributo id se debería verificar también en la migración? 

Gracias!!

**Comment by iaacosta** [comment]
Si el modelo no tiene el atributo `id` definido está bien.

¿Cómo están haciendo el `modelo.create(/* ... */);` o el `modelo.update(/* ... */);` en sus rutas de POST y PATCH/PUT?

**Comment by camichavez** [comment]
Ambos están igual que el del profe hasta el punto que he visto del vídeo. Lo que si estoy yendo paso a paso con el vídeo así que hay lineas que no están idénticas al archivo final en el repositorio de my-university,
```
router.post('objects.create', '/', async (ctx) =>{ 
const object = ctx.orm.object.build(ctx.request.body);
      try {
        await object.save({ fields: ['name', 'description', 'quantity', 'price', 'condition', 'category'] });
        ctx.redirect(ctx.router.url('objects.list'));
  }....
```

y

```
router.patch('objects.update', '/:id', async (ctx) => {
 const object  = ctx.orm.object.findByPk(ctx.params.id);
  try {
    const { name, description, quantity, price, condition, category} = ctx.request.body;
    await object.update({ name, description, quantity, price, condition, category});
    ctx.redirect(ctx.router.url('objects.list'));
  } ...
```

Creo que a eso te referias o eso espero ajja perdón si no

**Comment by iaacosta** [comment]
Si! A eso me refería. Están bien. (**EDIT: no están bien, le falta un `await` al `findByPk`**)

Si consultas directamente en base de datos por esta tabla, ¿que te da de output? Esto comandos deberías ejecutar para ver que hay en BDD:

```
psql <nombreDeBaseDeDatos> -U <tuUsuarioPostgres>
SELECT * FROM <nombreTablaConProblema>;
```

`<nombreTablaConProblema>` debe ser el mismo que se indica en el modelo y en la migración.

**Comment by camichavez** [comment]
Si aparecen los id! 
![image](https://user-images.githubusercontent.com/37157327/79532840-59be5a00-8044-11ea-89ff-115b00a122e4.png)

**Comment by iaacosta** [comment]
Mala mia jajaja para verlo más claramente, mejor usar

`SELECT id, name FROM <nombreTablaConProblema>;`

Que creo que ese número abajo es otro atributo.

**Comment by camichavez** [comment]
Si era otro atributo  jaja aqui va
![image](https://user-images.githubusercontent.com/37157327/79533061-fd0f6f00-8044-11ea-8b95-a6d462002154.png)

**Comment by iaacosta** [comment]
Perfect, eso indica que es un problema de como se guardan los elementos en base de datos.

¿Como fueron creados estos elementos? ¿A partir de una seed o desde el CRUD? Se puede debuggear mejor desde ahí

**Comment by camichavez** [comment]
Todos fueron creados desde el CRUD! justo luego de crear un elemento pongo que me muestre el id y obvio sale vacío. Eso también está igual al _form del ejemplo

**Comment by iaacosta** [comment]
Si en `postgres` preguntas por el detalle de la tabla `objects` con 

```
\d+ objects;
```

¿Te salen detalles acerca del _not null_, _primary key_ y _auto increment_ en el atributo `id`? Lo de _auto increment_ debería salir como un valor en la columna `Default`

![Screenshot_20200417_011726](https://user-images.githubusercontent.com/14133074/79534702-495cae00-8049-11ea-8780-928b548741d0.png)

**Comment by nrrosenberg** [comment]
yo estoy teniendo el mismo error del TypeError: Expected "id" to be defined y tengo esa tabla exactamente igual a esa.

**Comment by camichavez** [comment]
![image](https://user-images.githubusercontent.com/37157327/79534981-1b2b9e00-804a-11ea-9f51-d9215c559bbf.png)
 
mm veo una diferencia en la columna de Nullable y default en el id

**Comment by iaacosta** [comment]
¡Ahí está el problema entonces!

Algo pasó con la migración que no procesó bien el atributo. Como te decía antes, asegurate que la migración de creación de la tabla tenga el `id` de esta forma, que es la por defecto cuando ejecutas `yo @iic2513/template:model ... --create`

![Screenshot_20200417_012826](https://user-images.githubusercontent.com/14133074/79535206-c6d4ee00-804a-11ea-8b63-c8f9eebe3a3b.png)

Después puedes volver a aplicar tus migraciones, y si no sigue funcionando, revisa el resto de las migraciones y asegúrate que ninguna esté borrando estas restricciones.

Para mas info acerca de que puedes hacer con `sequelize` en tu linea de comandos (hacer rollbacks de migraciones, dropear BDD, etc), revisa [este link](https://github.com/sequelize/cli)

**Comment by nrrosenberg** [comment]
yo sigo teniendo el mismo error y creo tener bien las migraciones.

**Comment by iaacosta** [comment]
Perdón @nrrosenberg, no vi tu comentario entre medio de la discusión con @Cschavez.

¿Verificaste todo lo de la issue? En tu caso, ¿qué tienes en la ruta `edit` que no te funciona? ¿cómo lees el `id` en la vista?

**Comment by nrrosenberg** [comment]
Si ya revise todo, la primera foto es mi edit y la segunda donde esta el router.
<img width="360" alt="Captura de Pantalla 2020-04-17 a la(s) 01 42 22" src="https://user-images.githubusercontent.com/42253078/79535930-c50c2a00-804c-11ea-959b-3e91570a8887.png">
<img width="536" alt="Captura de Pantalla 2020-04-17 a la(s) 01 41 46" src="https://user-images.githubusercontent.com/42253078/79535933-c6d5ed80-804c-11ea-8530-525433c614d5.png">

**Comment by nrrosenberg** [comment]
Al edit lo estoy llamando con `<th><a href="<%= editUserPath(user) %>">Edit</a></th>` desde la lista de mis users

**Comment by iaacosta** [comment]
@nrrosenberg ¡Te falta un `await` en tu `findByPk`! Debería ser:

`const user = await ctx.orm.user.findByPk(ctx.params.id);`

**Comment by nrrosenberg** [comment]
Ahi funciono! Muchas Gracias!!

**Comment by iaacosta** [comment]
@nrrosenberg de nada!

@Cschavez no me percaté antes pero a ti también te pasó, ojo con corregir eso también a parte de la migración!

**Comment by ibaeza1** [comment]
Update: Con andres pudimos arreglar el problema haciendo una nueva base de datos y haciendo los models denuevo. Nuestro problema es que hicimos seed dos veces entonces la segunda vez nos tiro ids nulos y de ahi en adelante todo salia nulo. 
Si nada les resulta prueben haciendo otra base de datos en la shell de psql y asignandosela al proyecto. Despues hagan el model denuevo pero sin seeds y partan de ahi.
Eso nos resulto a nosotros :)

**Comment by camichavez** [comment]
Hola!  Yo no cambie la base de datos pero eliminé y volví a crear el modelo y funcionó!! Graciaaaas a todos :)

**Comment by gpvidal** [comment]
Buena! Todos felices! Gracias @cho19 ! :wink:
