### ISSUE TITLE
TypeError: Expected "id" to be defined

### ISSUE THREAD

**Issue by nrrosenberg** [IIC2513-2020-1/syllabus#48]
Hola, estoy haciendo el user/edit, pero al apretar el boton de edit en la lista de todos mis users, me aparece internal server error, y TypeError: Expected "id" to be defined en la consola. Tengo las funciones exactamente iguales a las del video del profe.

**Comment by iaacosta** [comment]
Hola @nrrosenberg 

En la issue #47 estamos viendo lo mismo para que veas que puede ser por ahí (y obviamente seguir comentando si no te resulta)

Saludos
