### ISSUE TITLE
Estilo diagrama entidad relacion

### ISSUE THREAD

**Issue by Fenho** [IIC2513-2020-1/syllabus#5]
¿Hay un tipo de diagrama entidad relación que debamos usar? ¿O podemos usar el que queramos?
Ejemplo 1:
![er1](https://user-images.githubusercontent.com/32397663/77590794-5a445480-6ecd-11ea-86e9-efbe062bd040.png)
Ejemplo 2:
![er2](https://user-images.githubusercontent.com/32397663/77590866-7fd15e00-6ecd-11ea-9a62-574fa2ca632c.png)

**Comment by gpvidal** [comment]
Hola @Fenho !

Un diagrama ER es más como el segundo ejemplo que colocaste. Tu primer ejemplo solo muestra relaciones entre llaves y ni siquiera tiene la cardinalidad.

En el segundo ejemplo tienes muchas más información :wink: 

Saludos,

**Comment by Fenho** [comment]
Gracias!
