### ISSUE TITLE
Pasar parametros al layout

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2513-2020-1/syllabus#50]
Hola! Con mi compañero de grupo intentamos de muchas formas hacer un "nav" dinámico, que recibiera parámetros de las rutas. El problema es que no logramos pasarle los parametros al layout sin tener que pasarselos en cada llamado a una vista. Qué podemos hacer para pasarle parámetros a todas las vistas?

**Comment by iaacosta** [comment]
Hola @JJJGGGG!

Las vistas del template funcionan con los parámetros que les pasas en los `ctx.render` y también en todo lo que exista en el `ctx.state`. 

Dicho esto, una forma de aplicarlo es establecer un middleware antes de que se carguen todas tus rutas (en el `routes.js`) que asigne los links relevantes al state, para que de esta forma sean "globales" para las vistas.

Espero esto haya aclarado un poco mejor que puedes hacer! Si tienes más dudas, pregunta no más.

**Comment by domingo-valdes** [comment]
¿El middleware se debería configurar en app.js?

**Comment by iaacosta** [comment]
Hola!

No necesariamente. Por ejemplo, `routes.js` es el archivo donde conglomeras todas tus rutas y por lo tanto renders. Ese lugar también es válido para algún middleware que involucre todas las vistas.
