### ISSUE TITLE
freelancer.hasMany called with something that's not a subclass of Sequelize.Model

### ISSUE THREAD

**Issue by nrrosenberg** [IIC2513-2020-1/syllabus#51]
Hola, estoy teniendo el error `freelancer.hasMany called with something that's not a subclass of Sequelize.Model` al momento de hacer agregar los seeds. Esa es my funcion con la que estoy llamando al hasMany.
<img width="655" alt="Captura de Pantalla 2020-04-17 a la(s) 20 12 38" src="https://user-images.githubusercontent.com/42253078/79622970-cc344600-80e7-11ea-93a7-5991c7da99de.png">

**Comment by iaacosta** [comment]
Hola!

¿Tu archivo `src/models/service.js` existe? Asegurate que esté con minúscula.

Si no, puedes hacer un `console.log(models)` previo a ese `hasMany` para ver que tiene ese objeto, debería tener un atributo `service` que es un modelo de Sequelize.

Saludos!
