### ISSUE TITLE
Herencia en el proyecto

### ISSUE THREAD

**Issue by Fenho** [IIC2513-2020-1/syllabus#52]
Con mi grupo no pudimos encontrar en la documentación de sequilize como usar herencia. Apreciaríamos una ayudita.

**Comment by iaacosta** [comment]
Hola!

Lamentablemente no tienen implementación para las herencias en Postgres :cry: (más info de la discusión en [este link](https://github.com/sequelize/sequelize/issues/1243)).

Alternativas que yo conozco:
- Aglomerar todas las entidades en una y usar algún atributo que te permita diferenciar entre una u otra, dejando los atributos que no le correspondan a algún tipo en `null`. 

  Por ejemplo, si tienes un `User` y un `Admin` y solo el user tiene un RUT, puedes hacer un solo modelo `User`, con las columnas que ambos comparten y dos adicionales: `rut` y `role`, donde `role` es `admin` o `user` y `rut` sería `null` para toda instancia que tenga rol `admin`
- Usar un modelo para cada una de las entidades que heredan, aunque sea repetitivo. 

  Ojo con esto eso si, pues si tienes un `User` y un `Admin` que comparten algún recurso (`Post`, por ejemplo) y hay una relación 1:N entre ellos, `Post` podría necesitar dos columnas para la referencia: `userId` y `adminId` si es que usas llaves foraneas.

¡Avísame si no se entiende algo!

**Comment by Fenho** [comment]
Muchas gracias!
