### ISSUE TITLE
Render vs redirect

### ISSUE THREAD

**Issue by daleal** [IIC2513-2020-1/syllabus#53]
Hola!
Cuando en un controlador decido que una _request_ es inválida, lo que hago es cargar un _flash_ mesage y mostrarle al usuario una vista con el _flash_ message. Mi problema es que no sé si luego de cargar el _flash_ message debería hacer un **render** o un **redirect** de la página que quiero mostrar al usuario. Conceptualmente entiendo la diferencia y pensaría que debería redireccionar, pero me gustaría saber si hay alguna forma correcta o no de hacerlo y **por qué** esa es la forma correcta (no pude encontrar nada muy relevante buscando [en los textos sagrados](https://www.google.com/)).

**Comment by iaacosta** [comment]
Hola!

Te daré la respuesta desde mi propio conocimiento adquirido en el ramo y otros medios, pero igual prefiero que @gpvidal confirme o refute esto.

Definamos en rigor que pasa en cada caso:
- Una redirección es una respuesta del servidor con status code 3xx y con información relevante de *dónde ir*. Tu navegador toma esta información y hace la redirección, que eventualmente termina en status code 200.
- Un render es una respuesta del servidor con status code 200 y la información para hacer el render, por lo que en rigor el navegador asume que está todo bien y sólo carga la información que se respondió.

Dicho esto, la redirección debería ser más correcta, porque usa los códigos para informar alguna incidencia que no le permitió tener un código 200 inmediatamente. 

Como el flash message viaja en los headers y no en el body, es posible hacer que persista entre requests e informe el error luego de la redirección.

**Comment by gpvidal** [comment]
Hola @daleal ,

A qué te refieres con que el request es inválido? Que el usuario ingresa mal los parámetros o tiene parámetros perdidos?

Saludos,

**Comment by daleal** [comment]
Que el usuario ingresa mal los parámetros

**Comment by gpvidal** [comment]
Sorry! Había olvidado responder esto :stuck_out_tongue: 

Tal como dice @cho19 va a depender del objetivo. Tomando como ejemplo `my-university`:

* Al agregar un curso, y si este es exitoso, se **redirige** a la lista de cursos - otra vista (Usando redirect)
* Si comete un error, entonces se hace render de esa misma vista con los datos pre llenados (Usando render)

Por eso, va a depender justamente de lo que quieras hacer :wink: 

Saludos,

**Comment by daleal** [comment]
Muchas gracias!
