### ISSUE TITLE
Duda funcionamiento middlewares

### ISSUE THREAD

**Issue by ncasassas** [IIC2513-2020-1/syllabus#55]
Hola, tengo un problema con la lectura de  middlewares en mi CRUD, lo que pasa es lo siguiente:
Tengo en un modulo definidas mis rutas correspondientes a un CRUD donde definí tal como en el ejemplo de my-university una función load para poder cargar los ctx.state a mis demás rutas que lo necesitaran. Esta función la tengo al principio de mi modulo, justo después de haber creado el router.
El problema es que por motivos que desconozco hay algunas funciones que me llaman a esa función load aunque no lo tenga definido así.

Por ejemplo tengo una ruta de la siguiente forma router.get('valor.valor2', '/:id/valor', load, async (ctx) ...  .
que efectivamente como se lo indico me llama a la función load y me entrega el resultado que quiero. El problema esta que tengo una función del tipo router.get('valor.valor2', '/:id/valor', async (ctx) ... , que no logro hacer correr bien ya que por algun motivo se ejecuta el load de alguna de las funciones donde si le pido que lo use.

Ya probé hacer console.log de todo y también eliminando las funciones que usan load el resultado si es el que quiero para esta ultima ruta, pero pierdo las otras. Revise el modulo muchas veces y no estoy llamando load sin querer tampoco.

Muchas gracias de antemano!

Se me fue mencionar que es segunda vez que me pasa esto y la primera lo solucione (ya que encontré la ruta que se llamaba "sola" ) colocando la ruta al final de mi código. Cosa que para esta segunda vez no ha funcionado.

**Comment by iaacosta** [comment]
Hola!

Si creas otro `middleware` aparte, ¿pasa lo mismo?

Saludos!

**Comment by gpvidal** [comment]
Hola @nko205 ,

Por lo que leí tienes dos rutas, en un mismo router, que resuelven a `GET '/:id/valor'`, es así? Esto no debería pasar en un mismo router porque justamente no sabe cuál debería resolver y comienza a jugar el orden del código.

Saludos,
