### ISSUE TITLE
Problema con heroku

### ISSUE THREAD

**Issue by ibaeza1** [IIC2513-2020-1/syllabus#56]
Hola!
Hice el deploy a heroku y me dice que si salio bien y que se subio pero cuando trato de entrar a la pagina me sale que no se puede ver. 
Estos son los logs
2020-04-19T04:11:19.727846+00:00 app[web.1]: npm ERR! errno 1
2020-04-19T04:11:19.729410+00:00 app[web.1]: npm ERR! grupo-niburu@1.0.0 start: `node index.js`
2020-04-19T04:11:19.729567+00:00 app[web.1]: npm ERR! Exit status 1
2020-04-19T04:11:19.729763+00:00 app[web.1]: npm ERR! 
2020-04-19T04:11:19.729899+00:00 app[web.1]: npm ERR! Failed at the grupo-niburu@1.0.0 start script.
2020-04-19T04:11:19.730038+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-04-19T04:11:19.738953+00:00 app[web.1]: npm WARN Local package.json exists, but node_modules missing, did you mean to install?
2020-04-19T04:11:19.739782+00:00 app[web.1]: 
2020-04-19T04:11:19.740086+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2020-04-19T04:11:19.740315+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2020-04-19T04_11_19_730Z-debug.log

Tengo el package.json bien y tengo el 
Script{
Start: node index.js }, bien tambien 
En verdad esta todo bien no se cual es el problema por que dice que el deploy si funciono. 
Ayuda :(
Gracias!

**Comment by ibaeza1** [comment]
UPDATE: no habia hecho 'yarn heroku-postbuild' pero cuando lo hago me sale esto:
![image](https://user-images.githubusercontent.com/37149485/79700658-548c2580-8265-11ea-93da-3af774e0cb5f.png)
Y si lo tengo definido en mi archivo .env como NODE_ENV=development.

**Comment by iaacosta** [comment]
Hola!

¿Pudiste solucionarlo? Lo primero se ve raro. ¿Tienes una estructura no convencional para Heroku? (todos tus archivos en el `root` del repositorio)

Lo segundo, ¿estás usando la terminal de Windows? Si es así, tiene que ver con el comando `build-assets` que no puede parsear variables de entorno _inline_

Saludos!

**Comment by ibaeza1** [comment]
Hola!
Para lo primero tengo todos los archivos en el lugar correcto creo yo.
Y para lo segundo si estoy usando windows. Y cuando hago build-assets desde el cmd me dice que rm -rf no esta definido y cuando lo corro del bash de git me sale que NODE_ENV no se reconoce.

**Comment by iaacosta** [comment]
Vale!

Para lo primero, me puse a revisar su repositorio y tienen un `package.json` aparte del que les da el template para el proyecto. Eso es lo que está provocando tu error, porque Heroku utiliza ese para tratar de hacer `start` a su página y no está correctamente configurado para correr los archivos del template.

Aquí tienen dos opciones:
1. Utilizar `git subtree push --prefix <tuCarpetaDelTemplate> heroku master`, que en términos muy coloquiales crea un nuevo "subrepositorio virtual" que pushea a Heroku solo lo necesario del template.
2. Seguir [este tutorial](https://www.youtube.com/watch?v=-j5gM2lCDus), que usa un `buildpack` distinto al por defecto de Heroku para NodeJS y te permite agregar una variable de entorno para indicar donde está realmente tu aplicación

Con esto, no deberías necesitar ejecutar a mano lo del `heroku-postbuild`, porque eso lo hace Heroku si todo se sube bien

**EDIT**: te puede pasar que Heroku alegue que las historias de git no coinciden, en dicho caso te conviene crear otra app no más dado que están configurando como subirla :blush:

Avísame si lo logras!
Saludos

**Comment by gpvidal** [comment]
Para complementar lo de @cho19 , él publicó algunas configuraciones que hay que hacer aquí: https://github.com/IIC2513-2020-1/syllabus/issues/49#issuecomment-615026198

Si haces push directamente desde el template debería funcionar, una vez configurado lo que dice @cho19 :wink: 

Saludos,

**Comment by gpvidal** [comment]
Ah! Algo que me faltó: Ustedes no deberían correr el script `heroku-postbuild`, esto lo hace Heroku.

**Comment by ibaeza1** [comment]
UPDATE: hice la opcion 1 que me dio @cho19 creando otra app con heroku create y ahora me sale esto.
![image](https://user-images.githubusercontent.com/37149485/79765852-2b1ada80-82f5-11ea-9286-c1547a1f29d6.png)
Esto significa que tengo que eliminarlos de mi carpeta de la app o de la root?? por que tengo uno extra como dijo tambien @cho19 
Lo otro es que como estoy usando windows el comando rm no me funciona. Cual es el equivalente a rm en windows?
Gracias!

**Comment by gpvidal** [comment]
No, el error es porque están haciendo `yarn install` y `npm install`, por eso tienes los dos archivos: `yarn.lock` y `package-lock.json`. Deberías borrar este último y trabajar con `yarn` para el proyecto.

Saludos,

**Comment by iaacosta** [comment]
Respecto a lo del `rm`, la consola nativa de Windows no lo tiene.

Te recomiendo usar `git bash` para no estar siempre mezclando comandos entre consolas, pero la equivalencia es `del` (y `deltree` para remover una carpeta con sus elementos, que ya es distinto a lo que hace `bash` con `rm -r` 😅 )

Saludos!

**Comment by ibaeza1** [comment]
UPDATE: ya hice todo lo anterior y todo y ahora me sale esto
![image](https://user-images.githubusercontent.com/37149485/79768445-cd888d00-82f8-11ea-8071-7c32268f7005.png)
dice undefined asi que en verdad ahora ya no se que hacer jajaja.
hice yarn install denuevo porque me faltaban algunas dependencias y elimine el package-lock.json pero en verdad ya no se me ocurre que mas puede ser :(

**Comment by gpvidal** [comment]
Mira acá lo que escribió @cho19 : https://github.com/IIC2513-2020-1/syllabus/issues/49#issuecomment-615026198

**Comment by ibaeza1** [comment]
Lo logre! muchas gracias :)

**Comment by gpvidal** [comment]
Excelente! :clap: Gracias @cho19 :wink:
