### ISSUE TITLE
Simbología javascript en html

### ISSUE THREAD

**Issue by Kitaps** [IIC2513-2020-1/syllabus#57]
Hola, 

no me queda muy claro las diferencias entre partir una linea de javascript en html de las siguientes formas:
`<%`
`<%-`
`<%=`

De antemano muchas gracias

**Comment by JorgeBdelaT** [comment]
Hola! Aquí te dejo una pequeña explicación:

- ```<%```: permite poner código que no será mostrado en la vista.
- ```<%-```: permite incluir código que si será visible en la vista pero elimina los tags html (unescaped html). Por ejemplo si  pones ```<%- <p>Hello world!</p> %>``` solo mostrará ```Hello world!```.
- ```<%=```: permite incluir código que si será visible en la vista pero no elimina los tags html (escaped html), por lo que si haces ```<%= <p>Hello world!</p> %>```  mostrará ```<p>Hello world!</p> ``` en pantalla.

Igual te invito a revisar la documentación de [ejs](https://ejs.co/) y si aun tienes dudas puedes volver a escribir por acá. 

Saludos y ánimo con la entrega!

edit: te dejo dos fotos mas explicativas igual
![WhatsApp Image 2020-04-19 at 23 31 54](https://user-images.githubusercontent.com/37000540/79711705-8ff31800-8296-11ea-8595-720d1d10ff1f.jpeg)
![WhatsApp Image 2020-04-19 at 23 32 08](https://user-images.githubusercontent.com/37000540/79711712-95e8f900-8296-11ea-8e13-f0e270d89908.jpeg)

**Comment by Kitaps** [comment]
Muchas gracias
