### ISSUE TITLE
Validaciones a nivel de base de datos

### ISSUE THREAD

**Issue by bedefrunner** [IIC2513-2020-1/syllabus#58]
Hola!

Sé cómo hacer validaciones a nivel de modelos en Sequelize, pero no a nivel de base de datos. Según yo se definen en los archivos de migraciones, pero hay algunas que no he logrado hacer funcionar, como la validación de largo mínimo de una columna de tipo string. 

Si quiero que la columna `password` de la tabla `users` tenga mínimo 6 letras y máximo 999, la siguiente restriccion en el archivo de migración NO funciona, es decir, a nivel de base de datos esta restricción no existe:

`password: {
      type: Sequelize.STRING,
      allowNull: false,
      len: [6, 999],
    },`

Cómo puedo hacer funcionar esta restricción a nivel de base de datos?

**Comment by ibaeza1** [comment]
Hola! una pregunta :) como hiciste lo de la validacion con sequelize?? me ayudaria caleta. Gracias!

**Comment by JorgeBdelaT** [comment]
@ibaeza1 hola! 

Para agregar validaciones a nivel de modelo puedes definir tus propias validaciones a la hora de definir los atributos de este. Te dejo un ejemplo para que quede más claro:
```js
const user = sequelize.define('user', {
    username: {
      type: DataTypes.STRING,      
      validate: {        
        customValidation(value) {
          if (value.length < 6) {
            throw new Error('El nombre de usuario debe tener al menos 6 caracteres');
          }
        },
      },
    }
});
```
También te dejo la documentación de [sequelize](https://sequelize.org/master/manual/validations-and-constraints.html) donde hay un par de ejemplos.

@bedefrunner con respecto a tu duda estuve buscando y tampoco encontre como validar a nivel de base de datos. Sin embargo, si haces las validaciones respectivas a nivel de modelos no debería ocurrir que atributos inválidos pasen a la base de datos.  Igual prefiero que @gpvidal  confirme o refute esto :smile:

**Comment by gpvidal** [comment]
Hola a todos!

La pregunta es.... se puede validar a nivel de base de datos? :eyes:  ajá!

Cuando ustedes crean una tabla en postgreSQL (y en bases de datos relacionales con SQL) escriben algo como esto:

```sql
CREATE TABLE users (
  id SERIAL,
  age INT,
  first_name VARCHAR(255),
  last_name VARCHAR(255),
  email TEXT
);
```

Justamente el tema es en los `VARCHAR(255)`! Lo que está entre paréntesis es el largo máximo que puede tener esa columna para ese tipo de dato! Entonces...

Pueden hacerlo a nivel de bases de datos? No lo pueden hacer :wink: 

Saludos,

**Comment by gpvidal** [comment]
Solo una precisión, no pueden hacerlo al momento de crear una tabla base de datos. Probablemente podrían crear un procedimiento almacenado para validar esto.

Saludos,
