### ISSUE TITLE
Diccionarios en Javascript

### ISSUE THREAD

**Issue by Kitaps** [IIC2513-2020-1/syllabus#6]
Hola una duda chica. 

En los ejercicios de Node, sale que las respuestas deberían darnos como: 
![image](https://user-images.githubusercontent.com/10112117/77591534-e7d47400-6ece-11ea-8f84-6601ab41eb08.png)
pero a mi me dan así:
![image](https://user-images.githubusercontent.com/10112117/77591561-f91d8080-6ece-11ea-8ddc-bc2fbd67a3a6.png)

Como pueden ver las comillas son distintas como también que las llaves no llevan comillas y en el otro si. Como influye esto en un programa?

De antemano muchas gracias, 
Patrick

**Comment by gpvidal** [comment]
Hola @Kitaps ,

Puede haber pasado que en alguna actualización del sistema, haya cambiado la forma en como se imprimen los objetos en consola. Pero de todas formas si lograste la misma información entonces está bien :smile: 

Saludos,

**Comment by Kitaps** [comment]
Gracias por la rápida respuesta
