### ISSUE TITLE
Problema login Heroku 

### ISSUE THREAD

**Issue by andresplass** [IIC2513-2020-1/syllabus#60]
Hola! mi compañera hizo el deploy de heroku. Ya hice el pull del master y al conectarme con su cuenta (heroku login) eso funciona.

Pero luego, **heroku git:remote -a nuestrapp**, 
»   Error: You do not have access to the app freelancer.
 »
 »   Error ID: forbidden
O también con **git push heroku master**,
fatal: 'heroku' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by iaacosta** [comment]
Hola!

¿Estás ocupando tus propias credenciales o las de tu compañera? Si son las tuyas, necesitas que ella te de acceso desde su panel de Heroku para poder acceder a las funcionalidades en consola.

Saludos!

**Comment by andresplass** [comment]
Sii! estoy usando las de ella

**Comment by iaacosta** [comment]
¿Y que output te da `heroku apps`?

**Comment by gpvidal** [comment]
Por si acaso, aquí también enseñamos buenas prácticas y **no deberían compartir sus contraseñas con nadie!!**

Saludos,

**Comment by andresplass** [comment]
@cho19 
Me entrega esto, (una fue de ensayo para probar un deploy con la wiki del repositorio)
$ **heroku apps**
=== aplass@uc.cl Apps
damp-garden-32844
lit-plains-45353
morning-meadow-19341
whispering-fortress-24087

@gpvidal esta bien profe! el problema es que ya llevamos dos dias jeje medidas drásticas

**Comment by iaacosta** [comment]
@andresplass estás logeado en tu cuenta y no en la de tu compañera (a menos que ella use una con tu mail jajaja) por eso te dice que la app no existe.

Para que estén alineados con las buenas prácticas, te recomiendo seguir [este tutorial](https://devcenter.heroku.com/articles/collaborating) para que tu compañera te agregue a la app como colaborador, de ahí podrías agregarla a tu `remote` de `git` y pushear directamente a Heroku también.

**Comment by andresplass** [comment]
Ya muchas gracias!
nos funcionó con lo que respondieron en la issue 56,
con **git subtree push --prefix freelancer heroku master**
 **heroku git:remote -a freelancer** y luego añadir como colaborador a mano en la pagina de Heroku.
