### ISSUE TITLE
Problema al correr yarn start

### ISSUE THREAD

**Issue by niguzman** [IIC2513-2020-1/syllabus#61]
Hola, no logro correr yarn start
me arroja el sgte error :C 
![image](https://user-images.githubusercontent.com/48304981/79700202-19d4be00-8262-11ea-84fb-2853f28e84c0.png)

**Comment by iaacosta** [comment]
Hola!

Asumo que corriste `yarn install` (si no, correlo). 

Si sigue sin funcionar, ¿cuales son los contenidos de tu `package.json`?

Saludos!

**Comment by felipegarcia98** [comment]
@cho19 yo tengo problemas con cualquier comando del yarn :c 
Todas las opciones me tiran este error

![imagen](https://user-images.githubusercontent.com/42228743/79716428-a7390200-82a4-11ea-962a-a3521c09474d.png)


Como dato, la version  de yarn es 
![imagen](https://user-images.githubusercontent.com/42228743/79716478-c899ee00-82a4-11ea-83ac-7d10565d7163.png)
y lo descargue con ``` sudo apt install yarn```

**Comment by iaacosta** [comment]
Hola @felipegarcia98!

¿Seguiste las instrucciones previas de [este link](https://classic.yarnpkg.com/en/docs/install#debian-stable)? En Ubuntu, por defecto ese comando instala otro paquete `yarn` que no es el que usamos :sweat_smile: 

Saludos!

**Comment by felipegarcia98** [comment]
@cho19 , tengo Ubuntu 18.04
No te voy a mentir, no se si hice el primer cuadrito (mi recuerdo dice que si), pero hice el segundo y funciono (desde eso me funciona el ```yarn --version```)
![imagen](https://user-images.githubusercontent.com/42228743/79717243-0bf55c00-82a7-11ea-9774-ea6de2a095ed.png)
pero creo que si me salte lo del path setup :yum: :sweat_smile: 

Por otro lado, hice lo de [la respuesta del profe](https://github.com/IIC2513-2020-1/syllabus/issues/17#issuecomment-608147713) y parece que me funciono (no me tiro error)

![imagen](https://user-images.githubusercontent.com/42228743/79717616-267c0500-82a8-11ea-9a41-1cbc0d791986.png)

**Comment by iaacosta** [comment]
Buenísimo!

Ojo eso si con la ejecución de `yo`, trata de que no sea con `sudo` porque sino todos los archivos que este cree estarán bloqueados y solo se podrán modificar con `sudo`. Ve bien que puedas ejecutar `yo` sin sudo y deberías estar bien

En todo caso, si prefieres seguir lo que te dice la página de `yarn`, debes hacer `sudo apt purge yarn` y nuevamente lo que te indica el primer y segundo cuadro.

Avísame si te nace algún problema!
Saludos

**Comment by felipegarcia98** [comment]
![imagen](https://user-images.githubusercontent.com/42228743/79718470-241aaa80-82aa-11ea-8713-88960c89c400.png)
![imagen](https://user-images.githubusercontent.com/42228743/79718488-2bda4f00-82aa-11ea-90d0-81a85862500b.png)
Todo apunta a que funciono, pero debo hacer lo del yarn u.u
Altiro hago lo que me dices

**Comment by iaacosta** [comment]
No es necesario lo que te dije! Era solo por si querías tomar ese camino o tenías otras complicaciones.

Si te corre `yo` sin `sudo`, no deberías de tener problemas :smile:

**Comment by felipegarcia98** [comment]
Alguna recomendacion para configurar el postgres?



PD: Igual lo intente y no cambio nada, incluso cuando hice lo de borrar cmdtest
![imagen](https://user-images.githubusercontent.com/42228743/79718997-7dcfa480-82ab-11ea-9902-3cfab9808d5c.png)

**Comment by felipegarcia98** [comment]
Habia que hacer algo parecido a lo que dijiste para arreglar el yarn. En [este link](https://github.com/Joystream/helpdesk/issues/16#issuecomment-484966596) lo señalan. 

Basicamente era un gran undo y redo
``` 
sudo apt remove cmdtest
sudo apt remove yarn
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && sudo apt-get install yarn```

**Comment by gpvidal** [comment]
Por lo que puedo ver, lo que hiciste fue actualizarlo de versión instalándolo desde otro repositorio. Es por esto que les recomendamos hacer la instalación con `nvm`. La instalación es bastante menos "dolorosa".

Saludos,

**Comment by niguzman** [comment]
Hola,
al final logré solucionar ese problema reinstalando pg de manera global pero sigo con otro problema.
por alguna razón postgres está accediendo a otro nombre de usuario cuando lo hago correr y me tira error. No le logrado averiguar como cambiarlo


![image](https://user-images.githubusercontent.com/48304981/79812880-20d5fc00-8348-11ea-9286-506eb5773f87.png)

![image](https://user-images.githubusercontent.com/48304981/79812915-38ad8000-8348-11ea-840f-46b2f0b1444d.png)

En vez de intentarlo con niguzman, lo está haciendo con Nico y creo que eso está generando el error

**Comment by gpvidal** [comment]
Configuraste las variables de entorno?

**Comment by niguzman** [comment]
Así las tengo
![image](https://user-images.githubusercontent.com/48304981/80024378-f3569300-84ac-11ea-8de3-a35e55423637.png)

**Comment by gpvidal** [comment]
No veo que tengas las variables de entorno de la aplicación configuradas. Revisa el archivo `src/config/database.js`.

Saludos,

**Comment by niguzman** [comment]
Creo que no estoy logrando configurar las variables de entorno, tengo windows 10 :C

**Comment by gpvidal** [comment]
Qué has intentado?
