### ISSUE TITLE
Como debuggear?

### ISSUE THREAD

**Issue by Calomi** [IIC2513-2020-1/syllabus#62]
cual/cuales son las mejores formas de debuggear con este template?
puse `console.log` por todos lados y nada (en los html con <%%> <%= %> <%- %> (tampoco sé bien la diferencia xd), también dentro de las funciones), `debugger` tampoco funciona.
EDIT: acabo de cachar q se imprimen en la consola donde hice el yarn dev, pero quiero que se impriman en la consola del navegador, por facilidad de visibilidad.

y hay alguna forma de que los errores se impriman también en la consola del navegador?

**Comment by domingo-valdes** [comment]
Si haces console.log en una vista deberías poder ver la salida en la consola del navegador

**Comment by iaacosta** [comment]
Hola @Calomi 

Hay varias formas. 

Por ejemplo, puedes crear un `<script></script>` al comienzo de tu código que sea de la forma:

```
<script>
  console.log('<%= loQueQuierasImprimir %>');
</script>
```

Otra forma es simplemente usar `<%= %>` para embedir lo que quieras imprimir en tú código. Por ejemplo, si quiero saber si `num` es `0` o `1`, puedo escribir `<%= num %>` en alguna parte de la vista y debería "imprimirse". Lo ideal es que veas tu consola del terminal, pero hay _workarounds_ para verlo en el navegador. 

Ojo eso si que si te pones a imprimir objetos, probablemente todos saldrán como `[object Object]`, para mejorar esto te conviene usar la función `JSON.stringify(objeto);` para que se imprima como un JSON

Espero que te sirva!
Saludos

**Comment by Calomi** [comment]
gracias!
```
<script>
  console.log('<%= loQueQuierasImprimir %>');
</script>
```
si me imprimió en la consola del navegador, las otras formas no lo hacian y tambien me funcionó:

```
<script>
  debugger;
</script>
```
😄
