### ISSUE TITLE
Heroku model build failed ./styles/index.scss

### ISSUE THREAD

**Issue by naazocar** [IIC2513-2020-1/syllabus#63]
Hola! Estoy intentando hacer deploy de la app a Heroku pero me sale el siguiente error y no he logrado solucionarlo:

<img width="833" alt="Screen Shot 2020-04-20 at 1 20 33 AM" src="https://user-images.githubusercontent.com/30675195/79716751-ace31780-82a5-11ea-9abd-6fd5aa665c0b.png">

**Comment by iaacosta** [comment]
Hola @naazocar 

¿Que contiene tu archivo `index.scss`?

**Comment by naazocar** [comment]
Hola @cho19 , mi archivo tiene lo siguiente:
<img width="328" alt="Screen Shot 2020-04-20 at 1 31 08 AM" src="https://user-images.githubusercontent.com/30675195/79717100-aacd8880-82a6-11ea-8406-911bc8c96f78.png">

**Comment by iaacosta** [comment]
¿Estás seguro que el naming de todos los archivos está bien? ¿Les carga localmente?

El error de Heroku hace referencia a que no se pudo compilar el SCSS, pero se usa la misma configuración tanto local como para el deploy. ¡Revisen bien su terminal a ver si lanza algún error!

**Comment by naazocar** [comment]
Acabo de correr localmente todas las views para ver si salía alguno, pero no :(
<img width="1048" alt="Screen Shot 2020-04-20 at 1 46 34 AM" src="https://user-images.githubusercontent.com/30675195/79717906-e10c0780-82a8-11ea-9784-d81e745ab670.png">
<img width="1070" alt="Screen Shot 2020-04-20 at 1 46 47 AM" src="https://user-images.githubusercontent.com/30675195/79717911-e2d5cb00-82a8-11ea-9b0c-cbaf91371436.png">

**Comment by iaacosta** [comment]
¿Están subidos tus cambios en tu repo? 

Que me metí a revisar para tratar de emularlo, y por lo menos en master me sale que `NavBar/style` está fallando porque el archivo real está con mayúscula (`NavBar/Style.scss`).

**Comment by naazocar** [comment]
Permiso para acriminarme contra la persona que le puso mal esa S? Jajaja muchas gracias, no sé por qué local corría bien. 

Lo que sí ahora en heroku no aparece la imagen que teníamos como background :( Intentaré solucionarlo, si no lo logro abro otra issue :)

**Comment by iaacosta** [comment]
Jajajaja no hay problema, asumo que tiene que ver con OSX que lo omite magicamente y Ubuntu no, solo tengan ojo con eso en el futuro.

Para lo de la imágen, asegurate que la estés importando en `assets` y que ocupen la función correspondiente para usar el `asset` (si esto es Chino, mejor abre otra issue)
