### ISSUE TITLE
GET /route 404

### ISSUE THREAD

**Issue by vicentesh** [IIC2513-2020-1/syllabus#64]
Hola, de un momento a otro dejo de verse la lista de mi objeto chat y no se que puede estar pasando, el error que me lanza es el 
![image](https://user-images.githubusercontent.com/48304636/79775157-d7fb5480-8301-11ea-8a4e-9286eb3a7505.png)
, en routes.js tengo esto:
![image](https://user-images.githubusercontent.com/48304636/79775339-17c23c00-8302-11ea-87e9-9bf92529c746.png)
lo que debería seguir las instrucciones de routes/chats.js, en donde tengo esto:
![image](https://user-images.githubusercontent.com/48304636/79775483-4f30e880-8302-11ea-818c-f71c14d808fd.png)
lo que a su vez me llevaría a la vista, tengo la base de datos bien y la relación está creada con el seed ya migrado, no se que puede estar pasando :(

**Comment by gpvidal** [comment]
Hola @vicentesh ,

Tu archivo `routes/chats.js` esta mal, ahí debería estar la implementación del router (según lo otro que enviaste).

Saludos,

**Comment by vicentesh** [comment]
se mando otra imagen, en routes/chats.js tengo esto:
![image](https://user-images.githubusercontent.com/48304636/79777123-c9626c80-8304-11ea-86d8-4471cdb308cd.png)

**Comment by gpvidal** [comment]
Tienes, al final de `routes/chats.js` la línea `module.exports = router;`?

**Comment by vicentesh** [comment]
Sisi, no se alcanzo a ver pero está

**Comment by gpvidal** [comment]
y solo te falla esa ruta o todo el router?

**Comment by vicentesh** [comment]
falla el router completo, antes funcionaban también las derivadas de este, vi en internet que quizás se podría solucionar con npm Install, pero eso re-instalaria todos los módulos y no se si después git creería que son 4000 cambios y pueda afectar al momento de hacer push

**Comment by gpvidal** [comment]
Probaste reiniciando el servidor? Si estás ocupando `yarn start` o `yarn dev` prueba parando el servidor y luego ejecutarlo nuevamente.

**Comment by vicentesh** [comment]
funcionó, al final intenté reinstalando los módulos y resultó, muchas gracias :)
