### ISSUE TITLE
Imagen Background no carga en Heroku

### ISSUE THREAD

**Issue by Michelmagna** [IIC2513-2020-1/syllabus#65]
Hola!
Tenemos el problema de que al cargar nuestra aplicación a Heroku, la imagen de fondo de nuestra pagina no se está subiendo. Primero pensamos que era por tamaño, arreglamos esto y sigue sin subir. Es curioso porque otra imagen (el logo) se sube sin problema alguno. Si nos pudiesen orientar se los agradeceríamos.

Gracias!

**Comment by gpvidal** [comment]
Hola @Michelmagna ,

Cómo están referenciando a la imagen?

Saludos,

**Comment by Michelmagna** [comment]
Asi la llamo profesor @gpvidal.

<img width="452" alt="Captura de Pantalla 2020-04-20 a la(s) 2 10 11 p  m" src="https://user-images.githubusercontent.com/40605397/79784827-d6855880-8310-11ea-968e-cf7e75646e4b.png">
He buscado y algunos recomiendan llamarla de otras maneras, sin embargo no me terminan funcionando en localhost.

**Comment by gpvidal** [comment]
Y si pones el path relativo?

**Comment by gpvidal** [comment]
Por ejemplo, para cargar la imagen `logo.png` en un archivo (por ejemplo) `courses.scss` tendrías que hacer algo de este estilo:

```css
td {
  background-image: url('../images/logo.png');
}
```

**Comment by Michelmagna** [comment]
Gracias profesor @gpvidal, ahi me funciono perfecto. Tenia mal definida la referencia.

Saludos.

**Comment by gpvidal** [comment]
Súper! :smile:
