### ISSUE TITLE
Comandos de sequelize en Windows

### ISSUE THREAD

**Issue by FelipeBodelon** [IIC2513-2020-1/syllabus#66]
Hola, 

Por algún motivo decidí desarrollar la aplicación en Windows, y por el momento no he tenido problemas, uso dotenv  para el manejo de variables de entorno sin problemas. 

Mi principal dificultad fue a la hora de realizar migraciones o utilizar otros comandos de sequelize. Descubrí que con `yarn sequelize <comando de sequelize>` se realizan las operaciones deseadas. En la wiki recomiendan `./node_modules/.bin/sequelize <comando de sequelize>`, lo que no puedo hacer en Windows. No he tenido problemas y solo quería saber si es correcto utilizar sequelize de esta forma.

**Comment by gpvidal** [comment]
Hola @FelipeBodelon ,

Sí puedes usar esa forma, de hecho me gusta más :slightly_smiling_face: Así que la agregaremos a la wiki :wink: 

Saludos,

**Comment by FelipeBodelon** [comment]
Buenísimo! En ese caso recomiendo también actualizar la wiki del repo del template que tiene la mayoría de los comandos de sequalize.

**Comment by gpvidal** [comment]
Actualizado!
