### ISSUE TITLE
Solicitud Plazo Extra

### ISSUE THREAD

**Issue by felipegarcia98** [IIC2513-2020-1/syllabus#67]
Profesores, Ayudantes (@gpvidal , @sormazabal ), me gustaría solicitarle algunas horas más para la entrega ya que sería de mucha ayuda para nosotros en estas semanas de hartos trabajos y responsabilidades académicas u.u

Cordialmente <3

**Comment by gpvidal** [comment]
Hola @felipegarcia98 ,

Ninguna posibilidad de plazo extra.

Saludos,
