### ISSUE TITLE
Deploy en Heroku no encuentra assets

### ISSUE THREAD

**Issue by tpcantergiani** [IIC2513-2020-1/syllabus#69]
Hola:
Al subir a heroku nuestra app, se muestra la pagina, pero sin el diseno.
![image](https://user-images.githubusercontent.com/44327650/79800232-d9d90e00-8329-11ea-95ba-240e6afda07b.png)
El problema esta en que no encuentra el path a los assets

El layout de la pagina lo tenemos definido de la siguiente maner:
![image](https://user-images.githubusercontent.com/44327650/79800364-13117e00-832a-11ea-81f2-9a24dd298c5e.png)

**Comment by gpvidal** [comment]
Probaste eliminando el espacio en el nombre que tiene el archivo?

Saludos,

**Comment by tpcantergiani** [comment]
EL nombre tiene ese espacio, de igual forma lo intentaremos!

**Comment by Sforrego** [comment]
Mismo Problema!
creo que es porque estamos usando scss pero no se como arreglarlo.

**Comment by gpvidal** [comment]
Borraron algo del template? Hicieron algún cambio en él? Les funciona en local?

**Comment by tpcantergiani** [comment]
Era por lo que había dicho, el espacio en el nombre botaba todo!

**Comment by gpvidal** [comment]
Buena! :tada:

**Comment by gpvidal** [comment]
A los servidores no les gusta mucho los espacios :stuck_out_tongue:
