### ISSUE TITLE
Casos de uso

### ISSUE THREAD

**Issue by nrrosenberg** [IIC2513-2020-1/syllabus#7]
Hola, cuando el enunciado 1 habla de casos de uso, se refiere al diagrama con actores y sus interacciones (como el de la foto) o a los relatos de usuario y funcionalidades principales de cada actor con la aplicación?
![image](https://user-images.githubusercontent.com/42253078/77600950-2591c680-6ee8-11ea-9ce9-197f833cda7b.png)

**Comment by gpvidal** [comment]
Hola @nrrosenberg !

Nos referimos a casos de uso, que son una tabla que indica ciertas características de acciones dentro de tu aplicación (muy en general).

En el siguiente sitio tienes un ejemplo, bajo el título "¿Como especificar Casos de Uso?":

https://sites.google.com/site/alfonsoperezr/investigacion/estructuracin-y-especificacin-de-casos-de-uos

No es necesario que especifiquen tanto detalle, por ejemplo los Requerimientos trazados, Puntos de inclusión o Puntos de extensión que aparecen en el ejemplo. Lo importante es que al leer sus casos de uso quede claro quién lo realiza, el flujo, qué es lo necesario y qué pasa al realizar ese caso de uso. Ideal si pueden agregar más información, siempre es bienvenida y permitirá tener mayor claridad de cómo piensan su proyecto.

Saludos,
Gabriel

**Comment by nrrosenberg** [comment]
Dale, gracias
