### ISSUE TITLE
No se puede deployar al Heroku | Error parsing url: undefined

### ISSUE THREAD

**Issue by nfbalbontin** [IIC2513-2020-1/syllabus#70]
Hola! Qué tal? 
Como grupo estamos desde las 16:00 intentando deployar al heroku nuestra app. Al comienzo teníamos el problema de que poseíamos dos archivos de package.json (package.json y package-lock.json), uno que corría con yarn y otro con npm. Luego de editar esto, nos sigue apareciendo el siguiente error: 
<img width="895" alt="Captura de Pantalla 2020-04-20 a la(s) 18 26 41" src="https://user-images.githubusercontent.com/26261777/79805747-d303c880-8334-11ea-9fbe-71e912c277dc.png">
En que nos dice que no está definida el "url". Luego de revisar la documentación de heroku, verificar que las versiones de yarn y node calcen y otras series de medidas, no logramos resolver este error. 
Agradecería ayuda :)

**Comment by gpvidal** [comment]
Hola @nfbalbontin ,

Mira este post de @cho19 , aquí se aborda ese error.

Saludos,

**Comment by nfbalbontin** [comment]
Hola @gpvidal ,
Gracias por la referencia! Pero no encontré ninguna issue hecha por @cho19 😅. Lo busqué con su etiqueta dentro de las issues cerradas y no me apareció. Seguro que es él el autor? 
Saludos!

**Comment by gpvidal** [comment]
Mala mía, acá va: https://github.com/IIC2513-2020-1/syllabus/issues/49#issuecomment-615026198

**Comment by nfbalbontin** [comment]
Muchas gracias!
