### ISSUE TITLE
Problema Heroku

### ISSUE THREAD

**Issue by vicentesh** [IIC2513-2020-1/syllabus#71]
Hola, al intentar hacer deploy de nuestra app a Heroku nos aparece el siguiente error:

![image](https://user-images.githubusercontent.com/48304636/79934303-39b1e080-8420-11ea-95dd-ffce88ef0365.png)

Intentamos resolverlo con el ayudante pero aún no nos funciona, alguien sabe por qué puede estar pasando.

Gracias 🍍

**Comment by gpvidal** [comment]
Probaron con `git push -f heroku master`?

**Comment by vicentesh** [comment]
Aparece el mismo error 😢 , lo que hemos intentado hacer hasta el momento es:

- Intentar desde otro computador.

- En el archivo database.js agregar un const pg = requiere('pg') y luego en producción agregar dialectModule: pg

- Revisar el archivo .sequelizerc

- instalar Postgres como add-on antes de hacer deploy de la app

- Correr heroku logs --tails y tratar de solucionar los errores que nos aparecían en el dashboard

- Revisar las migraciones

- Revisar el .gitignore

Todo los cambios que hemos hecho los hemos revertido para que no nos influyan en otros cambios.

**Comment by gpvidal** [comment]
Hola @vicentesh ,

Revisé el repositorio de tu grupo y me encontré con esto en el archivo `package.json`:

```
"heroku-postbuild": "yarn run build-assets && sequelize init && sequelize db:migrate"
```

Por qué hay un `sequelize init` ahí? En el template no está, así que supongo que ustedes lo agregaron y ese podría ser el error que tienen.

Saludos,

**Comment by vicentesh** [comment]
yap, sacamos la linea pero nos volvió a lanzar el error por el que la pusimos 😭 que no sabemos por que se produce, este: 
![image](https://user-images.githubusercontent.com/48304636/80041865-8dc5cf00-84cb-11ea-8e26-ba7094f31b91.png)
Gracias por la paciencia 🙏

**Comment by gpvidal** [comment]
Ya caché cual es el problema :tada: 

Mira el repositorio de my-university: https://github.com/IIC2513-2020-1/my-university

Si ves tu repositorio, le faltan todos los archivos que parten con un punto, entre ellos el `.sequelizerc`. Estos archivos son ocultos en linux, y probablemente ustedes copiaron el contenido de una carpeta a otra y, como esos archivos están ocultos, no se incluyeron al copiar.

Tienen que tener esos archivos en su repositorio, basta con que los copien.

Saludos,

**Comment by vicentesh** [comment]
Eso eraaaa 😄 muchas muchas gracias, ya resultó!!

**Comment by gpvidal** [comment]
Buena! :tada:
