### ISSUE TITLE
Webpack y configuración del template.

### ISSUE THREAD

**Issue by KnowYourselves** [IIC2513-2020-1/syllabus#72]
Hola!

Tengo una duda de como funciona webpack al momento de configurar el server. Entiendo a grandes rasgos lo que hace webpack, pero no entiendo como modificarlo.

En especifico, estamos haciendo un frontend en react ocupando el template como backend, por lo cual no es necesario que en este hayan assets en este último. Por tema de limpieza quiero eliminar esta carpeta, pero no logro hacerlo sin que me de error webpack. Cómo se podria hacer?

De antemano, muchas gracias!

**Comment by gpvidal** [comment]
Hola @KnowYourselves ,

Tienes que procurar que los archivos marcados como `entrypoint` en Webpack no importen los archivos que no quieres incluir. Una vez con eso puedes eliminarlos.

Saludos,

**Comment by KnowYourselves** [comment]
Hola profesor!

Al final investigando me di cuenta que para mi caso de uso especifico no es necesario el uso de webpack en el backend, asi que simplemente lo removí.

Muchas gracias!!
