### ISSUE TITLE
Heroku no lee nuestro scss

### ISSUE THREAD

**Issue by behrmann97** [IIC2513-2020-1/syllabus#73]
Hola, nuestra aplicación se ve bien al correrla localmente, pero al subirla a heroku, si bien todas las funcionalidades se mantienen, todo lo que es scss no se aplica. ¿Alguna idea de qué puede estar ocurriendo?

**Comment by gpvidal** [comment]
Hola @behrmann97 ,

Intentaste revisar como aparece acá https://github.com/IIC2513-2020-1/syllabus/issues/63#issuecomment-616319924 ?

Saludos,

**Comment by behrmann97** [comment]
Hola! Pasa que localmente nos corre bien, por lo que no creo que sea un problema de ese tipo. Aparte, solo hice push a heroku una vez que estaba listo, por lo que sería raro que tuviera algun error que no tuvieramos localmente.

Saludos!

**Comment by gpvidal** [comment]
No creo o no es un problema de ese tipo?

Tu problema es porque en el layout borraron estas lineas (aparecen en `my-university`):

```
<% if (env !== 'development') { %>
      <link rel="stylesheet" href="<%= assetPath('app.css') %>">
    <% } %>
```

y tienen esto:

```
<link rel = "stylesheet"
   type = "text/css"
   href = "app.css" />
  </head>
```

Por eso les funciona solo en `development`, pero no en `production`.

Saludos!

**Comment by behrmann97** [comment]
Era eso! No se en qué momento lo borramos, muchas gracias y perdón por la pérdida de tiempo 😄
