### ISSUE TITLE
Cookie sin datos del usuario

### ISSUE THREAD

**Issue by Kitaps** [IIC2513-2020-1/syllabus#74]
Hola, 

en el vídeo de session el profesor Gabriel menciona que no debemos usar user.id para guardar en la cookie, ya que eso es data del usuario. Que tenemos que usar información generada por nosotros.

La razón es seguridad? O por que? 
Por otro lado a que se refieren con información generada por nosotros?

**Comment by iaacosta** [comment]
Hola @Kitaps!

Las sesiones que implementó el profesor en clase las manejas en tus rutas como un objeto de JavaScript (`ctx.session`), pero si te fijas en tus cookies dentro del navegador, estás son un string (`koa:sess`). 

Para hacer esta conversión (_encode_ y _decode_), el paquete `koa-session` (del template) implementa unos [helpers](https://github.com/koajs/session/blob/master/lib/util.js). En código simple, se hace esto:

```js
const decode = (string) => {
  const body = Buffer.from(string, 'base64').toString('utf8');
  return JSON.parse(body);
};

const encode = (obj) => {
  const stringBody = JSON.stringify(obj);
  return Buffer.from(stringBody).toString('base64');
};
```

Imagínate el cliente tuviese conocimientos de aplicaciones web, podría:

1. Acceder a sus cookies
2. Tomar el valor del hash y aplicarle la función `decode`
3. Modificar el objeto en JavaScript con un `id` distinto
4. Aplicar la función `encode` al objeto modificado
5. Asignarla a sus cookies y enviar una request a una ruta privada

El resultado sería que el servidor piensa que es un usuario `id` distinto al de él (en este caso, el que inyectó). En otras palabras, te hackeó.

Para evitar esto, no puedes guardar ningún tipo de información en el hash que le envías al usuario, para no darle la posibilidad de modificarlo, de aquí el concepto de "información generada por nosotros".

Al final, la idea es que tu generes algo que identifique a la sesión, pero que solo sea eso: un identificador sin información del usuario. Luego, en tu servidor, ese identificador lo asocias a un usuario y puedes obtener su información. El cómo asociarlo queda a tu criterio 😃 

¡Avísame si te quedan dudas!

**Comment by Kitaps** [comment]
Gracias !!

**Comment by gpvidal** [comment]
Hola!

Solo quiero hacer una pequeña aclaración con respecto a este tema.

Lo que plantea @cho19  sobre cómo se transmiten las cookies es completamente cierto, de hecho es la forma para que no esté visible a simple vista (transformar a base64).

Sin embargo, nuestro *template* es serio :laughing: , y las cookies que envía van firmadas! y son seguras ¿Qué quiere decir eso? Que adicionalmente a lo que @cho19 menciona, también se envía la firma de la cookie generada ¿Con qué datos se genera? Con los datos de la cookie más unas llaves ¿Dónde están esas llaves? Si miras el archivo `src/app.js` hay una declaración para `app.keys = [...]` y esas son las llaves que se utilizan para firmar las cookies.

¿Qué pasa si trato de modificar una cookie? Como voy a modificar el valor, la voy a invalidar porque la firma fue hecha con la información anterior y, al ser recibida por el servidor, va a saber que es inválida.

¿Es malo que la cookie incluya el id de usuario? La verdad es que no, ya que al igual que otro es un identificador. Aunque siempre, si se va a incluir en un medio como este, este tiene que ser seguro para evitar justamente lo que @cho19 menciona.

¿Entonces por qué no puedo agregarla a la cookie para esta entrega? Principalmente por:
* Que lleguen y peguen código que no entienden, y que no saben las implicancias que tiene.
* Que se enfrenten al peor escenario (cookie no encriptada)

Eso principalmente, espero haber sido lo suficientemente claro con respecto a este tema :stuck_out_tongue: 

Nuestro template es posible usarlo en producción, al menos las cosas que dependen de él son seguras. La seguridad de lo que ustedes hagan depende de ustedes. Es por esto que en otros cursos ocupan nuestro querido template :smile: 

Saludos,

PD: En la versión `1.1.0` del template, que lancé este fin de semana, la cookie cambio de `koa:sess` a `koa.sess` :wink:
