### ISSUE TITLE
Link entre scss y view

### ISSUE THREAD

**Issue by Fenho** [IIC2513-2020-1/syllabus#76]
Hola, no entiendo cómo y en dónde se relacionan scss con su respectiva view. Seguí los videos del drive y me funciona, pero no entiendo por qué, y qué debería hacer si quisiera relacionar un scss con un view que tienen nombres distintos.

**Comment by gpvidal** [comment]
Hola @Fenho ,

Buena pregunta! Lo que hace el template es lo mismo que hacen otros frameworks: toman todos los archivos de estilo y finalmente genera uno con todos ellos.

Que existan múltiples archivos es solo para un orden del código en cuanto a que son estilos de una cierta entidad, que esté separado y sea fácil de navegar.

Esta es la forma en que, por ejemplo, Ruby on Rails opera.

Saludos,

**Comment by Fenho** [comment]
Muchas gracias!
