### ISSUE TITLE
Permisos de usuario

### ISSUE THREAD

**Issue by ibaeza1** [IIC2513-2020-1/syllabus#77]
Hola!
Estamos viendo con mi grupo como hacer los permisos de usuario (que un usuario no pueda editar los comentarios de otro, que un usuario no pueda eliminar cosas, etc), pero no entiendo bien como hacerlo.
Quizas es porque no nos manejamos bien con koa y no entendemos tanto como funciona.
Buscamos en google cosas pero en verdad estamos un poco perdidos y no sabemos bien que buscar.
Si nos pudieran guiar mas o menos en como hacerlo o alguna pagina donde podamos encontrar como se hace nos ayudaria mucho!
Gracias :)

**Comment by gpvidal** [comment]
Hola @ibaeza1 !

Si te fijas en `my-university`, particularmente en esta parte https://github.com/IIC2513-2020-1/my-university/blob/master/src/routes/courses.js#L8 definimos un función que se llama antes de algunas rutas, como por ejemplo esta: https://github.com/IIC2513-2020-1/my-university/blob/master/src/routes/courses.js#L46

En esa función cargamos el curso que se quiere ver/editar/borrar pero... que pasa si creo una que chequee los permisos de usuario? :stuck_out_tongue: 

Saludos!
