### ISSUE TITLE
Error sequelize

### ISSUE THREAD

**Issue by domingo-valdes** [IIC2513-2020-1/syllabus#78]
¿Por qué el siguiente código no me permite cambiar el atributo en la BD? El código es una adptación de lo que hay en uno de mis archivos de routes. Llevo mucho tiempo intentando solucionarlo:
```js
  let user = ctx.orm.user.build(ctx.request.body);

  // Ver si ya existe el usuario en la base de datos, para crearlo si es que todavía no está inscrito
  const userMatches = await ctx.orm.user.findAll({
    where: {
      email: user.email,
    },
  });
  if (userMatches.length > 0) {
    user = userMatches[0];
  } else {
    await user.save({ fields: [ 'email'] });
  }

  await user.set('atributo', 'valor atributo');
  await user.save();
```

**Comment by gpvidal** [comment]
Hola @domingo-valdes ,

Cual es el error?

Saludos,

**Comment by domingo-valdes** [comment]
No es que arroje un código de error, si no que cuando posteriormente hago `ctx.orm.user.findOne({ where: { atributo: 'valor atributo' } })`, retorna undefined. Según entiendo, no se está guardando en la BD y no entiendo por qué

**Comment by gpvidal** [comment]
Tengo un par de comentarios:

* No tendrá que ver algo con alguna validación o algo?
* Por qué no reemplazas las operaciones `set` y `save` por un `update` 

Saludos,

**Comment by domingo-valdes** [comment]
No hay validaciones y tampoco funciona con update :/

**Comment by gpvidal** [comment]
Espera! no hice una pregunta importante... Dónde estás colocando este código?

**Comment by domingo-valdes** [comment]
Al interior de un router

**Comment by domingo-valdes** [comment]
Lo logré solucionar! El problema era por la manera en que cree la columna "atributo", ya que hice una migración con addColumn como aparece aquí [https://stackoverflow.com/questions/49890998/how-to-add-column-in-sequelize-existing-model](url). Todavía no entiendo bien por qué, pero eso no funcionaba bien y para solucionarlo borré la migración y agregué "atributo" directamente entre los campos del modelo user.
Gracias de todas maneras profe @gpvidal !!!

**Comment by gpvidal** [comment]
Buena! Creo que me faltaba un poco más de info pero que bueno que lo solucionaste :wink: 

Saludos!
