### ISSUE TITLE
Acceder a métodos de asociaciones en routes.js

### ISSUE THREAD

**Issue by FloValdes** [IIC2513-2020-1/syllabus#79]
Hola, quiero crear una función que me diga las notificaciones pendientes de un usuario y mostrarlas en la nav bar que está en layout.html.ejs. 
Para eso pensé en hacer una función en routes.js, que llama a la función "getNotifications()" del CurrentUser, pero me sale este error:

`TypeError: currentUserFunction(...).getNotifications is not a function`

currentUser es efectivamente un user y puedo acceder a sus atributos, pero es como si las asociaciones aún no existieran o algo así? No tengo problemas en acceder a getNotifications() en otras partes del código, como en las rutas.

Gracias!

**Comment by gpvidal** [comment]
Hola @FloValdes ,

En las vistas **no puedes llamar a métodos asíncronos**, por lo que tienes que obtenerlos en la ruta antes.

Te recomiendo revisar esta página de `sequelize`, bajo el título "Fetching all associated elements" :wink:

https://sequelize.org/master/manual/eager-loading.html

Saludos,

**Comment by FloValdes** [comment]
Gracias!
