### ISSUE TITLE
Calendario de pruebas y programa

### ISSUE THREAD

**Issue by JJJGGGG** [IIC2513-2020-1/syllabus#8]
Hola, estuve buscando en CANVAS y SIDING y no encuentro ninguno de esos dos elementos. Hay algún programa del curso, y cuando están planificadas las pruebas?

**Comment by gpvidal** [comment]
Hola @JJJGGGG ,

Puedes ver el readme de este repositorio (la página que ves al entrar al syllabus), ahí puedes encontrar la información que buscas :wink: 

Saludos!
