### ISSUE TITLE
Importar y exportar modulo

### ISSUE THREAD

**Issue by andresplass** [IIC2513-2020-1/syllabus#80]
Hola, para hacer el perfil de un usuario, queriamos juntar lo que anteriormente eran las rutas de "ofertas" y "comentarios" en una sola ruta. Lo que ocurre es que en esta nueva ruta, las funciones por ejemplo "NewOfferPath" o "editOfferPath" o "NewCommentPath" o "editCommentPath", cada una esta definida para las rutas de Offers o Comments, pero no de esta nueva que seria el perfil, por lo que nos tira error de que esas funciones no estan definidas.
Existe una manera de importar éstas funciones en otra "view"? Intentamos usar lo de "require" o "module.exports" pero no lo logramos o no entendimos muy bien la escritura. 

De esto tambien nos preguntamos, al final de cada /routes/xxx.js , está "module.exports = router;" ésto no deberia permitir poder usar todo lo definido en ese archivo, en otro?

Muchas gracias

**Comment by gpvidal** [comment]
Hola @andresplass ,

> De esto tambien nos preguntamos, al final de cada /routes/xxx.js , está "module.exports = router;" ésto no deberia permitir poder usar todo lo definido en ese archivo, en otro?

Claro, esto les permitiría importar un router en otro y y usar sus middlewares, por ejemplo:

```js
const comments = require('./comments');
// [...]

router.use('/offers/:id/comments', comments.routes())

module.exports = router;
```

Probablemente tengas que clonar el router de comments (si lo vas a reutilizar), ya que hay un issue abierto en `koa-router` con respecto a rutas anidadas y aún está abierto. Te lo dejo como referencia en caso de que tengas errores.

https://github.com/ZijianHe/koa-router/issues/244

Saludos!

**Comment by andresplass** [comment]
Hola Profe gracias por la respuesta! la verdad lo probamos y no funcionó, nuestra pregunta va a esto.
Tenemos una view, llamada **myself** (donde se ve todo lo de el usuario conectado)
en esta esta la funcion:

```javascript
router.get('myself.list', '/', async (ctx) => {
  console.log(jobs.jobsList)
await ctx.render('myself/index', {
});});
```
Con la que simplemente cargamos el index de la pagina. Ahora bien, las **/routes** de por ejemplo, **Jobs** y **Comentarios** tienen sus propios get al igual que como lo definió usted en el tutorial del tipo:

```javascript
async function loadjob(ctx, next) {
  ctx.state.job = await ctx.orm.job.findByPk(ctx.params.id);
  return next();
}
router.get('jobs.list', '/', async (ctx) => {
  const jobsList = await ctx.orm.job.findAll();
  console.log(jobsList);
  await ctx.render('jobs/index', {
    jobsList,
    newjobPath: ctx.router.url('jobs.new'),
    editjobPath: (job) => ctx.router.url('jobs.edit', { id: job.id }),
    deletejobPath: (job) => ctx.router.url('jobs.delete', { id: job.id }),
  });
});
```
Ahora en **myself** queremos ocupar **newjobPath**, **editjobPath**, ... pero nos tira error que no esta definido. La solucion que se nos ocurre es efectivamente re definir en el get de myself, de nuevo newjobPath, editjobPath, basicamente **copy paste**, pero parece poco eficiente, 

Esa es la pregunta, queremos usar esas funciones en myself sin tener que copiar todo dentro del get (solución facil, pero seria tener codigo dos veces)

**Comment by gpvidal** [comment]
> Esa es la pregunta, queremos usar esas funciones en myself sin tener que copiar todo dentro del get (solución facil, pero seria tener codigo dos veces)

Súper buena esta intuición.

Pero tengo una duda, no quieren mover nada de las rutas? Es solo poder generar los links?

Saludos,

**Comment by andresplass** [comment]
Lo que queremos es que en una pagina nos muestre y permita usar las tablas de tres modelos distintos (es decir, que nos deje ver JobsList, CommentList, ...) pero en esta nueva pagina nos dice que esas listas no están definidas. (Ni sus funciones asociadas a su ruta (Edit/New/Delete)

Cada route por separado funciona bien, y nos permite ver las tres tablas por separado.

**Comment by gpvidal** [comment]
Pero no basta por ejemplo que hagan, para el list:

```js
const jobsList = await ctx.orm.job.findAll();
const commentsList = await ctx.orm.comment.findAll();
```

Ojo que el `ctx.router` tiene el router global, por lo que pueden obtener todas las rutas desde ahí. Entonces pueden llamar a `ctx.router.url('jobs.list')` desde cualquier otro router. Si te fijas acá https://github.com/IIC2513-2020-1/my-university/blob/master/src/routes/session.js#L18 estoy llamando a una ruta que está en otro router.

Saludos,

**Comment by andresplass** [comment]
Claro, pero ahi  estaria definiendo denuevo JobsList y CommentsList, y la idea es usar los que fueron definidos en el route de Jobs y Comments (entiendo que esa es la solucion facil).
Además, faltaria las funciones newjobPath,editjobPath,deletejobPath que siguiendo lo que me dice, tendria que tambien re definirlas y al final de a poco estaria copiando y pegando todo lo que definí en las routes de cada uno, dentro del myself.

Edit: me lo imagino como en python, que uno si queria usar funciones de otro modulo, ponia import * from '/...' lo que permitia usar las funciones del modulo, incluyendo variables. Eso queremos, en vez de definir todo por segunda vez

**Comment by gpvidal** [comment]
Cómo definiste `JobsList` y `CommentsList`?

**Comment by andresplass** [comment]
En Jobs.js
```javascript
router.get('jobs.list', '/', async (ctx) => {
  const jobsList = await ctx.orm.job.findAll();
  console.log(jobsList);
  await ctx.render('jobs/index', {
    jobsList,
    newjobPath: ctx.router.url('jobs.new'),
    editjobPath: (job) => ctx.router.url('jobs.edit', { id: job.id }),
    deletejobPath: (job) => ctx.router.url('jobs.delete', { id: job.id }),
  });
});
``` 
lo mismo para CommentsList en comments.js

**Comment by gpvidal** [comment]
Y tu quieres llevar todo eso al nuevo router para mezclarlo con los comments?

**Comment by andresplass** [comment]
Claro, quiero esas variables (List) y funciones de New/Edit/Delete de multiples Routes (Jobs, Comments, etc...) a esta nueva view

**Comment by gpvidal** [comment]
Lo que puedes hacer es que, antes de que se ejecuten esas rutas, agregar un *middleware* que guarde toda esa información en `ctx.state`. De esa forma la tendrás disponible en las vistas y las habrás calculado solo una vez :wink: 

Saludos,

**Comment by andresplass** [comment]
Si es que tiene tiempo, me podría ayudar con como escribir eso y donde?? que no entiendo muy bien el funcionamiento o la unión de las routes y el router.

gracias profesor

**Comment by gpvidal** [comment]
Puedes ver el ejemplo de la autenticación de `my-university`. Ahí en `src/routes.js` hay un *middleware* para agregar el `currentUser`.

**Comment by andresplass** [comment]
Con ese lo logré, gracias profe!
