### ISSUE TITLE
Package Sequelize-file

### ISSUE THREAD

**Issue by Cadagan** [IIC2513-2020-1/syllabus#81]
Mi duda es simple: podemos usar el paquete "sequalize files" para manejar atributos tipo imagenes?

Lo digo por lo que sale en [este enlace de stackoverflow](https://stackoverflow.com/questions/47701640/saving-images-with-sequelize)

Muchas gracias de antemano :grin:

**Comment by Cadagan** [comment]
Dejo aqui la documentacion por si a alguien le sirve: 
https://www.npmjs.com/package/sequelize-file

 (en caso de que podamos usarlo claro)

**Comment by gpvidal** [comment]
Hola @Cadagan ,

No pueden ocupar este paquete.

De hecho, no es buena idea que guarden ese tipo de información en la base de datos. Te recomiendo ver el video de upload de archivos :wink: 

Saludos,

**Comment by Cadagan** [comment]
Entonces al agregar un atributo tipo imagenes, lo definimos como tipo BLOB?

**Comment by gpvidal** [comment]
Si quieres guardar una referencia a un archivo creas una columna de tipo string y guardas ahí la URL o el identificador que tengas :+1: 

Saludos,

**Comment by Cadagan** [comment]
Buenisimo! ahi ya cache como hacerlo con el servicio externo de amazon! :raised_hands::raised_hands::raised_hands: Muchas gracias!
