### ISSUE TITLE
propiedades privadas en clases de js

### ISSUE THREAD

**Issue by Kitaps** [IIC2513-2020-1/syllabus#82]
Hola, 

estuve revisando el taller C10 de Prototype.
Me llamó la atención el ejercicio 2. 

Al final ninguno de los atributos es privado? 

Revisando Internet a la rápida no me funcionó ninguna de las maneras para hacer que las properties no pudiesen ser accedidas (get) ni modificadas (set) desde afuera.

**Comment by gpvidal** [comment]
Hola @Kitaps !

Efectivamente! En Javascript nada es "privado". Aunque ese ejercicio tiene que ver con la accesibilidad.

En el caso de los parámetros de la función tienen accesibilidad privada, ya que solo pueden ser accedidas desde dentro de la función.

El caso de las privilegiadas, pueden ser accedidas publicamente y también tienen acceso a aquellas que tienen accesibilidad privada.

Para las públicas, son aquellas que se pueden acceder desde el exterior.

Saludos,

**Comment by gpvidal** [comment]
PD: Recuerdo haber visto en el TC39 una *keyword* para declarar algo privado. No sé en qué etapa está eso.

**Comment by Kitaps** [comment]
> En el caso de los parámetros de la función tienen accesibilidad privada, ya que solo pueden ser accedidas desde dentro de la función.

Pero por ejemplo yo puedo sin problema desde fuera de la función hacer: 
```
console.log(nokia._manufacturer)
nokia.manufacturer = "Yo";
console.log(nokia.manufacturer)
```
y accedo desde fuera de la función. Si no, a que te refieres con accesibilidad privada?

**Comment by gpvidal** [comment]
por ejemplo:

```js
function Car(carBrand) {
  // ...
} 
```

En dónde puedes acceder a `carBrand`? Sólo dentro de la función.

**Comment by PaoloFabia** [comment]
Hola! 
También tengo dudas con respecto a los atributos privados, públicos o privilegiados. Por ejemplo, si pruebo con:

````
function Cine(nombre, peliculas){
    this.nombre = nombre;
    this.peliculas = peliculas; 
    this.printPeliculas = function(){
        console.log(this.peliculas);
    }
    this.actualizarPelis = function(n){
        this.peliculas = n;
    }
}

var cine = new Cine("hoyts", 6);
console.log(cine.nombre)
````
 En este caso sí puedo acceder al nombre (o eso me permite jupyter), sin embargo, está dentro del contexto de la función. 
Gracias de antemano!

**Comment by gpvidal** [comment]
Wow wow wow... alto ahí @PaoloFabia ! :stuck_out_tongue: 

¿A qué `nombre` accede? 
* al que está definido en esta línea? `function Cine(nombre, peliculas){`
* o al que está definido en `this.nombre = nombre;`

Saludos!

**Comment by Kitaps** [comment]
al de `this.nombre` no?

pero no es lo mismo?

**Comment by gpvidal** [comment]
Que tengan el mismo valor? Claro que tienen el mismo valor.

Acceder al parámetro de la función es lo mismo que acceder a la propiedad que está en `this`? Esto no es lo mismo.

Saludos,

**Comment by Kitaps** [comment]
ah no, claro

**Comment by gpvidal** [comment]
Igual una precisión:

> Que tengan el mismo valor? Claro que tienen el mismo valor.

Esto es solo válido al principio, después si tu asignas un valor a `this.name` esto cambia.
