### ISSUE TITLE
Plataforma para subir archivos

### ISSUE THREAD

**Issue by matiasop** [IIC2513-2020-1/syllabus#83]
Hola,

Después de ver el video de archivos traté de crear una cuenta en Digital Ocean, pero pareciese que se necesita una tarjeta de crédito. Lo mismo para amazon web services y google web services.

¿Existirá alguna alternativa que no requiera uso de tarjeta de crédito? ¿O alguna manera de subir acrhivos de manera local para este curso?

**Comment by KnowYourselves** [comment]
Hola!

No soy ayudante, pero lo que hicimos en nuestro grupo fue crear una tarjeta con la aplicación MACH y transferirle mil pesos. Amazon te acepta esa tarjeta sin ningun problema y te hace un cargo de un dolar solo para corroborar que tiene dinero.

**Comment by matiasop** [comment]
Parece que mach es buena opción. Nos va a solucionar el problema.

Gracias por responder!

**Comment by gpvidal** [comment]
Hola a ambos!

Solo por completitud, creo que cloudinary tiene espacio gratis, sin tarjeta. Al menos así era el semestre pasado.

Saludos,

PD: Bien ahí @KnowYourselves ! No es necesario ser ayudante para "ayudar" al resto :wink:
