### ISSUE TITLE
Configuración de SendGrid y nodemailer

### ISSUE THREAD

**Issue by FloValdes** [IIC2513-2020-1/syllabus#84]
Hola, intenté seguir el video para configurar el email pero no logro entender qué tengo que hacer con SendGrid. Creé una api key y usé lo que me decían como usuario y contraseña (también intenté con el usuario y contraseña de la cuenta de SendGrid) pero siempre me lanza el error "Missing credentials for "PLAIN"".

Creo que tiene algo que ver con poner las contraseñas como texto plano pero no entiendo bien cómo hacerlo.

Gracias.

**Comment by gpvidal** [comment]
Hola @FloValdes ,

Pusiste `apikey` como usuario? Aquí hay una indicación sobre el usuario y password que debes colocar:

https://sendgrid.com/docs/API_Reference/SMTP_API/integrating_with_the_smtp_api.html

Saludos,

**Comment by FloValdes** [comment]
Gracias por la respuesta, sí eso puse, aunque también dice que tengo que setear un puerto, tengo que hacer eso?

Me sigue saliendo "Missing credentials for "PLAIN".

**Comment by gpvidal** [comment]
Las credenciales deberían ser como usuario `apikey` y, la clave, la API key generada por SendGrid

**Comment by FloValdes** [comment]
No sé bien qué cambié, pero ahora funcionó! gracias.

**Comment by JJJGGGG** [comment]
Hola, nos dió el mismo error. Faltaba un
```js
require('dotenv').config()
```
Podrían agregarlo al template, hace falta en config/database.js y en config/mailer.js

**Comment by gpvidal** [comment]
Hola @JJJGGGG ,

No se debe agregar al template, no todos ocupan `dotenv`.

Saludos,
