### ISSUE TITLE
Base de datos sin modelos

### ISSUE THREAD

**Issue by andresplass** [IIC2513-2020-1/syllabus#86]
Hola, en vez de agregar listas en los modelos ya presentes, tenemos la idea de crear tablas que unan datos.
Ejemplo, tenemos Usuarios, Ofertas, Comentarios.
Para que un usuario haga un comentario en una oferta, esta la idea de hacer una tabla que una
id_usuario, id_oferta, id_comentario.
Es posible hacer una tabla en psql (CREATE TABLE) que tenga estas tres columnas, sin necesidad de hacer otro modelo, y de ser así, como podría "llamarla" para poder trabajarla.
Tenemos la teoria que es con el router.get('nueva_tabla.list', ....) para el llamado.

**Comment by gpvidal** [comment]
Hola @andresplass ,

Pero eso responde a tu modelación? Tu comentario es solo un identificador con un texto?

Saludos,

**Comment by andresplass** [comment]
Sí responde en sentido que es la union entre esos modelos.
Lo que quiero es no tener que crear modelos innecesarios, solo mantener una tabla en mi DB que tenga por ejemplo |id_usuario| id_oferta| id_comentario| estado| sin necesidad de hacer otro modelo.
y yo despues poder cargar esta tabla como una lista no más, no complicarse tanto. Pero, no se si es posible

**Comment by gpvidal** [comment]
mmm... me quedan dudas.

De todas formas, y para responder tu pregunta, no puedes hacer una tabla sin un modelo. Esto porque lo estás trabajando sobre un ORM (sequelize). 

Lo que si puedes tener es un modelo sin tabla en la base de datos.

Saludos,

**Comment by andresplass** [comment]
Ya profesor muchas gracias
