### ISSUE TITLE
Importar un modelo en otro

### ISSUE THREAD

**Issue by ibaeza1** [IIC2513-2020-1/syllabus#87]
Hola!
Tengo un modelo service.js y quiero hacer la asociacion hasMany(comment) y tengo un modelo comment.js ambos en mi carpeta de models
Cuando hago service.hasMany(comment) me dice que comment no esta definido. Creo que esto es porque tengo que importar el modelo comment en service, pero no entiendo bien como hacer eso.
Mi objetivo es poder comentar el servicio y que quede asociado, y esta es la unica forma que se me ocurre. Si hay otra forma también me ayudaria mucho :)
Gracias!

**Comment by gpvidal** [comment]
Hola @ibaeza1 ,

Puedes revisar esta *issue*:

https://github.com/IIC2513-2020-1/syllabus/issues/42

Saludos!
