### ISSUE TITLE
Error al hacer deploy: integrity check failed

### ISSUE THREAD

**Issue by matiaseche** [IIC2513-2020-1/syllabus#88]
Hola, estoy teniendo un error al hacer el deploy a heroku y no sé qué lo está causando.
![error](https://user-images.githubusercontent.com/29207183/81516508-1fc03b00-9306-11ea-9a7a-cff11638a150.png)

Probé correr `yarn install --check-files` y me tira el mismo error que aparece en la imagen.

**Comment by gpvidal** [comment]
Hola @matiaseche ,

Aún tienes este problema? Podría deberse a un error temporal de red.

Saludos,

**Comment by matiaseche** [comment]
Hola @gpvidal, logré solucioanrlo pero encontré un poco "penca" mi solución.
Lo que hice fue copiar el yarn.lock del repositorio `my-university` y funcionó.

**Comment by gpvidal** [comment]
Ahhh eso abre varias interrogantes :stuck_out_tongue: 

No tendrás por ahí un archivo `package-lock.json`? Quizás alguno está mezclando `npm` con `yarn`. O a alguno le falló alguna instalación e hizo push del `yarn.lock` igual

**Comment by matiaseche** [comment]
Si! Eso creemos que pudo haber causado el problema, borramos `package-lock.json`, creemos que uno usó `npm` y otro `yarn`, ahora estamos todos en la misma página!

**Comment by gpvidal** [comment]
Excelente! que buen que se solucionó :+1:
