### ISSUE TITLE
Error al correr yarn dev

### ISSUE THREAD

**Issue by niguzman** [IIC2513-2020-1/syllabus#89]
Hola, estoy teniendo el sgte error :C 
![image](https://user-images.githubusercontent.com/48304981/81589453-70c44380-9387-11ea-9b29-9f5ce47d1f95.png)
Lo raro es que igual termina de compilar pero cuando me meto a localhost no me carga la página

**Comment by gpvidal** [comment]
Hola @niguzman ,

Tu error está justo ahí: Tienes problemas para conectarte a la base de datos :wink: 

Saludos,

**Comment by niguzman** [comment]
Y cómo se soluciona?

**Comment by gpvidal** [comment]
Revisaste las variables de entorno? Que la base de datos esté creada? Hay un par de issues, que ya fueron cerradas, que tienen información sobre este error.

**Comment by niguzman** [comment]
Las tengo configuradas en un archivo .env, tengo el require('dotenv').config() en el data base e hice el createdb iic2513template_dev

**Comment by gpvidal** [comment]
Si haces un 
```js
console.log(process.env.DB_USERNAME);
```
y lo colocas bajo `const PORT = process.env.PORT || 3000;` en `index.js` (el que está en la raíz de tu proyecto).

Que te aparece arriba de `Unable to connect to the database:` en la consola al hacer `yarn dev`?

**Comment by niguzman** [comment]
Ya lo solucioné, me ayudó Kim :D
