### ISSUE TITLE
Casos de uso "Happy Path"

### ISSUE THREAD

**Issue by Kitaps** [IIC2513-2020-1/syllabus#9]
Hola, 
en la issue #7 hablaron de casos de uso. 
Me surgió una duda respecto a que tan completos tienen que ser. 

Mi duda principal es si es que basta con que consideramos el happy path, es decir el Actor, Descripción, Flujo normal y condiciones de satisfacción. O también hay que hacer todos los posibles flujos alternativos?

P.D.: Relatos de usuario no sirven?

**Comment by gpvidal** [comment]
Hola @Kitaps ,

También sería bueno saber si tienen alguna pre-condición o post-condición, por ejemplo, si el usuario tiene que estar registrado o haber ingresado a la plataforma.

No es necesario hacer todos los flujos alternativos, pero si hay alguno importante hay que colocarlo. Por ejemplo, si voy a hacer una compra y no tengo saldo ¿Qué pasa? Este sí sería un flujo relevante.

Finalmente, relatos o historias de usuario `!=` casos de uso, por lo que en esta entrega no sirven.

Saludos,

**Comment by Kitaps** [comment]
Gracias
