### ISSUE TITLE
Duda ruta de assets

### ISSUE THREAD

**Issue by cacoos** [IIC2513-2020-1/syllabus#90]
Hola!

Estuve investigando un poco cómo funcionaba la importación de assets. Vi que hay una función que se llama `assetPath(path)` que simplemente retorna "assets/path" cuando estamos en _dev_.

Luego, en algunas vistas como _layout.html.ejs_ se usa `assetPath('image.png')` directamente. Sé que en _assets/js/index.js_ importa la imagen pero, ¿cómo llegó a este index? ¿en qué momento se importaron todos los archivos?

Me pasa lo mismo con los scss.

Muchas gracias!

**Comment by gpvidal** [comment]
Hola @cacosandon !

Es una muy buena pregunta! Y estaba pensando que quizás podríamos hacer una clase de cómo funciona el template para aquellos que quieran saber.

Toda la magia en el template de los assets, scss y js del lado del cliente (React principalmente) es visto por una herramienta que se llama `webpack`. Esta herramienta se encarga de tomar tu código, generar los archivos necesarios (estilos, React y assets) para desplegar tu sitio. Eso en palabras simples.

Si tu quieres saber más me avisas y si hay interés podemos hacer una clase de eso :+1: 

Saludos,

**Comment by cacoos** [comment]
Gracias por la respuesta!

Ahora todo me hace sentido después de investigar `webpack` jajaj. De todas formas si hay más gente interesada sería buenísimo conocer más del template y de todos los módulos que se incorporan!

Saludos y gracias de nuevo :)
