### ISSUE TITLE
Ejercicio JQuery

### ISSUE THREAD

**Issue by stmorales** [IIC2513-2020-1/syllabus#91]
Hola!!

Les escribo con una duda sobre el ejercicio de JQuery que tenemos. No entiendo porque con el siguiente código cuando apreto el botón de `More Info` no se despliega nada.

![image](https://user-images.githubusercontent.com/42178490/81615017-e98ac600-93ae-11ea-9f09-08ccb41e2385.png)

Pero cuando lo hago de la siguiente manera si lo hace. 

![image](https://user-images.githubusercontent.com/42178490/81614860-a892b180-93ae-11ea-89b4-5335b7717661.png)

Les agradecería su me pudiesen explicar porque JQuery tiene este comportamiento?

Muchas gracias!

**Comment by gpvidal** [comment]
Hola @stmorales !

Qué bueno que hiciste el ejercicio! :tada: Es muy difícil decirte, viendo sólo el código JS, cuál es el error; sin embargo, me doy cuenta que navegaste por los hijos de un elemento y probablemente alguno de ellos es nulo.

Te recomiendo, para encontrar el error, ver si en la consola de tu navegador dice algo. Si no dice nada, entonces hay que revisar si alguna de tus variables es nula en algún punto (colocando `console.log` en algunos puntos).

De todas formas, más que navegar por hijos y así, te recomiendo colocar identificadores o buscar los elementos que deseas por el selector de jQuery, ya que así es más fácil encontrar el error :wink: 

Saludos,

**Comment by gpvidal** [comment]
Ah! lo olvide! Subí la solución :wink:

**Comment by stmorales** [comment]
Muchas gracias profesor!

Estaba intentando hacer el ejercicio sin agregar nada al archivo html, a ver si podía!

Gracias por los tips!

Saludos,
