### ISSUE TITLE
Heroku problema con cambios de modelos

### ISSUE THREAD

**Issue by andresplass** [IIC2513-2020-1/syllabus#92]
Hola para la entrega 1 nos funcionó bien heroku. Desde ese entonces hemos hecho cambios a nivel de modelo, agregar parametros y tablas a psql.

Para esta entrega de mañana, hicimos el  git subtree push --prefix freelancer heroku master 
y efectivamente se subió bien.
Nuestro localhost tambien funciona de maravilla, pero al momento de entrar en el link de heroku, ya desde el inicio tiene problemas con todos los modelos:

Dentro de los logs logramos captar, problemas del tipo relation "users" is not define o column "tag_admin" doesn't exist, que son clasicos problemas con psql, que no ocurren en nuestro localhost. 
Qué podría ser?? muchas gracias de antemanoo

**Comment by gpvidal** [comment]
Yo sé por qué es! :stuck_out_tongue: 

Te apuesto que, en vez de crear nuevas migraciones para agregar columnas a tus modelos, las agregabas a la migración de tu modelo.

Ok, es por este motivo que es bueno hacer migraciones con cada cambio por separado. Sequelize guarda en tu base de datos la última migración que corrió, por lo que si modificaste una migración que ya corrió esta no correrá de nuevo.

La solución a tu problema? Reiniciar y correr de nuevo todas las migraciones

**Es una solución? Claro que no!!!**

Imagínate que tu proyecto tiene usuarios reales y datos reales. Te ocurre este problema y tienes que reiniciar tu base de datos... **Vas a perder TODOS los datos!**

Ok, alguien podría decir: "bueno, pero podríamos meternos a la base de datos y agregar las columnas a mano"

Eso efectivamente es correcto, pero... para qué usaron migraciones? :confused: 

Por eso es siempre recomendable que **cada cambio que hagan en la estructura de su base de datos quede reflejada en una migración, y no reescriban migraciones después de haberlas ejecutado** :wink: 

Saludos!

**Comment by andresplass** [comment]
Hola profe, gracias por la respuesta,
No, no hicimos eso, podria decir que es parecido, para agregarle un nuevo parametro a un modelo, con yo @iic... al final creabamos el mismo (con un parametro mas) y lo sobreescribiamos, (nos preguntaba de hecho que ya existia y si queriamos sobreescribir) 

Edit: Lo solucionamos eliminando migraciones duplicadas que al parecer por estar duplicadas impedian que se creara el modelo en heroku, ahora funciona bien
