### ISSUE TITLE
Jupiter phobos

### ISSUE THREAD

**Issue by BlancaMunizaga** [IIC2513-2020-1/syllabus#93]
Hola profesor!
tengo un problema para usar el Jupiter del curso, me sale este error:
500 : Internal Server Error
Failed to start your server on the last attempt. Please contact admin if the issue persists.
You can try restarting your server from the home page.
Intente poner start my server pero no funciona. 
Que puedo hacer?

saludos  Blanca

**Comment by gpvidal** [comment]
Hola @BlancaMunizaga ,

Los estoy revisando!

Saludos

**Comment by gpvidal** [comment]
Listo @BlancaMunizaga ! :wink:

**Comment by BlancaMunizaga** [comment]
gracias! ahora funciona :)
