### ISSUE TITLE
Jupyter phobos

### ISSUE THREAD

**Issue by fernandamansilla** [IIC2513-2020-1/syllabus#95]
Hola, tengo un problema con el jupyter del curso. Cuando intento ingresar me sale este error :(
500 : Internal Server Error
Failed to reach your server. Please try again later. Contact admin if the issue persists.
You can try restarting your server from the home page.

Intente reiniciarlo desde mi pagina de inicio y me salio esto:

500 : Internal Server Error
Spawner failed to start [status=1]. The logs for fernandamansilla may contain details.
You can try restarting your server from the home page.

Que puedo hacer?

**Comment by gpvidal** [comment]
Hola @fernandamansilla !

Listo! debería estar resuelto.

Saludos,

**Comment by fernandamansilla** [comment]
Hola! Me sigue saliendo el mismo error

**Comment by fernandamansilla** [comment]
Funcionó, gracias!!
